In [112]:
import polars as pl

In [113]:
df = pl.read_parquet(
    '/Users/evrins/workspace/python/DNF_pvf_python/dnfpkgtool/repo/data/equipments.parquet'
)
df

shape: (63_788, 30)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id        ┆ name      ┆ name2     ┆ json      ┆ … ┆ armor_typ ┆ display_e ┆ display_r ┆ display_ │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ e         ┆ quipment_ ┆ arity     ┆ usable_j │
│ i64       ┆ str       ┆ str       ┆ str       ┆   ┆ ---       ┆ type      ┆ ---       ┆ ob       │
│           ┆           ┆           ┆           ┆   ┆ str       ┆ ---       ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆ str       ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 10018     ┆ (旧) 古老 ┆ Old Wool  ┆ {"[name]" ┆ … ┆ cl        ┆ 上衣      ┆ 普通      ┆ 全部职业 │
│           ┆ 的羊毛背  ┆ Vest      ┆ : ["(旧)  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 心        ┆           ┆ 古老的羊  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 毛背心"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[…       ┆   ┆           ┆           ┆           ┆          │
│ 10019     ┆ (旧)      ┆ Wool Vest ┆ {"[name]" ┆ … ┆ cl        ┆ 上衣      ┆ 高级      ┆ 全部职业 │
│           ┆ 羊毛背心  ┆           ┆ : ["(旧)  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 羊毛背心" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ], "[nam… ┆   ┆           ┆           ┆           ┆          │
│ 10020     ┆ (旧)      ┆ Robe of   ┆ {"[name]" ┆ … ┆ cl        ┆ 上衣      ┆ 稀有      ┆ 全部职业 │
│           ┆ 炎麻长袍  ┆ Carbon    ┆ : ["(旧)  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Fiber     ┆ 炎麻长袍" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ], "[nam… ┆   ┆           ┆           ┆           ┆          │
│ 10021     ┆ (旧) 厚绒 ┆ Thick     ┆ {"[name]" ┆ … ┆ cl        ┆ 上衣      ┆ 高级      ┆ 全部职业 │
│           ┆ 羊毛背心  ┆ Wool Vest ┆ : ["(旧)  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 厚绒羊毛  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 背心"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[n…      ┆   ┆           ┆           ┆           ┆          │
│ 10022     ┆ (旧) 旧式 ┆ Outdated  ┆ {"[name]" ┆ … ┆ cl        ┆ 上衣      ┆ 普通      ┆ 全部职业 │
│           ┆ 丝绸背心  ┆ Wool      ┆ : ["(旧)  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Tunic     ┆ 旧式丝绸  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 背心"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[n…      ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 101600008 ┆ 阿尔托莉  ┆           ┆ {"[name]" ┆ … ┆           ┆ 脸部装扮  ┆ 普通      ┆ 鬼剑士,  │
│           ┆ 雅的佩剑  ┆           ┆ : ["阿尔  ┆   ┆           ┆           ┆           ┆ 黑暗武士 │
│           ┆           ┆           ┆ 托莉雅的  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 佩剑"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[exp…    ┆   ┆           ┆           ┆           ┆          │
│ 400990109 ┆ 迷你皇女  ┆           ┆ {"[name]" ┆ … ┆           ┆ 宠物      ┆ 史诗      ┆ 全部职业 │
│           ┆ 艾丽婕    ┆           ┆ : ["迷你  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 皇女艾丽  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 婕"],     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[expl…   ┆   ┆           ┆           ┆           ┆          │
│ 400990502 ┆ 迷你冲浪  ┆           ┆ {"[name]" ┆ … ┆           ┆ 宠物      ┆ 史诗      ┆ 全部职业 │
│           ┆ 赛丽亚    ┆           ┆ : ["迷你  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 冲浪赛丽  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 亚"],     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[expl…   ┆   ┆           ┆           ┆           ┆          │
│ 400990078 ┆ 灵动小龙  ┆           ┆ {"[name]" ┆ … ┆           ┆ 宠物      ┆ 神器      ┆ 全部职业 │
│           ┆ 女        ┆           ┆ : ["灵动  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 小龙女"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[flavor… ┆   ┆           ┆           ┆           ┆          │
│ 400990077 ┆ 热辣小龙  ┆           ┆ {"[name]" ┆ … ┆           ┆ 宠物      ┆ 神器      ┆ 全部职业 │
│           ┆ 女        ┆           ┆ : ["热辣  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 小龙女"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[explai… ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [114]:
df.schema

Schema([('id', Int64),
        ('name', String),
        ('name2', String),
        ('json', String),
        ('level', Int64),
        ('rarity', Int64),
        ('equipment_type', String),
        ('sub_equipment_type', Int64),
        ('item_group_name', String),
        ('usable_job', List(String)),
        ('physical_attack', Int64),
        ('magical_attack', Int64),
        ('physical_defense', Int64),
        ('magical_defense', Int64),
        ('physical_critical_hit', Float64),
        ('magical_critical_hit', Float64),
        ('all_elemental_attack', Int64),
        ('attack_speed', Int64),
        ('cast_speed', Int64),
        ('move_speed', Int64),
        ('room_list_move_speed_rate', Float64),
        ('mp_max_rate', Int64),
        ('set_name', String),
        ('set_item', List(Int64)),
        ('durability', Int64),
        ('sub_type', Int64),
        ('armor_type', String),
        ('display_equipment_type', String),
        ('display_rarity', String),
        ('display_usable_job', String)])

In [115]:
df.select(pl.col('equipment_type')).sort(pl.col('equipment_type')).unique()

shape: (27, 1)
┌──────────────────┐
│ equipment_type   │
│ ---              │
│ str              │
╞══════════════════╡
│                  │
│ [amulet]         │
│ [artifact blue]  │
│ [artifact green] │
│ [artifact red]   │
│ …                │
│ [title name]     │
│ [waist avatar]   │
│ [waist]          │
│ [weapon]         │
│ [wrist]          │
└──────────────────┘

In [116]:
df.filter((pl.col('equipment_type') == '[coat avatar]') & (pl.col('name') != ''))

shape: (3_483, 30)
┌───────────┬────────────┬───────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ id        ┆ name       ┆ name2 ┆ json       ┆ … ┆ armor_type ┆ display_e ┆ display_r ┆ display_u │
│ ---       ┆ ---        ┆ ---   ┆ ---        ┆   ┆ ---        ┆ quipment_ ┆ arity     ┆ sable_job │
│ i64       ┆ str        ┆ str   ┆ str        ┆   ┆ str        ┆ type      ┆ ---       ┆ ---       │
│           ┆            ┆       ┆            ┆   ┆            ┆ ---       ┆ str       ┆ str       │
│           ┆            ┆       ┆            ┆   ┆            ┆ str       ┆           ┆           │
╞═══════════╪════════════╪═══════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 103500119 ┆ 层叠式运动 ┆       ┆ {"[name]": ┆ … ┆            ┆ 上衣装扮  ┆ 普通      ┆ 格斗家-男 │
│           ┆ 衫[A型]    ┆       ┆ ["层叠式运 ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ 动衫[A型]" ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ ], "[n…    ┆   ┆            ┆           ┆           ┆           │
│ 103500120 ┆ 层叠式运动 ┆       ┆ {"[name]": ┆ … ┆            ┆ 上衣装扮  ┆ 普通      ┆ 格斗家-男 │
│           ┆ 衫[B型]    ┆       ┆ ["层叠式运 ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ 动衫[B型]" ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ ], "[n…    ┆   ┆            ┆           ┆           ┆           │
│ 103500121 ┆ 层叠式运动 ┆       ┆ {"[name]": ┆ … ┆            ┆ 上衣装扮  ┆ 普通      ┆ 格斗家-男 │
│           ┆ 衫[C型]    ┆       ┆ ["层叠式运 ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ 动衫[C型]" ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ ], "[n…    ┆   ┆            ┆           ┆           ┆           │
│ 103500122 ┆ 层叠式运动 ┆       ┆ {"[name]": ┆ … ┆            ┆ 上衣装扮  ┆ 普通      ┆ 格斗家-男 │
│           ┆ 衫[D型]    ┆       ┆ ["层叠式运 ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ 动衫[D型]" ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ ], "[n…    ┆   ┆            ┆           ┆           ┆           │
│ 103500123 ┆ 无袖上衣[A ┆       ┆ {"[name]": ┆ … ┆            ┆ 上衣装扮  ┆ 普通      ┆ 格斗家-男 │
│           ┆ 型]        ┆       ┆ ["无袖上衣 ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ [A型]"],   ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ "[nam…     ┆   ┆            ┆           ┆           ┆           │
│ …         ┆ …          ┆ …     ┆ …          ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 608500091 ┆ 海滩男孩棉 ┆       ┆ {"[name]": ┆ … ┆            ┆ 上衣装扮  ┆ 普通      ┆ 圣职者    │
│           ┆ 背心       ┆       ┆ ["海滩男孩 ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ 棉背心"],  ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ "[expl…    ┆   ┆            ┆           ┆           ┆           │
│ 609500090 ┆ 海滩罗曼史 ┆       ┆ {"[name]": ┆ … ┆            ┆ 上衣装扮  ┆ 普通      ┆ 暗夜使者  │
│           ┆ 挖腰泳装上 ┆       ┆ ["海滩罗曼 ┆   ┆            ┆           ┆           ┆           │
│           ┆ 衣         ┆       ┆ 史挖腰泳装 ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ 上衣"],    ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ "[…        ┆   ┆            ┆           ┆           ┆           │
│ 609500091 ┆ 海滩女孩两 ┆       ┆ {"[name]": ┆ … ┆            ┆ 上衣装扮  ┆ 普通      ┆ 暗夜使者  │
│           ┆ 件式泳衣   ┆       ┆ ["海滩女孩 ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ 两件式泳衣 ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ "], "[ex…  ┆   ┆            ┆           ┆           ┆           │
│ 607500076 ┆ 海滩罗曼史 ┆       ┆ {"[name]": ┆ … ┆            ┆ 上衣装扮  ┆ 普通      ┆ 魔法师-男 │
│           ┆ 罩衫外套   ┆       ┆ ["海滩罗曼 ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ 史罩衫外套 ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ "], "[ex…  ┆   ┆            ┆           ┆           ┆           │
│ 607500077 ┆ 海滩男孩紧 ┆       ┆ {"[name]": ┆ … ┆            ┆ 上衣装扮  ┆ 普通      ┆ 魔法师-男 │
│           ┆ 身泳衣上衣 ┆       ┆ ["海滩男孩 ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ 紧身泳衣上 ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ 衣"], "[e… ┆   ┆            ┆           ┆           ┆           │
└───────────┴────────────┴───────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [117]:
df.filter((pl.col('equipment_type') == '') & (pl.col('name') != ''))

shape: (8, 30)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id        ┆ name      ┆ name2     ┆ json      ┆ … ┆ armor_typ ┆ display_e ┆ display_r ┆ display_ │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ e         ┆ quipment_ ┆ arity     ┆ usable_j │
│ i64       ┆ str       ┆ str       ┆ str       ┆   ┆ ---       ┆ type      ┆ ---       ┆ ob       │
│           ┆           ┆           ┆           ┆   ┆ str       ┆ ---       ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆ str       ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2312900   ┆ 成长之契  ┆           ┆ {"[name]" ┆ … ┆           ┆ 契约效果  ┆ 高级      ┆ 全部职业 │
│           ┆ 约        ┆           ┆ : ["成长  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 之契约"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2]… ┆   ┆           ┆           ┆           ┆          │
│ 100300084 ┆ 黑色小晶  ┆ Black     ┆ {"[name]" ┆ … ┆           ┆ 契约效果  ┆ 普通      ┆ 全部职业 │
│           ┆ 块效果    ┆ Small     ┆ : ["黑色  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Cube      ┆ 小晶块效  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 果"],     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name…   ┆   ┆           ┆           ┆           ┆          │
│ 100300085 ┆ 蓝色小晶  ┆ Blue      ┆ {"[name]" ┆ … ┆           ┆ 契约效果  ┆ 普通      ┆ 全部职业 │
│           ┆ 块效果    ┆ Small     ┆ : ["蓝色  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Cube      ┆ 小晶块效  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 果"],     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name…   ┆   ┆           ┆           ┆           ┆          │
│ 100300086 ┆ 红色小晶  ┆ Red Small ┆ {"[name]" ┆ … ┆           ┆ 契约效果  ┆ 普通      ┆ 全部职业 │
│           ┆ 块效果    ┆ Cube      ┆ : ["红色  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 小晶块效  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 果"],     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name…   ┆   ┆           ┆           ┆           ┆          │
│ 100300087 ┆ 白色小晶  ┆ White     ┆ {"[name]" ┆ … ┆           ┆ 契约效果  ┆ 普通      ┆ 全部职业 │
│           ┆ 块效果    ┆ Small     ┆ : ["白色  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Cube      ┆ 小晶块效  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 果"],     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name…   ┆   ┆           ┆           ┆           ┆          │
│ 100300088 ┆ 无色小晶  ┆ Nonecolor ┆ {"[name]" ┆ … ┆           ┆ 契约效果  ┆ 普通      ┆ 全部职业 │
│           ┆ 块效果    ┆ Small     ┆ : ["无色  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Cube      ┆ 小晶块效  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 果"],     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name…   ┆   ┆           ┆           ┆           ┆          │
│ 100300089 ┆ 金色小晶  ┆ Gold      ┆ {"[name]" ┆ … ┆           ┆ 契约效果  ┆ 普通      ┆ 全部职业 │
│           ┆ 块效果    ┆ Small     ┆ : ["金色  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Cube      ┆ 小晶块效  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 果"],     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name…   ┆   ┆           ┆           ┆           ┆          │
│ 9944451   ┆ 黑钻契约  ┆           ┆ {"[name]" ┆ … ┆           ┆ 契约效果  ┆ 普通      ┆ 全部职业 │
│           ┆ 附加效果  ┆           ┆ : ["黑钻  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 契约附加  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 效果"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[nam…    ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [118]:
df.filter((pl.col('equipment_type') == '[amulet]') & (pl.col('name') != ''))

shape: (1_850, 30)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id        ┆ name      ┆ name2     ┆ json      ┆ … ┆ armor_typ ┆ display_e ┆ display_r ┆ display_ │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ e         ┆ quipment_ ┆ arity     ┆ usable_j │
│ i64       ┆ str       ┆ str       ┆ str       ┆   ┆ ---       ┆ type      ┆ ---       ┆ ob       │
│           ┆           ┆           ┆           ┆   ┆ str       ┆ ---       ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆ str       ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 20013     ┆ (旧) 褪色 ┆ Fade      ┆ {"[name]" ┆ … ┆           ┆ 项链      ┆ 普通      ┆ 全部职业 │
│           ┆ 的青铜项  ┆ Bronze    ┆ : ["(旧)  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 链        ┆ Chain     ┆ 褪色的青  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 铜项链"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[…       ┆   ┆           ┆           ┆           ┆          │
│ 20014     ┆ (旧)      ┆ Bronze    ┆ {"[name]" ┆ … ┆           ┆ 项链      ┆ 高级      ┆ 全部职业 │
│           ┆ 青铜项链  ┆ Chain     ┆ : ["(旧)  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 青铜项链" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ], "[nam… ┆   ┆           ┆           ┆           ┆          │
│ 20015     ┆ (旧) 精致 ┆ Azure     ┆ {"[name]" ┆ … ┆           ┆ 项链      ┆ 高级      ┆ 全部职业 │
│           ┆ 的青铜项  ┆ Bronze    ┆ : ["(旧)  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 链        ┆ Chain     ┆ 精致的青  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 铜项链"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[…       ┆   ┆           ┆           ┆           ┆          │
│ 20016     ┆ (旧) 哥布 ┆ Goblin    ┆ {"[name]" ┆ … ┆           ┆ 项链      ┆ 稀有      ┆ 全部职业 │
│           ┆ 林冥骨项  ┆ Bone      ┆ : ["(旧)  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 坠        ┆ Necklace  ┆ 哥布林冥  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 骨项坠"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[…       ┆   ┆           ┆           ┆           ┆          │
│ 20017     ┆ (旧) 磨损 ┆ Peeled    ┆ {"[name]" ┆ … ┆           ┆ 项链      ┆ 普通      ┆ 全部职业 │
│           ┆ 的镀银项  ┆ Silver    ┆ : ["(旧)  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 链        ┆ Coating   ┆ 磨损的镀  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Necklace  ┆ 银项链"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[…       ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 100310870 ┆ 执刑者的  ┆           ┆ {"[name]" ┆ … ┆           ┆ 项链      ┆ 史诗      ┆ 全部职业 │
│           ┆ 刺杀项链  ┆           ┆ : ["执刑  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 者的刺杀  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 项链"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[bas…    ┆   ┆           ┆           ┆           ┆          │
│ 300300000 ┆ MLA-014   ┆           ┆ {"[name]" ┆ … ┆           ┆ 项链      ┆ 神器      ┆ 全部职业 │
│           ┆ 机械项圈( ┆           ┆ :         ┆   ┆           ┆           ┆           ┆          │
│           ┆ 附加伤害) ┆           ┆ ["MLA-014 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 机械项圈( ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 附加伤害… ┆   ┆           ┆           ┆           ┆          │
│ 300300001 ┆ MLA-014   ┆           ┆ {"[name]" ┆ … ┆           ┆ 项链      ┆ 神器      ┆ 全部职业 │
│           ┆ 机械项圈( ┆           ┆ :         ┆   ┆           ┆           ┆           ┆          │
│           ┆ 冷却时间) ┆           ┆ ["MLA-014 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 机械项圈( ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 冷却时间… ┆   ┆           ┆           ┆           ┆          │
│ 300300002 ┆ MLA-014   ┆           ┆ {"[name]" ┆ … ┆           ┆ 项链      ┆ 神器      ┆ 全部职业 │
│           ┆ 机械项圈( ┆           ┆ :         ┆   ┆           ┆           ┆           ┆          │
│           ┆ 暴击伤害) ┆           ┆ ["MLA-014 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 机械项圈( ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 暴击伤害… ┆   ┆           ┆           ┆           ┆          │
│ 600300000 ┆ OnTime    ┆ ontime    ┆ {"[name]" ┆ … ┆           ┆ 项链      ┆ 稀有      ┆ 全部职业 │
│           ┆ 绝对项链  ┆ neck      ┆ :         ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ["OnTime  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 绝对项链" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ], "[…    ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [119]:
df.filter((pl.col('equipment_type') == '[artifact green]') & (pl.col('name') != ''))

shape: (23, 30)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id        ┆ name      ┆ name2     ┆ json      ┆ … ┆ armor_typ ┆ display_e ┆ display_r ┆ display_ │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ e         ┆ quipment_ ┆ arity     ┆ usable_j │
│ i64       ┆ str       ┆ str       ┆ str       ┆   ┆ ---       ┆ type      ┆ ---       ┆ ob       │
│           ┆           ┆           ┆           ┆   ┆ str       ┆ ---       ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆ str       ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 64500     ┆ Artifect  ┆ Artifect  ┆ {"[name]" ┆ … ┆           ┆ 绿色      ┆ 稀有      ┆ 全部职业 │
│           ┆ Green     ┆ Green     ┆ : [""],   ┆   ┆           ┆ 宠物装备  ┆           ┆          │
│           ┆           ┆           ┆ "[name2]" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ : ["…     ┆   ┆           ┆           ┆           ┆          │
│ 64501     ┆ 翡翠宝珠  ┆ Orb of    ┆ {"[name]" ┆ … ┆           ┆ 绿色      ┆ 稀有      ┆ 全部职业 │
│           ┆           ┆ Emerald   ┆ : ["翡翠  ┆   ┆           ┆ 宠物装备  ┆           ┆          │
│           ┆           ┆           ┆ 宝珠"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2]" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆          │
│ 64502     ┆ 风之宝珠  ┆ Orb of    ┆ {"[name]" ┆ … ┆           ┆ 绿色      ┆ 稀有      ┆ 全部职业 │
│           ┆           ┆ Wind      ┆ : ["风之  ┆   ┆           ┆ 宠物装备  ┆           ┆          │
│           ┆           ┆           ┆ 宝珠"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2]" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆          │
│ 64503     ┆ 翡翠冠饰  ┆ Tiara of  ┆ {"[name]" ┆ … ┆           ┆ 绿色      ┆ 稀有      ┆ 全部职业 │
│           ┆           ┆ Emerald   ┆ : ["翡翠  ┆   ┆           ┆ 宠物装备  ┆           ┆          │
│           ┆           ┆           ┆ 冠饰"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2]" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆          │
│ 64505     ┆ 风之冠饰  ┆ Tiara of  ┆ {"[name]" ┆ … ┆           ┆ 绿色      ┆ 稀有      ┆ 全部职业 │
│           ┆           ┆ Wind      ┆ : ["风之  ┆   ┆           ┆ 宠物装备  ┆           ┆          │
│           ┆           ┆           ┆ 冠饰"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2]" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 2747198   ┆ 灵咒之罪  ┆           ┆ {"[name]" ┆ … ┆           ┆ 绿色      ┆ 神器      ┆ 全部职业 │
│           ┆ 恶密钥    ┆           ┆ : ["灵咒  ┆   ┆           ┆ 宠物装备  ┆           ┆          │
│           ┆           ┆           ┆ 之罪恶密  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 钥"],     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[mini…   ┆   ┆           ┆           ┆           ┆          │
│ 2747199   ┆ 灵咒之魔  ┆           ┆ {"[name]" ┆ … ┆           ┆ 绿色      ┆ 神器      ┆ 全部职业 │
│           ┆ 女宝珠    ┆           ┆ : ["灵咒  ┆   ┆           ┆ 宠物装备  ┆           ┆          │
│           ┆           ┆           ┆ 之魔女宝  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 珠"],     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[mini…   ┆   ┆           ┆           ┆           ┆          │
│ 100330622 ┆ 希望之胜  ┆           ┆ {"[name]" ┆ … ┆           ┆ 绿色      ┆ 神器      ┆ 全部职业 │
│           ┆ 利红宝石  ┆           ┆ : ["希望  ┆   ┆           ┆ 宠物装备  ┆           ┆          │
│           ┆ 钥匙      ┆           ┆ 之胜利红  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 宝石钥匙" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ], "[m…   ┆   ┆           ┆           ┆           ┆          │
│ 10006770  ┆ 青龙偃月  ┆           ┆ {"[name]" ┆ … ┆           ┆ 绿色      ┆ 神器      ┆ 全部职业 │
│           ┆ 刀        ┆           ┆ : ["青龙  ┆   ┆           ┆ 宠物装备  ┆           ┆          │
│           ┆           ┆           ┆ 偃月刀"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[flavor… ┆   ┆           ┆           ┆           ┆          │
│ 10006773  ┆ 清爽哈密  ┆           ┆ {"[name]" ┆ … ┆           ┆ 绿色      ┆ 神器      ┆ 全部职业 │
│           ┆ 瓜冰沙    ┆           ┆ : ["清爽  ┆   ┆           ┆ 宠物装备  ┆           ┆          │
│           ┆           ┆           ┆ 哈密瓜冰  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 沙"],     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[flav…   ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [120]:
df.filter((pl.col('equipment_type') == '[aurora avatar]') & (pl.col('name') != ''))

shape: (268, 30)
┌───────────┬────────────┬───────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ id        ┆ name       ┆ name2 ┆ json       ┆ … ┆ armor_type ┆ display_e ┆ display_r ┆ display_u │
│ ---       ┆ ---        ┆ ---   ┆ ---        ┆   ┆ ---        ┆ quipment_ ┆ arity     ┆ sable_job │
│ i64       ┆ str        ┆ str   ┆ str        ┆   ┆ str        ┆ type      ┆ ---       ┆ ---       │
│           ┆            ┆       ┆            ┆   ┆            ┆ ---       ┆ str       ┆ str       │
│           ┆            ┆       ┆            ┆   ┆            ┆ str       ┆           ┆           │
╞═══════════╪════════════╪═══════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 107590007 ┆ 迅捷的奥拉 ┆       ┆ {"[name]": ┆ … ┆            ┆ 光环      ┆ 普通      ┆ 格斗家    │
│           ┆ 光环[格斗  ┆       ┆ ["迅捷的奥 ┆   ┆            ┆           ┆           ┆           │
│           ┆ 家(女)]    ┆       ┆ 拉光环[格  ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ 斗家(女)]" ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ ]…         ┆   ┆            ┆           ┆           ┆           │
│ 107590009 ┆ 迅捷的奥拉 ┆       ┆ {"[name]": ┆ … ┆            ┆ 光环      ┆ 普通      ┆ 鬼剑士,黑 │
│           ┆ 光环[鬼剑  ┆       ┆ ["迅捷的奥 ┆   ┆            ┆           ┆           ┆ 暗武士    │
│           ┆ 士/黑暗武  ┆       ┆ 拉光环[鬼  ┆   ┆            ┆           ┆           ┆           │
│           ┆ 士]        ┆       ┆ 剑士/黑暗  ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ 武士]…     ┆   ┆            ┆           ┆           ┆           │
│ 107590010 ┆ 迅捷的奥拉 ┆       ┆ {"[name]": ┆ … ┆            ┆ 光环      ┆ 普通      ┆ 格斗家-男 │
│           ┆ 光环[格斗  ┆       ┆ ["迅捷的奥 ┆   ┆            ┆           ┆           ┆           │
│           ┆ 家(男)]    ┆       ┆ 拉光环[格  ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ 斗家(男)]" ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ ]…         ┆   ┆            ┆           ┆           ┆           │
│ 107590011 ┆ 迅捷的奥拉 ┆       ┆ {"[name]": ┆ … ┆            ┆ 光环      ┆ 普通      ┆ 魔法师-男 │
│           ┆ 光环[魔法  ┆       ┆ ["迅捷的奥 ┆   ┆            ┆           ┆           ┆           │
│           ┆ 师(男)]    ┆       ┆ 拉光环[魔  ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ 法师(男)]" ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ ]…         ┆   ┆            ┆           ┆           ┆           │
│ 107590012 ┆ 迅捷的奥拉 ┆       ┆ {"[name]": ┆ … ┆            ┆ 光环      ┆ 普通      ┆ 暗夜使者  │
│           ┆ 光环[暗夜  ┆       ┆ ["迅捷的奥 ┆   ┆            ┆           ┆           ┆           │
│           ┆ 使者]      ┆       ┆ 拉光环[暗  ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ 夜使者]"], ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ …          ┆   ┆            ┆           ┆           ┆           │
│ …         ┆ …          ┆ …     ┆ …          ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 609590009 ┆ 清澈蓝浪花 ┆       ┆ {"[name]": ┆ … ┆            ┆ 光环      ┆ 普通      ┆ 暗夜使者  │
│           ┆            ┆       ┆ ["清澈蓝浪 ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ 花"],      ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ "[usable…  ┆   ┆            ┆           ┆           ┆           │
│ 101590310 ┆ 希望之洗礼 ┆       ┆ {"[name]": ┆ … ┆            ┆ 光环      ┆ 普通      ┆ 全部职业  │
│           ┆            ┆       ┆ ["希望之洗 ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ 礼"],      ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ "[basic …  ┆   ┆            ┆           ┆           ┆           │
│ 412590201 ┆ 镜花水月   ┆       ┆ {"[name]": ┆ … ┆            ┆ 光环      ┆ 普通      ┆ 全部职业  │
│           ┆            ┆       ┆ ["镜花水月 ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ "],        ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ "[basic e… ┆   ┆            ┆           ┆           ┆           │
│ 401590035 ┆ 魔界大战终 ┆       ┆ {"[name]": ┆ … ┆            ┆ 光环      ┆ 普通      ┆ 全部职业  │
│           ┆ 结者       ┆       ┆ ["魔界大战 ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ 终结者"],  ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ "[basi…    ┆   ┆            ┆           ┆           ┆           │
│ 401590108 ┆ 黑色大地的 ┆       ┆ {"[name]": ┆ … ┆            ┆ 光环      ┆ 普通      ┆ 全部职业  │
│           ┆ 审判者     ┆       ┆ ["黑色大地 ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ 的审判者"] ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ , "[exp…   ┆   ┆            ┆           ┆           ┆           │
└───────────┴────────────┴───────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [121]:
df.filter((pl.col('equipment_type') == '[breast avatar]') & (pl.col('name') != ''))

shape: (2_784, 30)
┌───────────┬────────────┬───────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ id        ┆ name       ┆ name2 ┆ json       ┆ … ┆ armor_type ┆ display_e ┆ display_r ┆ display_u │
│ ---       ┆ ---        ┆ ---   ┆ ---        ┆   ┆ ---        ┆ quipment_ ┆ arity     ┆ sable_job │
│ i64       ┆ str        ┆ str   ┆ str        ┆   ┆ str        ┆ type      ┆ ---       ┆ ---       │
│           ┆            ┆       ┆            ┆   ┆            ┆ ---       ┆ str       ┆ str       │
│           ┆            ┆       ┆            ┆   ┆            ┆ str       ┆           ┆           │
╞═══════════╪════════════╪═══════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 103520132 ┆ 简约围巾[A ┆       ┆ {"[name]": ┆ … ┆            ┆ 胸部装扮  ┆ 普通      ┆ 格斗家-男 │
│           ┆ 型]        ┆       ┆ ["简约围巾 ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ [A型]"],   ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ "[nam…     ┆   ┆            ┆           ┆           ┆           │
│ 103520133 ┆ 简约围巾[B ┆       ┆ {"[name]": ┆ … ┆            ┆ 胸部装扮  ┆ 普通      ┆ 格斗家-男 │
│           ┆ 型]        ┆       ┆ ["简约围巾 ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ [B型]"],   ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ "[nam…     ┆   ┆            ┆           ┆           ┆           │
│ 103520134 ┆ 简约围巾[C ┆       ┆ {"[name]": ┆ … ┆            ┆ 胸部装扮  ┆ 普通      ┆ 格斗家-男 │
│           ┆ 型]        ┆       ┆ ["简约围巾 ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ [C型]"],   ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ "[nam…     ┆   ┆            ┆           ┆           ┆           │
│ 103520135 ┆ 简约围巾[D ┆       ┆ {"[name]": ┆ … ┆            ┆ 胸部装扮  ┆ 普通      ┆ 格斗家-男 │
│           ┆ 型]        ┆       ┆ ["简约围巾 ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ [D型]"],   ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ "[nam…     ┆   ┆            ┆           ┆           ┆           │
│ 103520136 ┆ 围巾[A型]  ┆       ┆ {"[name]": ┆ … ┆            ┆ 胸部装扮  ┆ 普通      ┆ 格斗家-男 │
│           ┆            ┆       ┆ ["围巾[A型 ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ ]"],       ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ "[name2…   ┆   ┆            ┆           ┆           ┆           │
│ …         ┆ …          ┆ …     ┆ …          ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 608520083 ┆ 海滩男孩青 ┆       ┆ {"[name]": ┆ … ┆            ┆ 胸部装扮  ┆ 普通      ┆ 圣职者    │
│           ┆ 铜项链     ┆       ┆ ["海滩男孩 ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ 青铜项链"] ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ , "[exp…   ┆   ┆            ┆           ┆           ┆           │
│ 609520082 ┆ 海滩罗曼史 ┆       ┆ {"[name]": ┆ … ┆            ┆ 胸部装扮  ┆ 普通      ┆ 暗夜使者  │
│           ┆ 爱心纹身   ┆       ┆ ["海滩罗曼 ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ 史爱心纹身 ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ "], "[ex…  ┆   ┆            ┆           ┆           ┆           │
│ 609520083 ┆ 海滩女孩爱 ┆       ┆ {"[name]": ┆ … ┆            ┆ 胸部装扮  ┆ 普通      ┆ 暗夜使者  │
│           ┆ 心纹身     ┆       ┆ ["海滩女孩 ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ 爱心纹身"] ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ , "[exp…   ┆   ┆            ┆           ┆           ┆           │
│ 607520069 ┆ 海滩罗曼史 ┆       ┆ {"[name]": ┆ … ┆            ┆ 胸部装扮  ┆ 普通      ┆ 魔法师-男 │
│           ┆ 狂野刺青   ┆       ┆ ["海滩罗曼 ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ 史狂野刺青 ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ "], "[ex…  ┆   ┆            ┆           ┆           ┆           │
│ 607520070 ┆ 海滩男孩狂 ┆       ┆ {"[name]": ┆ … ┆            ┆ 胸部装扮  ┆ 普通      ┆ 魔法师-男 │
│           ┆ 野刺青     ┆       ┆ ["海滩男孩 ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ 狂野刺青"] ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ , "[exp…   ┆   ┆            ┆           ┆           ┆           │
└───────────┴────────────┴───────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [122]:
df.filter((pl.col('equipment_type') == '[creature]') & (pl.col('name') != ''))

shape: (233, 30)
┌───────────┬───────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ id        ┆ name      ┆ name2    ┆ json      ┆ … ┆ armor_typ ┆ display_e ┆ display_r ┆ display_u │
│ ---       ┆ ---       ┆ ---      ┆ ---       ┆   ┆ e         ┆ quipment_ ┆ arity     ┆ sable_job │
│ i64       ┆ str       ┆ str      ┆ str       ┆   ┆ ---       ┆ type      ┆ ---       ┆ ---       │
│           ┆           ┆          ┆           ┆   ┆ str       ┆ ---       ┆ str       ┆ str       │
│           ┆           ┆          ┆           ┆   ┆           ┆ str       ┆           ┆           │
╞═══════════╪═══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 63000     ┆ 佛拉斯    ┆ Faras    ┆ {"[name]" ┆ … ┆           ┆ 宠物      ┆ 高级      ┆ 全部职业  │
│           ┆           ┆          ┆ : ["佛拉  ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ 斯"], "[n ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ ame2]":…  ┆   ┆           ┆           ┆           ┆           │
│ 63001     ┆ 佛尔卡斯  ┆ Pentabas ┆ {"[name]" ┆ … ┆           ┆ 宠物      ┆ 高级      ┆ 全部职业  │
│           ┆           ┆          ┆ : ["佛尔  ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ 卡斯"],   ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ "[name2]" ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ …         ┆   ┆           ┆           ┆           ┆           │
│ 63002     ┆ 菲尼克斯  ┆ Phoenix  ┆ {"[name]" ┆ … ┆           ┆ 宠物      ┆ 高级      ┆ 全部职业  │
│           ┆           ┆          ┆ : ["菲尼  ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ 克斯"],   ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ "[name2]" ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ …         ┆   ┆           ┆           ┆           ┆           │
│ 63003     ┆ 恰克斯    ┆ Charp    ┆ {"[name]" ┆ … ┆           ┆ 宠物      ┆ 高级      ┆ 全部职业  │
│           ┆           ┆          ┆ : ["恰克  ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ 斯"], "[n ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ ame2]":…  ┆   ┆           ┆           ┆           ┆           │
│ 63004     ┆ 哈帕斯    ┆ Halphas  ┆ {"[name]" ┆ … ┆           ┆ 宠物      ┆ 高级      ┆ 全部职业  │
│           ┆           ┆          ┆ : ["哈帕  ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ 斯"], "[n ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ ame2]":…  ┆   ┆           ┆           ┆           ┆           │
│ …         ┆ …         ┆ …        ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 2750000   ┆ 蓝喜鹊    ┆ bluebird ┆ {"[name]" ┆ … ┆           ┆ 宠物      ┆ 神器      ┆ 全部职业  │
│           ┆           ┆          ┆ : ["蓝喜  ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ 鹊"], "[n ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ ame2]":…  ┆   ┆           ┆           ┆           ┆           │
│ 400990109 ┆ 迷你皇女  ┆          ┆ {"[name]" ┆ … ┆           ┆ 宠物      ┆ 史诗      ┆ 全部职业  │
│           ┆ 艾丽婕    ┆          ┆ : ["迷你  ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ 皇女艾丽  ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ 婕"],     ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ "[expl…   ┆   ┆           ┆           ┆           ┆           │
│ 400990502 ┆ 迷你冲浪  ┆          ┆ {"[name]" ┆ … ┆           ┆ 宠物      ┆ 史诗      ┆ 全部职业  │
│           ┆ 赛丽亚    ┆          ┆ : ["迷你  ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ 冲浪赛丽  ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ 亚"],     ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ "[expl…   ┆   ┆           ┆           ┆           ┆           │
│ 400990078 ┆ 灵动小龙  ┆          ┆ {"[name]" ┆ … ┆           ┆ 宠物      ┆ 神器      ┆ 全部职业  │
│           ┆ 女        ┆          ┆ : ["灵动  ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ 小龙女"], ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ "[flavor… ┆   ┆           ┆           ┆           ┆           │
│ 400990077 ┆ 热辣小龙  ┆          ┆ {"[name]" ┆ … ┆           ┆ 宠物      ┆ 神器      ┆ 全部职业  │
│           ┆ 女        ┆          ┆ : ["热辣  ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ 小龙女"], ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ "[explai… ┆   ┆           ┆           ┆           ┆           │
└───────────┴───────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [123]:
df.filter((pl.col('equipment_type') == '[support]') & (pl.col('name') != ''))

shape: (967, 30)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id        ┆ name      ┆ name2     ┆ json      ┆ … ┆ armor_typ ┆ display_e ┆ display_r ┆ display_ │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ e         ┆ quipment_ ┆ arity     ┆ usable_j │
│ i64       ┆ str       ┆ str       ┆ str       ┆   ┆ ---       ┆ type      ┆ ---       ┆ ob       │
│           ┆           ┆           ┆           ┆   ┆ str       ┆ ---       ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆ str       ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 440000    ┆ 古老的丝  ┆ Old Silky ┆ {"[name]" ┆ … ┆           ┆ 辅助装备  ┆ 普通      ┆ 全部职业 │
│           ┆ 绒臂章    ┆ Yarn      ┆ : ["古老  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Armband   ┆ 的丝绒臂  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 章"],     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name…   ┆   ┆           ┆           ┆           ┆          │
│ 440001    ┆ 丝绒臂章  ┆ Silky     ┆ {"[name]" ┆ … ┆           ┆ 辅助装备  ┆ 高级      ┆ 全部职业 │
│           ┆           ┆ Yarn      ┆ : ["丝绒  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Armband   ┆ 臂章"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2]" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆          │
│ 440003    ┆ 虚祖王室  ┆ Sujue     ┆ {"[name]" ┆ … ┆           ┆ 辅助装备  ┆ 神器      ┆ 全部职业 │
│           ┆ 臂章      ┆ Royal     ┆ : ["虚祖  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Family    ┆ 王室臂章" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Armband   ┆ ],        ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2…  ┆   ┆           ┆           ┆           ┆          │
│ 440004    ┆ 布万加的  ┆ Bwanga's  ┆ {"[name]" ┆ … ┆           ┆ 辅助装备  ┆ 史诗      ┆ 全部职业 │
│           ┆ 族长臂章  ┆ Patriarch ┆ : ["布万  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Armband   ┆ 加的族长  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 臂章"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[nam…    ┆   ┆           ┆           ┆           ┆          │
│ 440016    ┆ 剑魂巴恩  ┆ Noble     ┆ {"[name]" ┆ … ┆           ┆ 辅助装备  ┆ 神器      ┆ 鬼剑士   │
│           ┆ 的手套    ┆ Glove of  ┆ : ["剑魂  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Bhan      ┆ 巴恩的手  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 套"],     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name…   ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 100341669 ┆ 时间旅行  ┆           ┆ {"[name]" ┆ … ┆           ┆ 辅助装备  ┆ 史诗      ┆ 全部职业 │
│           ┆ 者的随身  ┆           ┆ : ["时间  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 怀表      ┆           ┆ 旅行者的  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 随身怀表" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ], "[b…   ┆   ┆           ┆           ┆           ┆          │
│ 300340000 ┆ MLA-600   ┆           ┆ {"[name]" ┆ … ┆           ┆ 辅助装备  ┆ 神器      ┆ 全部职业 │
│           ┆ 机械臂章( ┆           ┆ :         ┆   ┆           ┆           ┆           ┆          │
│           ┆ 附加伤害) ┆           ┆ ["MLA-600 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 机械臂章( ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 附加伤害… ┆   ┆           ┆           ┆           ┆          │
│ 300340001 ┆ MLA-600   ┆           ┆ {"[name]" ┆ … ┆           ┆ 辅助装备  ┆ 神器      ┆ 全部职业 │
│           ┆ 机械臂章( ┆           ┆ :         ┆   ┆           ┆           ┆           ┆          │
│           ┆ 冷却时间) ┆           ┆ ["MLA-600 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 机械臂章( ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 冷却时间… ┆   ┆           ┆           ┆           ┆          │
│ 300340002 ┆ MLA-600   ┆           ┆ {"[name]" ┆ … ┆           ┆ 辅助装备  ┆ 神器      ┆ 全部职业 │
│           ┆ 机械臂章( ┆           ┆ :         ┆   ┆           ┆           ┆           ┆          │
│           ┆ 暴击伤害) ┆           ┆ ["MLA-600 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 机械臂章( ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 暴击伤害… ┆   ┆           ┆           ┆           ┆          │
│ 600340000 ┆ 觉醒勇士  ┆ awake     ┆ {"[name]" ┆ … ┆           ┆ 辅助装备  ┆ 稀有      ┆ 全部职业 │
│           ┆ 的辅助装  ┆ support   ┆ : ["觉醒  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 备        ┆           ┆ 勇士的辅  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 助装备"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[na…     ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [124]:
df.filter((pl.col('equipment_type') == '[weapon]') & (pl.col('name') != ''))

shape: (7_915, 30)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id        ┆ name      ┆ name2     ┆ json      ┆ … ┆ armor_typ ┆ display_e ┆ display_r ┆ display_ │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ e         ┆ quipment_ ┆ arity     ┆ usable_j │
│ i64       ┆ str       ┆ str       ┆ str       ┆   ┆ ---       ┆ type      ┆ ---       ┆ ob       │
│           ┆           ┆           ┆           ┆   ┆ str       ┆ ---       ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆ str       ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 29000     ┆ 普通手套  ┆ Default   ┆ {"[name]" ┆ … ┆           ┆ 手套      ┆ 普通      ┆ 格斗家,  │
│           ┆           ┆ Gloves    ┆ : ["普通  ┆   ┆           ┆           ┆           ┆ 格斗家-  │
│           ┆           ┆           ┆ 手套"],   ┆   ┆           ┆           ┆           ┆ 男       │
│           ┆           ┆           ┆ "[name2]" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆          │
│ 29016     ┆ (旧) 破旧 ┆ Outdated  ┆ {"[name]" ┆ … ┆           ┆ 手套      ┆ 普通      ┆ 格斗家,  │
│           ┆ 的蚕丝手  ┆ Hora      ┆ : ["(旧)  ┆   ┆           ┆           ┆           ┆ 格斗家-  │
│           ┆ 套        ┆           ┆ 破旧的蚕  ┆   ┆           ┆           ┆           ┆ 男       │
│           ┆           ┆           ┆ 丝手套"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[…       ┆   ┆           ┆           ┆           ┆          │
│ 29017     ┆ (旧)      ┆ Hora      ┆ {"[name]" ┆ … ┆           ┆ 手套      ┆ 高级      ┆ 格斗家,  │
│           ┆ 蚕丝手套  ┆           ┆ : ["(旧)  ┆   ┆           ┆           ┆           ┆ 格斗家-  │
│           ┆           ┆           ┆ 蚕丝手套" ┆   ┆           ┆           ┆           ┆ 男       │
│           ┆           ┆           ┆ ], "[nam… ┆   ┆           ┆           ┆           ┆          │
│ 29018     ┆ (旧) 十夫 ┆ Knuckle   ┆ {"[name]" ┆ … ┆           ┆ 手套      ┆ 稀有      ┆ 格斗家,  │
│           ┆ 长的手套  ┆ of Chief  ┆ : ["(旧)  ┆   ┆           ┆           ┆           ┆ 格斗家-  │
│           ┆           ┆ Sign      ┆ 十夫长的  ┆   ┆           ┆           ┆           ┆ 男       │
│           ┆           ┆           ┆ 手套"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[n…      ┆   ┆           ┆           ┆           ┆          │
│ 29019     ┆ (旧) 坚固 ┆ Strong    ┆ {"[name]" ┆ … ┆           ┆ 手套      ┆ 高级      ┆ 格斗家,  │
│           ┆ 的蚕丝手  ┆ Hora      ┆ : ["(旧)  ┆   ┆           ┆           ┆           ┆ 格斗家-  │
│           ┆ 套        ┆           ┆ 坚固的蚕  ┆   ┆           ┆           ┆           ┆ 男       │
│           ┆           ┆           ┆ 丝手套"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[…       ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 609020004 ┆ 传承 :    ┆ Legacy :  ┆ {"[name]" ┆ … ┆           ┆ 手杖      ┆ 传承      ┆ 暗夜使者 │
│           ┆ 复魂天使  ┆ Mummy     ┆ : ["传承  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 的木乃伊  ┆ Wand of   ┆ : 复魂天  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 手杖      ┆ Lauvi     ┆ 使的木乃  ┆   ┆           ┆           ┆           ┆          │
│           ┆ [活动]    ┆           ┆ 伊手杖 [… ┆   ┆           ┆           ┆           ┆          │
│ 609020005 ┆ 传承 :    ┆ Legacy :  ┆ {"[name]" ┆ … ┆           ┆ 手杖      ┆ 传承      ┆ 暗夜使者 │
│           ┆ 暗影精灵  ┆ Logna     ┆ : ["传承  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 的罗格纳  ┆ Demos of  ┆ : 暗影精  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 手杖      ┆ Reiden    ┆ 灵的罗格  ┆   ┆           ┆           ┆           ┆          │
│           ┆ [活动]    ┆           ┆ 纳手杖 [… ┆   ┆           ┆           ┆           ┆          │
│ 609020006 ┆ 传承 :    ┆ Legacy :  ┆ {"[name]" ┆ … ┆           ┆ 手杖      ┆ 传承      ┆ 暗夜使者 │
│           ┆ 毒狱天使  ┆ Airamos   ┆ : ["传承  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 的阿摩司  ┆ of Oreas  ┆ : 毒狱天  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 手杖      ┆           ┆ 使的阿摩  ┆   ┆           ┆           ┆           ┆          │
│           ┆ [活动]    ┆           ┆ 司手杖 [… ┆   ┆           ┆           ┆           ┆          │
│ 609020007 ┆ 传承 :    ┆ Legacy :  ┆ {"[name]" ┆ … ┆           ┆ 手杖      ┆ 传承      ┆ 暗夜使者 │
│           ┆ 炎魔精灵  ┆ Gud Rota  ┆ : ["传承  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 的祭祀手  ┆ of Salim  ┆ : 炎魔精  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 杖 [活动] ┆           ┆ 灵的祭祀  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 手杖 [活… ┆   ┆           ┆           ┆           ┆          │
│ 609020008 ┆ 茁壮冒险  ┆ taiwan    ┆ {"[name]" ┆ … ┆           ┆ 手杖      ┆ 稀有      ┆ 暗夜使者 │
│           ┆ 家的成长  ┆ newbie    ┆ : ["茁壮  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 权杖      ┆ support   ┆ 冒险家的  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 2nd       ┆ 成长权杖" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ], "[n…   ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [125]:
df.filter(pl.col('id') == 11338)

shape: (1, 30)
┌───────┬────────────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ id    ┆ name       ┆ name2      ┆ json       ┆ … ┆ armor_typ ┆ display_e ┆ display_r ┆ display_u │
│ ---   ┆ ---        ┆ ---        ┆ ---        ┆   ┆ e         ┆ quipment_ ┆ arity     ┆ sable_job │
│ i64   ┆ str        ┆ str        ┆ str        ┆   ┆ ---       ┆ type      ┆ ---       ┆ ---       │
│       ┆            ┆            ┆            ┆   ┆ str       ┆ ---       ┆ str       ┆ str       │
│       ┆            ┆            ┆            ┆   ┆           ┆ str       ┆           ┆           │
╞═══════╪════════════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 11338 ┆ 古老的鳞岩 ┆ Low-Cost   ┆ {"[name]": ┆ … ┆ ha        ┆ 上衣      ┆ 稀有      ┆ 全部职业  │
│       ┆ 胸甲       ┆ Carbollite ┆ ["古老的鳞 ┆   ┆           ┆           ┆           ┆           │
│       ┆            ┆ Breastplat ┆ 岩胸甲"],  ┆   ┆           ┆           ┆           ┆           │
│       ┆            ┆ …          ┆ "[name…    ┆   ┆           ┆           ┆           ┆           │
└───────┴────────────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [126]:
df.select(pl.col('item_group_name')).unique()

shape: (59, 1)
┌─────────────────┐
│ item_group_name │
│ ---             │
│ str             │
╞═════════════════╡
│ staff           │
│ totem           │
│ katana          │
│ support         │
│ claw            │
│ …               │
│ lt coat         │
│ ring            │
│ lt shoes        │
│ bglove          │
│ ssword          │
└─────────────────┘

In [127]:
df.select(pl.col('equipment_type')).unique()

shape: (27, 1)
┌─────────────────┐
│ equipment_type  │
│ ---             │
│ str             │
╞═════════════════╡
│ [skin avatar]   │
│ [face avatar]   │
│ [weapon]        │
│ [pants]         │
│ [amulet]        │
│ …               │
│ [artifact blue] │
│ [creature]      │
│ [coat]          │
│ [shoes]         │
│ [waist]         │
└─────────────────┘

In [128]:
df.filter((pl.col('equipment_type') == '[title name]') & (pl.col('name') != ''))

shape: (762, 30)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id        ┆ name      ┆ name2     ┆ json      ┆ … ┆ armor_typ ┆ display_e ┆ display_r ┆ display_ │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ e         ┆ quipment_ ┆ arity     ┆ usable_j │
│ i64       ┆ str       ┆ str       ┆ str       ┆   ┆ ---       ┆ type      ┆ ---       ┆ ob       │
│           ┆           ┆           ┆           ┆   ┆ str       ┆ ---       ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆ str       ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 26001     ┆ (旧) 卡妮 ┆ Kanna's   ┆ {"[name]" ┆ … ┆           ┆ 称号      ┆ 稀有      ┆ 全部职业 │
│           ┆ 娜的希望☆ ┆ slave     ┆ : ["(旧)  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 卡妮娜的  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 希望☆"],  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[…       ┆   ┆           ┆           ┆           ┆          │
│ 26002     ┆ 温暖的心  ┆ Warmmind  ┆ {"[name]" ┆ … ┆           ┆ 称号      ┆ 稀有      ┆ 全部职业 │
│           ┆           ┆           ┆ : ["温暖  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 的心"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2]" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆          │
│ 26003     ┆ 皇女的护  ┆ Skadyguar ┆ {"[name]" ┆ … ┆           ┆ 称号      ┆ 稀有      ┆ 全部职业 │
│           ┆ 卫        ┆ d         ┆ : ["皇女  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 的护卫"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2]… ┆   ┆           ┆           ┆           ┆          │
│ 26004     ┆ 帝国见习  ┆ Empireapp ┆ {"[name]" ┆ … ┆           ┆ 称号      ┆ 稀有      ┆ 全部职业 │
│           ┆ 骑士      ┆ rentice   ┆ : ["帝国  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 见习骑士" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ],        ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2…  ┆   ┆           ┆           ┆           ┆          │
│ 26005     ┆ 罗马宽剑  ┆ Gladios   ┆ {"[name]" ┆ … ┆           ┆ 称号      ┆ 稀有      ┆ 全部职业 │
│           ┆           ┆           ┆ : ["罗马  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 宽剑"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2]" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 100331258 ┆ 蓝色海浪  ┆           ┆ {"[name]" ┆ … ┆           ┆ 称号      ┆ 稀有      ┆ 全部职业 │
│           ┆           ┆           ┆ : ["蓝色  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 海浪"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[explain ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆          │
│ 100331259 ┆ 红色夕阳- ┆           ┆ {"[name]" ┆ … ┆           ┆ 称号      ┆ 稀有      ┆ 全部职业 │
│           ┆ 白金      ┆           ┆ : ["红色  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 夕阳-白金 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "],       ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[grad…   ┆   ┆           ┆           ┆           ┆          │
│ 100331260 ┆ 型男辣妹- ┆           ┆ {"[name]" ┆ … ┆           ┆ 称号      ┆ 稀有      ┆ 全部职业 │
│           ┆ 白金      ┆           ┆ : ["型男  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 辣妹-白金 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "],       ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[grad…   ┆   ┆           ┆           ┆           ┆          │
│ 100331261 ┆ 蓝色海浪- ┆           ┆ {"[name]" ┆ … ┆           ┆ 称号      ┆ 稀有      ┆ 全部职业 │
│           ┆ 白金      ┆           ┆ : ["蓝色  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 海浪-白金 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "],       ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[expl…   ┆   ┆           ┆           ┆           ┆          │
│ 20251005  ┆ 赛丽亚的  ┆ [Seria]   ┆ {"[name]" ┆ … ┆           ┆ 称号      ┆ 史诗      ┆ 全部职业 │
│           ┆ 祝福      ┆           ┆ : ["赛丽  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 亚的祝福" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ],        ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2…  ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [129]:
df.filter(pl.col('name') == '守护腰带')

shape: (1, 30)
┌───────┬──────────┬────────────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ id    ┆ name     ┆ name2      ┆ json       ┆ … ┆ armor_type ┆ display_eq ┆ display_r ┆ display_u │
│ ---   ┆ ---      ┆ ---        ┆ ---        ┆   ┆ ---        ┆ uipment_ty ┆ arity     ┆ sable_job │
│ i64   ┆ str      ┆ str        ┆ str        ┆   ┆ str        ┆ pe         ┆ ---       ┆ ---       │
│       ┆          ┆            ┆            ┆   ┆            ┆ ---        ┆ str       ┆ str       │
│       ┆          ┆            ┆            ┆   ┆            ┆ str        ┆           ┆           │
╞═══════╪══════════╪════════════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 17242 ┆ 守护腰带 ┆ Protection ┆ {"[name]": ┆ … ┆ ha         ┆ 腰带       ┆ 稀有      ┆ 全部职业  │
│       ┆          ┆ Belt       ┆ ["守护腰带 ┆   ┆            ┆            ┆           ┆           │
│       ┆          ┆            ┆ "],        ┆   ┆            ┆            ┆           ┆           │
│       ┆          ┆            ┆ "[name2]"… ┆   ┆            ┆            ┆           ┆           │
└───────┴──────────┴────────────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

In [130]:
df.filter(pl.col('display_rarity') == '史诗')

shape: (1_338, 30)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id        ┆ name      ┆ name2     ┆ json      ┆ … ┆ armor_typ ┆ display_e ┆ display_r ┆ display_ │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ e         ┆ quipment_ ┆ arity     ┆ usable_j │
│ i64       ┆ str       ┆ str       ┆ str       ┆   ┆ ---       ┆ type      ┆ ---       ┆ ob       │
│           ┆           ┆           ┆           ┆   ┆ str       ┆ ---       ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆ str       ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 10114     ┆ (旧) 银月 ┆ Spangle   ┆ {"[name]" ┆ … ┆ cl        ┆ 上衣      ┆ 史诗      ┆ 全部职业 │
│           ┆ 少女T恤衫 ┆ Girl      ┆ : ["(旧)  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ T-Shirts  ┆ 银月少女T ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 恤衫"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[…       ┆   ┆           ┆           ┆           ┆          │
│ 10115     ┆ (旧) 天翎 ┆ Araclotho ┆ {"[name]" ┆ … ┆ cl        ┆ 上衣      ┆ 史诗      ┆ 全部职业 │
│           ┆ 逐月长袍  ┆ 's Silk   ┆ : ["(旧)  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ shirts    ┆ 天翎逐月  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 长袍"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[n…      ┆   ┆           ┆           ┆           ┆          │
│ 10116     ┆ (旧) 希曼 ┆ Himan     ┆ {"[name]" ┆ … ┆ cl        ┆ 上衣      ┆ 史诗      ┆ 全部职业 │
│           ┆ 的影舞衬  ┆ Stella's  ┆ : ["(旧)  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 衫        ┆ Rangerie  ┆ 希曼的影  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Top       ┆ 舞衬衫"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[…       ┆   ┆           ┆           ┆           ┆          │
│ 10117     ┆ (旧) 幽灵 ┆ Floating  ┆ {"[name]" ┆ … ┆ cl        ┆ 上衣      ┆ 史诗      ┆ 全部职业 │
│           ┆ 穿云长袍  ┆ Ghosts    ┆ : ["(旧)  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 幽灵穿云  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 长袍"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[n…      ┆   ┆           ┆           ┆           ┆          │
│ 10493     ┆ (旧) 青龙 ┆ DragonHid ┆ {"[name]" ┆ … ┆ lt        ┆ 上衣      ┆ 史诗      ┆ 全部职业 │
│           ┆ 啸月胸甲  ┆ e Coat    ┆ : ["(旧)  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 青龙啸月  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 胸甲"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[n…      ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 400350048 ┆ 暗黑克雷  ┆           ┆ {"[name]" ┆ … ┆           ┆ 魔法石    ┆ 史诗      ┆ 全部职业 │
│           ┆ 泽的龟甲  ┆           ┆ : ["暗黑  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 克雷泽的  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 龟甲"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[bas…    ┆   ┆           ┆           ┆           ┆          │
│ 400350049 ┆ 彩虹克雷  ┆           ┆ {"[name]" ┆ … ┆           ┆ 魔法石    ┆ 史诗      ┆ 全部职业 │
│           ┆ 泽的龟甲  ┆           ┆ : ["彩虹  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 克雷泽的  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 龟甲"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[bas…    ┆   ┆           ┆           ┆           ┆          │
│ 20251005  ┆ 赛丽亚的  ┆ [Seria]   ┆ {"[name]" ┆ … ┆           ┆ 称号      ┆ 史诗      ┆ 全部职业 │
│           ┆ 祝福      ┆           ┆ : ["赛丽  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 亚的祝福" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ],        ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2…  ┆   ┆           ┆           ┆           ┆          │
│ 400990109 ┆ 迷你皇女  ┆           ┆ {"[name]" ┆ … ┆           ┆ 宠物      ┆ 史诗      ┆ 全部职业 │
│           ┆ 艾丽婕    ┆           ┆ : ["迷你  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 皇女艾丽  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 婕"],     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[expl…   ┆   ┆           ┆           ┆           ┆          │
│ 400990502 ┆ 迷你冲浪  ┆           ┆ {"[name]" ┆ … ┆           ┆ 宠物      ┆ 史诗      ┆ 全部职业 │
│           ┆ 赛丽亚    ┆           ┆ : ["迷你  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 冲浪赛丽  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 亚"],     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[expl…   ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [131]:
df.filter(pl.col('all_elemental_attack') != 0).sort(
    pl.col('all_elemental_attack'), descending=True
)

shape: (319, 30)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id        ┆ name      ┆ name2     ┆ json      ┆ … ┆ armor_typ ┆ display_e ┆ display_r ┆ display_ │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ e         ┆ quipment_ ┆ arity     ┆ usable_j │
│ i64       ┆ str       ┆ str       ┆ str       ┆   ┆ ---       ┆ type      ┆ ---       ┆ ob       │
│           ┆           ┆           ┆           ┆   ┆ str       ┆ ---       ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆ str       ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 100350017 ┆ 高级精灵  ┆           ┆ {"[name]" ┆ … ┆           ┆ 魔法石    ┆ 史诗      ┆ 全部职业 │
│           ┆ 的精炼宝  ┆           ┆ : ["高级  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 石        ┆           ┆ 精灵的精  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 炼宝石"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[na…     ┆   ┆           ┆           ┆           ┆          │
│ 108010087 ┆ 神兽之护  ┆           ┆ {"[name]" ┆ … ┆           ┆ 念珠      ┆ 史诗      ┆ 圣职者   │
│           ┆           ┆           ┆ : ["神兽  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 之护"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[basic   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ e…        ┆   ┆           ┆           ┆           ┆          │
│ 450125    ┆ 融合之高  ┆ Tear of   ┆ {"[name]" ┆ … ┆           ┆ 魔法石    ┆ 史诗      ┆ 全部职业 │
│           ┆ 级精灵的  ┆ Flame     ┆ : ["融合  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 眼泪      ┆ Hulk      ┆ 之高级精  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 灵的眼泪" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ], "[n…   ┆   ┆           ┆           ┆           ┆          │
│ 400350049 ┆ 彩虹克雷  ┆           ┆ {"[name]" ┆ … ┆           ┆ 魔法石    ┆ 史诗      ┆ 全部职业 │
│           ┆ 泽的龟甲  ┆           ┆ : ["彩虹  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 克雷泽的  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 龟甲"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[bas…    ┆   ┆           ┆           ┆           ┆          │
│ 100350012 ┆ 中级精灵  ┆           ┆ {"[name]" ┆ … ┆           ┆ 魔法石    ┆ 神器      ┆ 全部职业 │
│           ┆ 的精炼宝  ┆           ┆ : ["中级  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 石        ┆           ┆ 精灵的精  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 炼宝石"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[na…     ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 601590057 ┆ 七彩泡泡  ┆           ┆ {"[name]" ┆ … ┆           ┆ 光环      ┆ 普通      ┆ 全部职业 │
│           ┆ 光环      ┆           ┆ : ["七彩  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 泡泡光环" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ],        ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[flavo…  ┆   ┆           ┆           ┆           ┆          │
│ 100330789 ┆ 昨日之恩  ┆           ┆ {"[name]" ┆ … ┆           ┆ 称号      ┆ 稀有      ┆ 全部职业 │
│           ┆ 赐 - 新芽 ┆           ┆ : ["昨日  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 之恩赐 -  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 新芽"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[e…      ┆   ┆           ┆           ┆           ┆          │
│ 100300090 ┆ 佩伦琐尔  ┆           ┆ {"[name]" ┆ … ┆           ┆ 项链      ┆ 领主神器  ┆ 全部职业 │
│           ┆ 项链      ┆           ┆ : ["佩伦  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 琐尔项链" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ],        ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[basic…  ┆   ┆           ┆           ┆           ┆          │
│ 63084     ┆ 炎息红龙  ┆ Flame Red ┆ {"[name]" ┆ … ┆           ┆ 宠物      ┆ 稀有      ┆ 全部职业 │
│           ┆           ┆ Dragon    ┆ : ["炎息  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 红龙"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2]" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆          │
│ 63086     ┆ 冰息蓝龙  ┆ Cold Blue ┆ {"[name]" ┆ … ┆           ┆ 宠物      ┆ 稀有      ┆ 全部职业 │
│           ┆           ┆ Dragon    ┆ : ["冰息  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 蓝龙"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2]" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [132]:
df.filter(pl.col('equipment_type') == '[weapon]').select(
    pl.col('item_group_name')
).unique()

shape: (28, 1)
┌─────────────────┐
│ item_group_name │
│ ---             │
│ str             │
╞═════════════════╡
│ beamswd         │
│ twinswd         │
│ wand            │
│ rod             │
│ broom           │
│ …               │
│ bglove          │
│ revolver        │
│ knuckle         │
│ hcannon         │
│ claw            │
└─────────────────┘

In [133]:
df.filter(pl.col('id').is_in(list(range(2747697, 2747702))))

shape: (5, 30)
┌─────────┬────────────┬───────┬────────────┬───┬────────────┬────────────┬────────────┬───────────┐
│ id      ┆ name       ┆ name2 ┆ json       ┆ … ┆ armor_type ┆ display_eq ┆ display_ra ┆ display_u │
│ ---     ┆ ---        ┆ ---   ┆ ---        ┆   ┆ ---        ┆ uipment_ty ┆ rity       ┆ sable_job │
│ i64     ┆ str        ┆ str   ┆ str        ┆   ┆ str        ┆ pe         ┆ ---        ┆ ---       │
│         ┆            ┆       ┆            ┆   ┆            ┆ ---        ┆ str        ┆ str       │
│         ┆            ┆       ┆            ┆   ┆            ┆ str        ┆            ┆           │
╞═════════╪════════════╪═══════╪════════════╪═══╪════════════╪════════════╪════════════╪═══════════╡
│ 2747697 ┆ 骑士王的守 ┆       ┆ {"[name]": ┆ … ┆            ┆ 称号       ┆ 神器       ┆ 全部职业  │
│         ┆ 护         ┆       ┆ ["骑士王的 ┆   ┆            ┆            ┆            ┆           │
│         ┆            ┆       ┆ 守护"],    ┆   ┆            ┆            ┆            ┆           │
│         ┆            ┆       ┆ "[expla…   ┆   ┆            ┆            ┆            ┆           │
│ 2747698 ┆ 征服王的友 ┆       ┆ {"[name]": ┆ … ┆            ┆ 称号       ┆ 神器       ┆ 全部职业  │
│         ┆ 谊         ┆       ┆ ["征服王的 ┆   ┆            ┆            ┆            ┆           │
│         ┆            ┆       ┆ 友谊"],    ┆   ┆            ┆            ┆            ┆           │
│         ┆            ┆       ┆ "[expla…   ┆   ┆            ┆            ┆            ┆           │
│ 2747699 ┆ 英雄王的宝 ┆       ┆ {"[name]": ┆ … ┆            ┆ 称号       ┆ 神器       ┆ 全部职业  │
│         ┆ 库         ┆       ┆ ["英雄王的 ┆   ┆            ┆            ┆            ┆           │
│         ┆            ┆       ┆ 宝库"],    ┆   ┆            ┆            ┆            ┆           │
│         ┆            ┆       ┆ "[expla…   ┆   ┆            ┆            ┆            ┆           │
│ 2747700 ┆ 骑士的愿望 ┆       ┆ {"[name]": ┆ … ┆            ┆ 称号       ┆ 稀有       ┆ 全部职业  │
│         ┆            ┆       ┆ ["骑士的愿 ┆   ┆            ┆            ┆            ┆           │
│         ┆            ┆       ┆ 望"],      ┆   ┆            ┆            ┆            ┆           │
│         ┆            ┆       ┆ "[explai…  ┆   ┆            ┆            ┆            ┆           │
│ 2747701 ┆ 狂战士的愤 ┆       ┆ {"[name]": ┆ … ┆            ┆ 称号       ┆ 稀有       ┆ 全部职业  │
│         ┆ 怒         ┆       ┆ ["狂战士的 ┆   ┆            ┆            ┆            ┆           │
│         ┆            ┆       ┆ 愤怒"],    ┆   ┆            ┆            ┆            ┆           │
│         ┆            ┆       ┆ "[expla…   ┆   ┆            ┆            ┆            ┆           │
└─────────┴────────────┴───────┴────────────┴───┴────────────┴────────────┴────────────┴───────────┘

In [134]:
df.filter(pl.col('set_name') != '').select(pl.col('set_name'), pl.col('set_item')).sort(
    pl.col('set_name'), descending=True
)

shape: (1_107, 2)
┌─────────────────────────────┬─────────────────────────┐
│ set_name                    ┆ set_item                │
│ ---                         ┆ ---                     │
│ str                         ┆ list[i64]               │
╞═════════════════════════════╪═════════════════════════╡
│ 龙鸣重甲  套装              ┆ [11237, 13237, … 19234] │
│ 龙鸣重甲  套装              ┆ [11259, 13259, … 17256] │
│ 龙脊轻甲  套装              ┆ [10874, 12874, … 16873] │
│ 黑龙汲星轻甲  套装          ┆ [10875, 12875, … 16874] │
│ 黑豹突击者轻甲  套装        ┆ [10934, 12928, … 18926] │
│ …                           ┆ …                       │
│ 2010年夏日  套装 1 (神枪手) ┆ [47201, 47619, … 50220] │
│ 2010年夏日  套装 1 (格斗家) ┆ [43196, 43624, … 46220] │
│ 2010年夏日  套装 1 (圣职者) ┆ [55135, 55514, … 58220] │
│ (旧) 窒息的悲鸣首饰         ┆ [20167, 22160, 24175]   │
│ (旧) 泰拉石首饰             ┆ [20166, 22159, 24174]   │
└─────────────────────────────┴─────────────────────────┘

In [135]:
df.select('*').sort(pl.col('cast_speed'), descending=True)

shape: (63_788, 30)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id        ┆ name      ┆ name2     ┆ json      ┆ … ┆ armor_typ ┆ display_e ┆ display_r ┆ display_ │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ e         ┆ quipment_ ┆ arity     ┆ usable_j │
│ i64       ┆ str       ┆ str       ┆ str       ┆   ┆ ---       ┆ type      ┆ ---       ┆ ob       │
│           ┆           ┆           ┆           ┆   ┆ str       ┆ ---       ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆ str       ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 22183     ┆ 简易白瓷  ┆ Upgrade   ┆ {"[name]" ┆ … ┆           ┆ 手镯      ┆ 普通      ┆ 全部职业 │
│           ┆ 手镯      ┆ Ceramics  ┆ : ["简易  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Bracelet  ┆ 白瓷手镯" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ],        ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2…  ┆   ┆           ┆           ┆           ┆          │
│ 24213     ┆ 简易青铜  ┆ Upgrade   ┆ {"[name]" ┆ … ┆           ┆ 戒指      ┆ 普通      ┆ 全部职业 │
│           ┆ 戒指      ┆ Bronze    ┆ : ["简易  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Ring      ┆ 青铜戒指" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ],        ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2…  ┆   ┆           ┆           ┆           ┆          │
│ 101020259 ┆ 御魂 -    ┆           ┆ {"[name]" ┆ … ┆           ┆ 太刀      ┆ 史诗      ┆ 鬼剑士,  │
│           ┆ 七支刀    ┆           ┆ : ["御魂  ┆   ┆           ┆           ┆           ┆ 黑暗武士 │
│           ┆           ┆           ┆ -         ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 七支刀"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[bas…    ┆   ┆           ┆           ┆           ┆          │
│ 100150123 ┆ 锦绣丹华  ┆           ┆ {"[name]" ┆ … ┆ cl        ┆ 头肩      ┆ 史诗      ┆ 全部职业 │
│           ┆ 护肩      ┆           ┆ : ["锦绣  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 丹华护肩" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ],        ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[basic…  ┆   ┆           ┆           ┆           ┆          │
│ 106010125 ┆ 精灵王之  ┆           ┆ {"[name]" ┆ … ┆           ┆ 魔杖      ┆ 史诗      ┆ 魔法师,  │
│           ┆ 庇护      ┆           ┆ : ["精灵  ┆   ┆           ┆           ┆           ┆ 魔法师-  │
│           ┆           ┆           ┆ 王之庇护" ┆   ┆           ┆           ┆           ┆ 男,缔造  │
│           ┆           ┆           ┆ ],        ┆   ┆           ┆           ┆           ┆ 者       │
│           ┆           ┆           ┆ "[basic…  ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 109010019 ┆ 赖的科特  ┆           ┆ {"[name]" ┆ … ┆           ┆ 双剑      ┆ 稀有      ┆ 暗夜使者 │
│           ┆ 尔(傀儡)  ┆           ┆ : ["赖的  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 科特尔(傀 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 儡)"],    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[na…     ┆   ┆           ┆           ┆           ┆          │
│ 102010088 ┆ 科尔基斯( ┆           ┆ {"[name]" ┆ … ┆           ┆ 臂铠      ┆ 稀有      ┆ 格斗家,  │
│           ┆ 傀儡)     ┆           ┆ : ["科尔  ┆   ┆           ┆           ┆           ┆ 格斗家-  │
│           ┆           ┆           ┆ 基斯(傀儡 ┆   ┆           ┆           ┆           ┆ 男       │
│           ┆           ┆           ┆ )"],      ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[nam…    ┆   ┆           ┆           ┆           ┆          │
│ 32030     ┆ 机械战神  ┆ Action    ┆ {"[name]" ┆ … ┆           ┆ 步枪      ┆ 史诗      ┆ 神枪手,  │
│           ┆ 的战斗步  ┆ Reform    ┆ : ["机械  ┆   ┆           ┆           ┆           ┆ 神枪手-  │
│           ┆ 枪        ┆ Musket    ┆ 战神的战  ┆   ┆           ┆           ┆           ┆ 女       │
│           ┆           ┆           ┆ 斗步枪"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[na…     ┆   ┆           ┆           ┆           ┆          │
│ 106030020 ┆ 干特(傀儡 ┆           ┆ {"[name]" ┆ … ┆           ┆ 法杖      ┆ 稀有      ┆ 魔法师,  │
│           ┆ )         ┆           ┆ : ["干特( ┆   ┆           ┆           ┆           ┆ 魔法师-  │
│           ┆           ┆           ┆ 傀儡)"],  ┆   ┆           ┆           ┆           ┆ 男,缔造  │
│           ┆           ┆           ┆ "[name2…  ┆   ┆           ┆           ┆           ┆ 者       │
│ 109020019 ┆ 罗萨罗兹( ┆           ┆ {"[name]" ┆ … ┆           ┆ 手杖      ┆ 稀有      ┆ 暗夜使者 │
│           ┆ 傀儡)     ┆           ┆ : ["罗萨  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 罗兹(傀儡 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ )"],      ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[nam…    ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [136]:
df.filter((pl.col('sub_type') == 0) & (pl.col('equipment_type') == '[creature]'))

shape: (130, 30)
┌───────────┬───────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ id        ┆ name      ┆ name2    ┆ json      ┆ … ┆ armor_typ ┆ display_e ┆ display_r ┆ display_u │
│ ---       ┆ ---       ┆ ---      ┆ ---       ┆   ┆ e         ┆ quipment_ ┆ arity     ┆ sable_job │
│ i64       ┆ str       ┆ str      ┆ str       ┆   ┆ ---       ┆ type      ┆ ---       ┆ ---       │
│           ┆           ┆          ┆           ┆   ┆ str       ┆ ---       ┆ str       ┆ str       │
│           ┆           ┆          ┆           ┆   ┆           ┆ str       ┆           ┆           │
╞═══════════╪═══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 63000     ┆ 佛拉斯    ┆ Faras    ┆ {"[name]" ┆ … ┆           ┆ 宠物      ┆ 高级      ┆ 全部职业  │
│           ┆           ┆          ┆ : ["佛拉  ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ 斯"], "[n ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ ame2]":…  ┆   ┆           ┆           ┆           ┆           │
│ 63001     ┆ 佛尔卡斯  ┆ Pentabas ┆ {"[name]" ┆ … ┆           ┆ 宠物      ┆ 高级      ┆ 全部职业  │
│           ┆           ┆          ┆ : ["佛尔  ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ 卡斯"],   ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ "[name2]" ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ …         ┆   ┆           ┆           ┆           ┆           │
│ 63002     ┆ 菲尼克斯  ┆ Phoenix  ┆ {"[name]" ┆ … ┆           ┆ 宠物      ┆ 高级      ┆ 全部职业  │
│           ┆           ┆          ┆ : ["菲尼  ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ 克斯"],   ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ "[name2]" ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ …         ┆   ┆           ┆           ┆           ┆           │
│ 63003     ┆ 恰克斯    ┆ Charp    ┆ {"[name]" ┆ … ┆           ┆ 宠物      ┆ 高级      ┆ 全部职业  │
│           ┆           ┆          ┆ : ["恰克  ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ 斯"], "[n ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ ame2]":…  ┆   ┆           ┆           ┆           ┆           │
│ 63004     ┆ 哈帕斯    ┆ Halphas  ┆ {"[name]" ┆ … ┆           ┆ 宠物      ┆ 高级      ┆ 全部职业  │
│           ┆           ┆          ┆ : ["哈帕  ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ 斯"], "[n ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ ame2]":…  ┆   ┆           ┆           ┆           ┆           │
│ …         ┆ …         ┆ …        ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 2750000   ┆ 蓝喜鹊    ┆ bluebird ┆ {"[name]" ┆ … ┆           ┆ 宠物      ┆ 神器      ┆ 全部职业  │
│           ┆           ┆          ┆ : ["蓝喜  ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ 鹊"], "[n ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ ame2]":…  ┆   ┆           ┆           ┆           ┆           │
│ 400990109 ┆ 迷你皇女  ┆          ┆ {"[name]" ┆ … ┆           ┆ 宠物      ┆ 史诗      ┆ 全部职业  │
│           ┆ 艾丽婕    ┆          ┆ : ["迷你  ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ 皇女艾丽  ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ 婕"],     ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ "[expl…   ┆   ┆           ┆           ┆           ┆           │
│ 400990502 ┆ 迷你冲浪  ┆          ┆ {"[name]" ┆ … ┆           ┆ 宠物      ┆ 史诗      ┆ 全部职业  │
│           ┆ 赛丽亚    ┆          ┆ : ["迷你  ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ 冲浪赛丽  ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ 亚"],     ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ "[expl…   ┆   ┆           ┆           ┆           ┆           │
│ 400990078 ┆ 灵动小龙  ┆          ┆ {"[name]" ┆ … ┆           ┆ 宠物      ┆ 神器      ┆ 全部职业  │
│           ┆ 女        ┆          ┆ : ["灵动  ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ 小龙女"], ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ "[flavor… ┆   ┆           ┆           ┆           ┆           │
│ 400990077 ┆ 热辣小龙  ┆          ┆ {"[name]" ┆ … ┆           ┆ 宠物      ┆ 神器      ┆ 全部职业  │
│           ┆ 女        ┆          ┆ : ["热辣  ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ 小龙女"], ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ "[explai… ┆   ┆           ┆           ┆           ┆           │
└───────────┴───────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [137]:
df.select('usable_job', 'display_usable_job')

shape: (63_788, 2)
┌─────────────────────────────────┬────────────────────┐
│ usable_job                      ┆ display_usable_job │
│ ---                             ┆ ---                │
│ list[str]                       ┆ str                │
╞═════════════════════════════════╪════════════════════╡
│ ["[all]"]                       ┆ 全部职业           │
│ ["[all]"]                       ┆ 全部职业           │
│ ["[all]"]                       ┆ 全部职业           │
│ ["[all]"]                       ┆ 全部职业           │
│ ["[all]"]                       ┆ 全部职业           │
│ …                               ┆ …                  │
│ ["[swordman]", "[demonic sword… ┆ 鬼剑士,黑暗武士    │
│ ["[all]"]                       ┆ 全部职业           │
│ ["[all]"]                       ┆ 全部职业           │
│ ["[all]"]                       ┆ 全部职业           │
│ ["[all]"]                       ┆ 全部职业           │
└─────────────────────────────────┴────────────────────┘

In [138]:
df.filter(pl.col('equipment_type') == '[ring]')

shape: (1_884, 30)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id        ┆ name      ┆ name2     ┆ json      ┆ … ┆ armor_typ ┆ display_e ┆ display_r ┆ display_ │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ e         ┆ quipment_ ┆ arity     ┆ usable_j │
│ i64       ┆ str       ┆ str       ┆ str       ┆   ┆ ---       ┆ type      ┆ ---       ┆ ob       │
│           ┆           ┆           ┆           ┆   ┆ str       ┆ ---       ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆ str       ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 24012     ┆ (旧) 褪色 ┆ Fade      ┆ {"[name]" ┆ … ┆           ┆ 戒指      ┆ 普通      ┆ 全部职业 │
│           ┆ 的青铜戒  ┆ Bronze    ┆ : ["(旧)  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 指        ┆ Ring      ┆ 褪色的青  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 铜戒指"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[…       ┆   ┆           ┆           ┆           ┆          │
│ 24013     ┆ (旧)      ┆ Bronze    ┆ {"[name]" ┆ … ┆           ┆ 戒指      ┆ 高级      ┆ 全部职业 │
│           ┆ 青铜戒指  ┆ Ring      ┆ : ["(旧)  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 青铜戒指" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ], "[nam… ┆   ┆           ┆           ┆           ┆          │
│ 24014     ┆ (旧)      ┆ The 3rd   ┆ {"[name]" ┆ … ┆           ┆ 戒指      ┆ 稀有      ┆ 全部职业 │
│           ┆ 剜心指环  ┆ Finger of ┆ : ["(旧)  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Pulling   ┆ 剜心指环" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Hear…     ┆ ], "[nam… ┆   ┆           ┆           ┆           ┆          │
│ 24015     ┆ (旧) 精致 ┆ Azure     ┆ {"[name]" ┆ … ┆           ┆ 戒指      ┆ 高级      ┆ 全部职业 │
│           ┆ 的青铜戒  ┆ Bronze    ┆ : ["(旧)  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 指        ┆ Ring      ┆ 精致的青  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 铜戒指"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[…       ┆   ┆           ┆           ┆           ┆          │
│ 24016     ┆ (旧) 碎裂 ┆ Rubbed    ┆ {"[name]" ┆ … ┆           ┆ 戒指      ┆ 普通      ┆ 全部职业 │
│           ┆ 的钢铁戒  ┆ Steel     ┆ : ["(旧)  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 指        ┆ Ring      ┆ 碎裂的钢  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 铁戒指"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[…       ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 300320001 ┆ MLA-129   ┆           ┆ {"[name]" ┆ … ┆           ┆ 戒指      ┆ 神器      ┆ 全部职业 │
│           ┆ 能量戒指( ┆           ┆ :         ┆   ┆           ┆           ┆           ┆          │
│           ┆ 冷却时间) ┆           ┆ ["MLA-129 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 能量戒指( ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 冷却时间… ┆   ┆           ┆           ┆           ┆          │
│ 300320002 ┆ MLA-129   ┆           ┆ {"[name]" ┆ … ┆           ┆ 戒指      ┆ 神器      ┆ 全部职业 │
│           ┆ 能量戒指( ┆           ┆ :         ┆   ┆           ┆           ┆           ┆          │
│           ┆ 暴击伤害) ┆           ┆ ["MLA-129 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 能量戒指( ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 暴击伤害… ┆   ┆           ┆           ┆           ┆          │
│ 600320000 ┆ OnTime    ┆ ontime    ┆ {"[name]" ┆ … ┆           ┆ 戒指      ┆ 稀有      ┆ 全部职业 │
│           ┆ 绝对戒指  ┆ ring      ┆ :         ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ["OnTime  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 绝对戒指" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ], "[…    ┆   ┆           ┆           ┆           ┆          │
│ 603200000 ┆ 开国功臣  ┆           ┆ {"[name]" ┆ … ┆           ┆ 戒指      ┆ 稀有      ┆ 全部职业 │
│           ┆ 戒指      ┆           ┆ : ["开国  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 功臣戒指" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ],        ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[flavo…  ┆   ┆           ┆           ┆           ┆          │
│ 603200001 ┆ 宝藏猎人  ┆ Ring of   ┆ {"[name]" ┆ … ┆           ┆ 戒指      ┆ 稀有      ┆ 全部职业 │
│           ┆ 的戒指 -  ┆ treasure  ┆ : ["宝藏  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 鬼剑士    ┆ hunter    ┆ 猎人的戒  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 指 -      ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 鬼剑士"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘