In [1]:
import polars as pl

In [2]:
df = pl.read_parquet(
    "/Users/evrins/workspace/python/DNF_pvf_python/dnfpkgtool/repo/data/equipments.parquet"
)
df

shape: (63_788, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id        ┆ name      ┆ name2     ┆ json      ┆ … ┆ usable_jo ┆ armor_typ ┆ equipment ┆ rarity_d │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ b         ┆ e         ┆ _type_dis ┆ isplay   │
│ i64       ┆ str       ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ play      ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ list[str] ┆ str       ┆ ---       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ str       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 10018     ┆ (旧) 古老 ┆ Old Wool  ┆ {"[name]" ┆ … ┆ ["[all]"] ┆ cl        ┆ 上衣      ┆ 普通     │
│           ┆ 的羊毛背  ┆ Vest      ┆ : ["(旧)  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 心        ┆           ┆ 古老的羊  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 毛背心"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[…       ┆   ┆           ┆           ┆           ┆          │
│ 10019     ┆ (旧)      ┆ Wool Vest ┆ {"[name]" ┆ … ┆ ["[all]"] ┆ cl        ┆ 上衣      ┆ 高级     │
│           ┆ 羊毛背心  ┆           ┆ : ["(旧)  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 羊毛背心" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ], "[nam… ┆   ┆           ┆           ┆           ┆          │
│ 10020     ┆ (旧)      ┆ Robe of   ┆ {"[name]" ┆ … ┆ ["[all]"] ┆ cl        ┆ 上衣      ┆ 稀有     │
│           ┆ 炎麻长袍  ┆ Carbon    ┆ : ["(旧)  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Fiber     ┆ 炎麻长袍" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ], "[nam… ┆   ┆           ┆           ┆           ┆          │
│ 10021     ┆ (旧) 厚绒 ┆ Thick     ┆ {"[name]" ┆ … ┆ ["[all]"] ┆ cl        ┆ 上衣      ┆ 高级     │
│           ┆ 羊毛背心  ┆ Wool Vest ┆ : ["(旧)  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 厚绒羊毛  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 背心"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[n…      ┆   ┆           ┆           ┆           ┆          │
│ 10022     ┆ (旧) 旧式 ┆ Outdated  ┆ {"[name]" ┆ … ┆ ["[all]"] ┆ cl        ┆ 上衣      ┆ 普通     │
│           ┆ 丝绸背心  ┆ Wool      ┆ : ["(旧)  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Tunic     ┆ 旧式丝绸  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 背心"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[n…      ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 101600008 ┆ 阿尔托莉  ┆           ┆ {"[name]" ┆ … ┆ ["[swordm ┆           ┆ 脸部装扮  ┆ 普通     │
│           ┆ 雅的佩剑  ┆           ┆ : ["阿尔  ┆   ┆ an]",     ┆           ┆           ┆          │
│           ┆           ┆           ┆ 托莉雅的  ┆   ┆ "[demonic ┆           ┆           ┆          │
│           ┆           ┆           ┆ 佩剑"],   ┆   ┆ sword…    ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[exp…    ┆   ┆           ┆           ┆           ┆          │
│ 400990109 ┆ 迷你皇女  ┆           ┆ {"[name]" ┆ … ┆ ["[all]"] ┆           ┆ 宠物      ┆ 史诗     │
│           ┆ 艾丽婕    ┆           ┆ : ["迷你  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 皇女艾丽  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 婕"],     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[expl…   ┆   ┆           ┆           ┆           ┆          │
│ 400990502 ┆ 迷你冲浪  ┆           ┆ {"[name]" ┆ … ┆ ["[all]"] ┆           ┆ 宠物      ┆ 史诗     │
│           ┆ 赛丽亚    ┆           ┆ : ["迷你  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 冲浪赛丽  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 亚"],     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[expl…   ┆   ┆           ┆           ┆           ┆          │
│ 400990078 ┆ 灵动小龙  ┆           ┆ {"[name]" ┆ … ┆ ["[all]"] ┆           ┆ 宠物      ┆ 神器     │
│           ┆ 女        ┆           ┆ : ["灵动  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 小龙女"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[flavor… ┆   ┆           ┆           ┆           ┆          │
│ 400990077 ┆ 热辣小龙  ┆           ┆ {"[name]" ┆ … ┆ ["[all]"] ┆           ┆ 宠物      ┆ 神器     │
│           ┆ 女        ┆           ┆ : ["热辣  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 小龙女"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[explai… ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [3]:
df.schema

Schema([('id', Int64),
        ('name', String),
        ('name2', String),
        ('json', String),
        ('level', Int64),
        ('equipment_type', String),
        ('sub_equipment_type', Int64),
        ('item_group_name', String),
        ('usable_job', List(String)),
        ('armor_type', String),
        ('equipment_type_display', String),
        ('rarity_display', String)])

In [4]:
df.select(pl.col("equipment_type")).sort(pl.col("equipment_type")).unique()

shape: (27, 1)
┌──────────────────┐
│ equipment_type   │
│ ---              │
│ str              │
╞══════════════════╡
│                  │
│ [amulet]         │
│ [artifact blue]  │
│ [artifact green] │
│ [artifact red]   │
│ …                │
│ [title name]     │
│ [waist avatar]   │
│ [waist]          │
│ [weapon]         │
│ [wrist]          │
└──────────────────┘

In [5]:
df.filter((pl.col("equipment_type") == "[coat avatar]") & (pl.col("name") != ""))

shape: (3_483, 12)
┌───────────┬────────────┬───────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ id        ┆ name       ┆ name2 ┆ json       ┆ … ┆ usable_job ┆ armor_typ ┆ equipment ┆ rarity_di │
│ ---       ┆ ---        ┆ ---   ┆ ---        ┆   ┆ ---        ┆ e         ┆ _type_dis ┆ splay     │
│ i64       ┆ str        ┆ str   ┆ str        ┆   ┆ list[str]  ┆ ---       ┆ play      ┆ ---       │
│           ┆            ┆       ┆            ┆   ┆            ┆ str       ┆ ---       ┆ str       │
│           ┆            ┆       ┆            ┆   ┆            ┆           ┆ str       ┆           │
╞═══════════╪════════════╪═══════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 103500119 ┆ 层叠式运动 ┆       ┆ {"[name]": ┆ … ┆ ["[at      ┆           ┆ 上衣装扮  ┆ 普通      │
│           ┆ 衫[A型]    ┆       ┆ ["层叠式运 ┆   ┆ fighter]"] ┆           ┆           ┆           │
│           ┆            ┆       ┆ 动衫[A型]" ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ ], "[n…    ┆   ┆            ┆           ┆           ┆           │
│ 103500120 ┆ 层叠式运动 ┆       ┆ {"[name]": ┆ … ┆ ["[at      ┆           ┆ 上衣装扮  ┆ 普通      │
│           ┆ 衫[B型]    ┆       ┆ ["层叠式运 ┆   ┆ fighter]"] ┆           ┆           ┆           │
│           ┆            ┆       ┆ 动衫[B型]" ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ ], "[n…    ┆   ┆            ┆           ┆           ┆           │
│ 103500121 ┆ 层叠式运动 ┆       ┆ {"[name]": ┆ … ┆ ["[at      ┆           ┆ 上衣装扮  ┆ 普通      │
│           ┆ 衫[C型]    ┆       ┆ ["层叠式运 ┆   ┆ fighter]"] ┆           ┆           ┆           │
│           ┆            ┆       ┆ 动衫[C型]" ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ ], "[n…    ┆   ┆            ┆           ┆           ┆           │
│ 103500122 ┆ 层叠式运动 ┆       ┆ {"[name]": ┆ … ┆ ["[at      ┆           ┆ 上衣装扮  ┆ 普通      │
│           ┆ 衫[D型]    ┆       ┆ ["层叠式运 ┆   ┆ fighter]"] ┆           ┆           ┆           │
│           ┆            ┆       ┆ 动衫[D型]" ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ ], "[n…    ┆   ┆            ┆           ┆           ┆           │
│ 103500123 ┆ 无袖上衣[A ┆       ┆ {"[name]": ┆ … ┆ ["[at      ┆           ┆ 上衣装扮  ┆ 普通      │
│           ┆ 型]        ┆       ┆ ["无袖上衣 ┆   ┆ fighter]"] ┆           ┆           ┆           │
│           ┆            ┆       ┆ [A型]"],   ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ "[nam…     ┆   ┆            ┆           ┆           ┆           │
│ …         ┆ …          ┆ …     ┆ …          ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 608500091 ┆ 海滩男孩棉 ┆       ┆ {"[name]": ┆ … ┆ ["[priest] ┆           ┆ 上衣装扮  ┆ 普通      │
│           ┆ 背心       ┆       ┆ ["海滩男孩 ┆   ┆ "]         ┆           ┆           ┆           │
│           ┆            ┆       ┆ 棉背心"],  ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ "[expl…    ┆   ┆            ┆           ┆           ┆           │
│ 609500090 ┆ 海滩罗曼史 ┆       ┆ {"[name]": ┆ … ┆ ["[thief]" ┆           ┆ 上衣装扮  ┆ 普通      │
│           ┆ 挖腰泳装上 ┆       ┆ ["海滩罗曼 ┆   ┆ ]          ┆           ┆           ┆           │
│           ┆ 衣         ┆       ┆ 史挖腰泳装 ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ 上衣"],    ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ "[…        ┆   ┆            ┆           ┆           ┆           │
│ 609500091 ┆ 海滩女孩两 ┆       ┆ {"[name]": ┆ … ┆ ["[thief]" ┆           ┆ 上衣装扮  ┆ 普通      │
│           ┆ 件式泳衣   ┆       ┆ ["海滩女孩 ┆   ┆ ]          ┆           ┆           ┆           │
│           ┆            ┆       ┆ 两件式泳衣 ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ "], "[ex…  ┆   ┆            ┆           ┆           ┆           │
│ 607500076 ┆ 海滩罗曼史 ┆       ┆ {"[name]": ┆ … ┆ ["[at      ┆           ┆ 上衣装扮  ┆ 普通      │
│           ┆ 罩衫外套   ┆       ┆ ["海滩罗曼 ┆   ┆ mage]"]    ┆           ┆           ┆           │
│           ┆            ┆       ┆ 史罩衫外套 ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ "], "[ex…  ┆   ┆            ┆           ┆           ┆           │
│ 607500077 ┆ 海滩男孩紧 ┆       ┆ {"[name]": ┆ … ┆ ["[at      ┆           ┆ 上衣装扮  ┆ 普通      │
│           ┆ 身泳衣上衣 ┆       ┆ ["海滩男孩 ┆   ┆ mage]"]    ┆           ┆           ┆           │
│           ┆            ┆       ┆ 紧身泳衣上 ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ 衣"], "[e… ┆   ┆            ┆           ┆           ┆           │
└───────────┴────────────┴───────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [6]:
df.filter((pl.col("equipment_type") == "") & (pl.col("name") != ""))

shape: (8, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id        ┆ name      ┆ name2     ┆ json      ┆ … ┆ usable_jo ┆ armor_typ ┆ equipment ┆ rarity_d │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ b         ┆ e         ┆ _type_dis ┆ isplay   │
│ i64       ┆ str       ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ play      ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ list[str] ┆ str       ┆ ---       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ str       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2312900   ┆ 成长之契  ┆           ┆ {"[name]" ┆ … ┆ ["[all]"] ┆           ┆ 契约效果  ┆ 高级     │
│           ┆ 约        ┆           ┆ : ["成长  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 之契约"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2]… ┆   ┆           ┆           ┆           ┆          │
│ 100300084 ┆ 黑色小晶  ┆ Black     ┆ {"[name]" ┆ … ┆ ["[all]"] ┆           ┆ 契约效果  ┆ 普通     │
│           ┆ 块效果    ┆ Small     ┆ : ["黑色  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Cube      ┆ 小晶块效  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 果"],     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name…   ┆   ┆           ┆           ┆           ┆          │
│ 100300085 ┆ 蓝色小晶  ┆ Blue      ┆ {"[name]" ┆ … ┆ ["[all]"] ┆           ┆ 契约效果  ┆ 普通     │
│           ┆ 块效果    ┆ Small     ┆ : ["蓝色  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Cube      ┆ 小晶块效  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 果"],     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name…   ┆   ┆           ┆           ┆           ┆          │
│ 100300086 ┆ 红色小晶  ┆ Red Small ┆ {"[name]" ┆ … ┆ ["[all]"] ┆           ┆ 契约效果  ┆ 普通     │
│           ┆ 块效果    ┆ Cube      ┆ : ["红色  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 小晶块效  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 果"],     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name…   ┆   ┆           ┆           ┆           ┆          │
│ 100300087 ┆ 白色小晶  ┆ White     ┆ {"[name]" ┆ … ┆ ["[all]"] ┆           ┆ 契约效果  ┆ 普通     │
│           ┆ 块效果    ┆ Small     ┆ : ["白色  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Cube      ┆ 小晶块效  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 果"],     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name…   ┆   ┆           ┆           ┆           ┆          │
│ 100300088 ┆ 无色小晶  ┆ Nonecolor ┆ {"[name]" ┆ … ┆ ["[all]"] ┆           ┆ 契约效果  ┆ 普通     │
│           ┆ 块效果    ┆ Small     ┆ : ["无色  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Cube      ┆ 小晶块效  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 果"],     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name…   ┆   ┆           ┆           ┆           ┆          │
│ 100300089 ┆ 金色小晶  ┆ Gold      ┆ {"[name]" ┆ … ┆ ["[all]"] ┆           ┆ 契约效果  ┆ 普通     │
│           ┆ 块效果    ┆ Small     ┆ : ["金色  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Cube      ┆ 小晶块效  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 果"],     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name…   ┆   ┆           ┆           ┆           ┆          │
│ 9944451   ┆ 黑钻契约  ┆           ┆ {"[name]" ┆ … ┆ ["[all]"] ┆           ┆ 契约效果  ┆ 普通     │
│           ┆ 附加效果  ┆           ┆ : ["黑钻  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 契约附加  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 效果"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[nam…    ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [7]:
df.filter((pl.col("equipment_type") == "[amulet]") & (pl.col("name") != ""))

shape: (1_850, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id        ┆ name      ┆ name2     ┆ json      ┆ … ┆ usable_jo ┆ armor_typ ┆ equipment ┆ rarity_d │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ b         ┆ e         ┆ _type_dis ┆ isplay   │
│ i64       ┆ str       ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ play      ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ list[str] ┆ str       ┆ ---       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ str       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 20013     ┆ (旧) 褪色 ┆ Fade      ┆ {"[name]" ┆ … ┆ ["[all]"] ┆           ┆ 项链      ┆ 普通     │
│           ┆ 的青铜项  ┆ Bronze    ┆ : ["(旧)  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 链        ┆ Chain     ┆ 褪色的青  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 铜项链"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[…       ┆   ┆           ┆           ┆           ┆          │
│ 20014     ┆ (旧)      ┆ Bronze    ┆ {"[name]" ┆ … ┆ ["[all]"] ┆           ┆ 项链      ┆ 高级     │
│           ┆ 青铜项链  ┆ Chain     ┆ : ["(旧)  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 青铜项链" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ], "[nam… ┆   ┆           ┆           ┆           ┆          │
│ 20015     ┆ (旧) 精致 ┆ Azure     ┆ {"[name]" ┆ … ┆ ["[all]"] ┆           ┆ 项链      ┆ 高级     │
│           ┆ 的青铜项  ┆ Bronze    ┆ : ["(旧)  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 链        ┆ Chain     ┆ 精致的青  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 铜项链"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[…       ┆   ┆           ┆           ┆           ┆          │
│ 20016     ┆ (旧) 哥布 ┆ Goblin    ┆ {"[name]" ┆ … ┆ ["[all]"] ┆           ┆ 项链      ┆ 稀有     │
│           ┆ 林冥骨项  ┆ Bone      ┆ : ["(旧)  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 坠        ┆ Necklace  ┆ 哥布林冥  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 骨项坠"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[…       ┆   ┆           ┆           ┆           ┆          │
│ 20017     ┆ (旧) 磨损 ┆ Peeled    ┆ {"[name]" ┆ … ┆ ["[all]"] ┆           ┆ 项链      ┆ 普通     │
│           ┆ 的镀银项  ┆ Silver    ┆ : ["(旧)  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 链        ┆ Coating   ┆ 磨损的镀  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Necklace  ┆ 银项链"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[…       ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 100310870 ┆ 执刑者的  ┆           ┆ {"[name]" ┆ … ┆ ["[all]"] ┆           ┆ 项链      ┆ 史诗     │
│           ┆ 刺杀项链  ┆           ┆ : ["执刑  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 者的刺杀  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 项链"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[bas…    ┆   ┆           ┆           ┆           ┆          │
│ 300300000 ┆ MLA-014   ┆           ┆ {"[name]" ┆ … ┆ ["[all]"] ┆           ┆ 项链      ┆ 神器     │
│           ┆ 机械项圈( ┆           ┆ :         ┆   ┆           ┆           ┆           ┆          │
│           ┆ 附加伤害) ┆           ┆ ["MLA-014 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 机械项圈( ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 附加伤害… ┆   ┆           ┆           ┆           ┆          │
│ 300300001 ┆ MLA-014   ┆           ┆ {"[name]" ┆ … ┆ ["[all]"] ┆           ┆ 项链      ┆ 神器     │
│           ┆ 机械项圈( ┆           ┆ :         ┆   ┆           ┆           ┆           ┆          │
│           ┆ 冷却时间) ┆           ┆ ["MLA-014 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 机械项圈( ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 冷却时间… ┆   ┆           ┆           ┆           ┆          │
│ 300300002 ┆ MLA-014   ┆           ┆ {"[name]" ┆ … ┆ ["[all]"] ┆           ┆ 项链      ┆ 神器     │
│           ┆ 机械项圈( ┆           ┆ :         ┆   ┆           ┆           ┆           ┆          │
│           ┆ 暴击伤害) ┆           ┆ ["MLA-014 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 机械项圈( ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 暴击伤害… ┆   ┆           ┆           ┆           ┆          │
│ 600300000 ┆ OnTime    ┆ ontime    ┆ {"[name]" ┆ … ┆ ["[all]"] ┆           ┆ 项链      ┆ 稀有     │
│           ┆ 绝对项链  ┆ neck      ┆ :         ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ["OnTime  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 绝对项链" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ], "[…    ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [8]:
df.filter((pl.col("equipment_type") == "[artifact green]") & (pl.col("name") != ""))

shape: (23, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id        ┆ name      ┆ name2     ┆ json      ┆ … ┆ usable_jo ┆ armor_typ ┆ equipment ┆ rarity_d │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ b         ┆ e         ┆ _type_dis ┆ isplay   │
│ i64       ┆ str       ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ play      ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ list[str] ┆ str       ┆ ---       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ str       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 64500     ┆ Artifect  ┆ Artifect  ┆ {"[name]" ┆ … ┆ ["[all]"] ┆           ┆ 绿色      ┆ 稀有     │
│           ┆ Green     ┆ Green     ┆ : [""],   ┆   ┆           ┆           ┆ 宠物装备  ┆          │
│           ┆           ┆           ┆ "[name2]" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ : ["…     ┆   ┆           ┆           ┆           ┆          │
│ 64501     ┆ 翡翠宝珠  ┆ Orb of    ┆ {"[name]" ┆ … ┆ ["[all]"] ┆           ┆ 绿色      ┆ 稀有     │
│           ┆           ┆ Emerald   ┆ : ["翡翠  ┆   ┆           ┆           ┆ 宠物装备  ┆          │
│           ┆           ┆           ┆ 宝珠"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2]" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆          │
│ 64502     ┆ 风之宝珠  ┆ Orb of    ┆ {"[name]" ┆ … ┆ ["[all]"] ┆           ┆ 绿色      ┆ 稀有     │
│           ┆           ┆ Wind      ┆ : ["风之  ┆   ┆           ┆           ┆ 宠物装备  ┆          │
│           ┆           ┆           ┆ 宝珠"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2]" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆          │
│ 64503     ┆ 翡翠冠饰  ┆ Tiara of  ┆ {"[name]" ┆ … ┆ ["[all]"] ┆           ┆ 绿色      ┆ 稀有     │
│           ┆           ┆ Emerald   ┆ : ["翡翠  ┆   ┆           ┆           ┆ 宠物装备  ┆          │
│           ┆           ┆           ┆ 冠饰"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2]" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆          │
│ 64505     ┆ 风之冠饰  ┆ Tiara of  ┆ {"[name]" ┆ … ┆ ["[all]"] ┆           ┆ 绿色      ┆ 稀有     │
│           ┆           ┆ Wind      ┆ : ["风之  ┆   ┆           ┆           ┆ 宠物装备  ┆          │
│           ┆           ┆           ┆ 冠饰"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2]" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 2747198   ┆ 灵咒之罪  ┆           ┆ {"[name]" ┆ … ┆ ["[all]"] ┆           ┆ 绿色      ┆ 神器     │
│           ┆ 恶密钥    ┆           ┆ : ["灵咒  ┆   ┆           ┆           ┆ 宠物装备  ┆          │
│           ┆           ┆           ┆ 之罪恶密  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 钥"],     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[mini…   ┆   ┆           ┆           ┆           ┆          │
│ 2747199   ┆ 灵咒之魔  ┆           ┆ {"[name]" ┆ … ┆ ["[all]"] ┆           ┆ 绿色      ┆ 神器     │
│           ┆ 女宝珠    ┆           ┆ : ["灵咒  ┆   ┆           ┆           ┆ 宠物装备  ┆          │
│           ┆           ┆           ┆ 之魔女宝  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 珠"],     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[mini…   ┆   ┆           ┆           ┆           ┆          │
│ 100330622 ┆ 希望之胜  ┆           ┆ {"[name]" ┆ … ┆ ["[all]"] ┆           ┆ 绿色      ┆ 神器     │
│           ┆ 利红宝石  ┆           ┆ : ["希望  ┆   ┆           ┆           ┆ 宠物装备  ┆          │
│           ┆ 钥匙      ┆           ┆ 之胜利红  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 宝石钥匙" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ], "[m…   ┆   ┆           ┆           ┆           ┆          │
│ 10006770  ┆ 青龙偃月  ┆           ┆ {"[name]" ┆ … ┆ ["[all]"] ┆           ┆ 绿色      ┆ 神器     │
│           ┆ 刀        ┆           ┆ : ["青龙  ┆   ┆           ┆           ┆ 宠物装备  ┆          │
│           ┆           ┆           ┆ 偃月刀"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[flavor… ┆   ┆           ┆           ┆           ┆          │
│ 10006773  ┆ 清爽哈密  ┆           ┆ {"[name]" ┆ … ┆ ["[all]"] ┆           ┆ 绿色      ┆ 神器     │
│           ┆ 瓜冰沙    ┆           ┆ : ["清爽  ┆   ┆           ┆           ┆ 宠物装备  ┆          │
│           ┆           ┆           ┆ 哈密瓜冰  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 沙"],     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[flav…   ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [9]:
df.filter((pl.col("equipment_type") == "[aurora avatar]") & (pl.col("name") != ""))

shape: (268, 12)
┌───────────┬────────────┬───────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ id        ┆ name       ┆ name2 ┆ json       ┆ … ┆ usable_job ┆ armor_typ ┆ equipment ┆ rarity_di │
│ ---       ┆ ---        ┆ ---   ┆ ---        ┆   ┆ ---        ┆ e         ┆ _type_dis ┆ splay     │
│ i64       ┆ str        ┆ str   ┆ str        ┆   ┆ list[str]  ┆ ---       ┆ play      ┆ ---       │
│           ┆            ┆       ┆            ┆   ┆            ┆ str       ┆ ---       ┆ str       │
│           ┆            ┆       ┆            ┆   ┆            ┆           ┆ str       ┆           │
╞═══════════╪════════════╪═══════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 107590007 ┆ 迅捷的奥拉 ┆       ┆ {"[name]": ┆ … ┆ ["[fighter ┆           ┆ 光环      ┆ 普通      │
│           ┆ 光环[格斗  ┆       ┆ ["迅捷的奥 ┆   ┆ ]"]        ┆           ┆           ┆           │
│           ┆ 家(女)]    ┆       ┆ 拉光环[格  ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ 斗家(女)]" ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ ]…         ┆   ┆            ┆           ┆           ┆           │
│ 107590009 ┆ 迅捷的奥拉 ┆       ┆ {"[name]": ┆ … ┆ ["[swordma ┆           ┆ 光环      ┆ 普通      │
│           ┆ 光环[鬼剑  ┆       ┆ ["迅捷的奥 ┆   ┆ n]",       ┆           ┆           ┆           │
│           ┆ 士/黑暗武  ┆       ┆ 拉光环[鬼  ┆   ┆ "[demonic  ┆           ┆           ┆           │
│           ┆ 士]        ┆       ┆ 剑士/黑暗  ┆   ┆ sword…     ┆           ┆           ┆           │
│           ┆            ┆       ┆ 武士]…     ┆   ┆            ┆           ┆           ┆           │
│ 107590010 ┆ 迅捷的奥拉 ┆       ┆ {"[name]": ┆ … ┆ ["[at      ┆           ┆ 光环      ┆ 普通      │
│           ┆ 光环[格斗  ┆       ┆ ["迅捷的奥 ┆   ┆ fighter]"] ┆           ┆           ┆           │
│           ┆ 家(男)]    ┆       ┆ 拉光环[格  ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ 斗家(男)]" ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ ]…         ┆   ┆            ┆           ┆           ┆           │
│ 107590011 ┆ 迅捷的奥拉 ┆       ┆ {"[name]": ┆ … ┆ ["[at      ┆           ┆ 光环      ┆ 普通      │
│           ┆ 光环[魔法  ┆       ┆ ["迅捷的奥 ┆   ┆ mage]"]    ┆           ┆           ┆           │
│           ┆ 师(男)]    ┆       ┆ 拉光环[魔  ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ 法师(男)]" ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ ]…         ┆   ┆            ┆           ┆           ┆           │
│ 107590012 ┆ 迅捷的奥拉 ┆       ┆ {"[name]": ┆ … ┆ ["[thief]" ┆           ┆ 光环      ┆ 普通      │
│           ┆ 光环[暗夜  ┆       ┆ ["迅捷的奥 ┆   ┆ ]          ┆           ┆           ┆           │
│           ┆ 使者]      ┆       ┆ 拉光环[暗  ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ 夜使者]"], ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ …          ┆   ┆            ┆           ┆           ┆           │
│ …         ┆ …          ┆ …     ┆ …          ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 609590009 ┆ 清澈蓝浪花 ┆       ┆ {"[name]": ┆ … ┆ ["[thief]" ┆           ┆ 光环      ┆ 普通      │
│           ┆            ┆       ┆ ["清澈蓝浪 ┆   ┆ ]          ┆           ┆           ┆           │
│           ┆            ┆       ┆ 花"],      ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ "[grade]…  ┆   ┆            ┆           ┆           ┆           │
│ 101590310 ┆ 希望之洗礼 ┆       ┆ {"[name]": ┆ … ┆ ["[all]"]  ┆           ┆ 光环      ┆ 普通      │
│           ┆            ┆       ┆ ["希望之洗 ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ 礼"],      ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ "[basic …  ┆   ┆            ┆           ┆           ┆           │
│ 412590201 ┆ 镜花水月   ┆       ┆ {"[name]": ┆ … ┆ ["[all]"]  ┆           ┆ 光环      ┆ 普通      │
│           ┆            ┆       ┆ ["镜花水月 ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ "],        ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ "[basic e… ┆   ┆            ┆           ┆           ┆           │
│ 401590035 ┆ 魔界大战终 ┆       ┆ {"[name]": ┆ … ┆ ["[all]"]  ┆           ┆ 光环      ┆ 普通      │
│           ┆ 结者       ┆       ┆ ["魔界大战 ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ 终结者"],  ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ "[basi…    ┆   ┆            ┆           ┆           ┆           │
│ 401590108 ┆ 黑色大地的 ┆       ┆ {"[name]": ┆ … ┆ ["[all]"]  ┆           ┆ 光环      ┆ 普通      │
│           ┆ 审判者     ┆       ┆ ["黑色大地 ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ 的审判者"] ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ , "[exp…   ┆   ┆            ┆           ┆           ┆           │
└───────────┴────────────┴───────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [10]:
df.filter((pl.col("equipment_type") == "[breast avatar]") & (pl.col("name") != ""))

shape: (2_784, 12)
┌───────────┬────────────┬───────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ id        ┆ name       ┆ name2 ┆ json       ┆ … ┆ usable_job ┆ armor_typ ┆ equipment ┆ rarity_di │
│ ---       ┆ ---        ┆ ---   ┆ ---        ┆   ┆ ---        ┆ e         ┆ _type_dis ┆ splay     │
│ i64       ┆ str        ┆ str   ┆ str        ┆   ┆ list[str]  ┆ ---       ┆ play      ┆ ---       │
│           ┆            ┆       ┆            ┆   ┆            ┆ str       ┆ ---       ┆ str       │
│           ┆            ┆       ┆            ┆   ┆            ┆           ┆ str       ┆           │
╞═══════════╪════════════╪═══════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 103520132 ┆ 简约围巾[A ┆       ┆ {"[name]": ┆ … ┆ ["[at      ┆           ┆ 胸部装扮  ┆ 普通      │
│           ┆ 型]        ┆       ┆ ["简约围巾 ┆   ┆ fighter]"] ┆           ┆           ┆           │
│           ┆            ┆       ┆ [A型]"],   ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ "[nam…     ┆   ┆            ┆           ┆           ┆           │
│ 103520133 ┆ 简约围巾[B ┆       ┆ {"[name]": ┆ … ┆ ["[at      ┆           ┆ 胸部装扮  ┆ 普通      │
│           ┆ 型]        ┆       ┆ ["简约围巾 ┆   ┆ fighter]"] ┆           ┆           ┆           │
│           ┆            ┆       ┆ [B型]"],   ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ "[nam…     ┆   ┆            ┆           ┆           ┆           │
│ 103520134 ┆ 简约围巾[C ┆       ┆ {"[name]": ┆ … ┆ ["[at      ┆           ┆ 胸部装扮  ┆ 普通      │
│           ┆ 型]        ┆       ┆ ["简约围巾 ┆   ┆ fighter]"] ┆           ┆           ┆           │
│           ┆            ┆       ┆ [C型]"],   ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ "[nam…     ┆   ┆            ┆           ┆           ┆           │
│ 103520135 ┆ 简约围巾[D ┆       ┆ {"[name]": ┆ … ┆ ["[at      ┆           ┆ 胸部装扮  ┆ 普通      │
│           ┆ 型]        ┆       ┆ ["简约围巾 ┆   ┆ fighter]"] ┆           ┆           ┆           │
│           ┆            ┆       ┆ [D型]"],   ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ "[nam…     ┆   ┆            ┆           ┆           ┆           │
│ 103520136 ┆ 围巾[A型]  ┆       ┆ {"[name]": ┆ … ┆ ["[at      ┆           ┆ 胸部装扮  ┆ 普通      │
│           ┆            ┆       ┆ ["围巾[A型 ┆   ┆ fighter]"] ┆           ┆           ┆           │
│           ┆            ┆       ┆ ]"],       ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ "[name2…   ┆   ┆            ┆           ┆           ┆           │
│ …         ┆ …          ┆ …     ┆ …          ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 608520083 ┆ 海滩男孩青 ┆       ┆ {"[name]": ┆ … ┆ ["[priest] ┆           ┆ 胸部装扮  ┆ 普通      │
│           ┆ 铜项链     ┆       ┆ ["海滩男孩 ┆   ┆ "]         ┆           ┆           ┆           │
│           ┆            ┆       ┆ 青铜项链"] ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ , "[exp…   ┆   ┆            ┆           ┆           ┆           │
│ 609520082 ┆ 海滩罗曼史 ┆       ┆ {"[name]": ┆ … ┆ ["[thief]" ┆           ┆ 胸部装扮  ┆ 普通      │
│           ┆ 爱心纹身   ┆       ┆ ["海滩罗曼 ┆   ┆ ]          ┆           ┆           ┆           │
│           ┆            ┆       ┆ 史爱心纹身 ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ "], "[ex…  ┆   ┆            ┆           ┆           ┆           │
│ 609520083 ┆ 海滩女孩爱 ┆       ┆ {"[name]": ┆ … ┆ ["[thief]" ┆           ┆ 胸部装扮  ┆ 普通      │
│           ┆ 心纹身     ┆       ┆ ["海滩女孩 ┆   ┆ ]          ┆           ┆           ┆           │
│           ┆            ┆       ┆ 爱心纹身"] ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ , "[exp…   ┆   ┆            ┆           ┆           ┆           │
│ 607520069 ┆ 海滩罗曼史 ┆       ┆ {"[name]": ┆ … ┆ ["[at      ┆           ┆ 胸部装扮  ┆ 普通      │
│           ┆ 狂野刺青   ┆       ┆ ["海滩罗曼 ┆   ┆ mage]"]    ┆           ┆           ┆           │
│           ┆            ┆       ┆ 史狂野刺青 ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ "], "[ex…  ┆   ┆            ┆           ┆           ┆           │
│ 607520070 ┆ 海滩男孩狂 ┆       ┆ {"[name]": ┆ … ┆ ["[at      ┆           ┆ 胸部装扮  ┆ 普通      │
│           ┆ 野刺青     ┆       ┆ ["海滩男孩 ┆   ┆ mage]"]    ┆           ┆           ┆           │
│           ┆            ┆       ┆ 狂野刺青"] ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ , "[exp…   ┆   ┆            ┆           ┆           ┆           │
└───────────┴────────────┴───────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [11]:
df.filter((pl.col("equipment_type") == "[creature]") & (pl.col("name") != ""))

shape: (233, 12)
┌───────────┬───────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ id        ┆ name      ┆ name2    ┆ json      ┆ … ┆ usable_jo ┆ armor_typ ┆ equipment ┆ rarity_di │
│ ---       ┆ ---       ┆ ---      ┆ ---       ┆   ┆ b         ┆ e         ┆ _type_dis ┆ splay     │
│ i64       ┆ str       ┆ str      ┆ str       ┆   ┆ ---       ┆ ---       ┆ play      ┆ ---       │
│           ┆           ┆          ┆           ┆   ┆ list[str] ┆ str       ┆ ---       ┆ str       │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆ str       ┆           │
╞═══════════╪═══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 63000     ┆ 佛拉斯    ┆ Faras    ┆ {"[name]" ┆ … ┆ ["[all]"] ┆           ┆ 宠物      ┆ 高级      │
│           ┆           ┆          ┆ : ["佛拉  ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ 斯"], "[n ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ ame2]":…  ┆   ┆           ┆           ┆           ┆           │
│ 63001     ┆ 佛尔卡斯  ┆ Pentabas ┆ {"[name]" ┆ … ┆ ["[all]"] ┆           ┆ 宠物      ┆ 高级      │
│           ┆           ┆          ┆ : ["佛尔  ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ 卡斯"],   ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ "[name2]" ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ …         ┆   ┆           ┆           ┆           ┆           │
│ 63002     ┆ 菲尼克斯  ┆ Phoenix  ┆ {"[name]" ┆ … ┆ ["[all]"] ┆           ┆ 宠物      ┆ 高级      │
│           ┆           ┆          ┆ : ["菲尼  ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ 克斯"],   ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ "[name2]" ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ …         ┆   ┆           ┆           ┆           ┆           │
│ 63003     ┆ 恰克斯    ┆ Charp    ┆ {"[name]" ┆ … ┆ ["[all]"] ┆           ┆ 宠物      ┆ 高级      │
│           ┆           ┆          ┆ : ["恰克  ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ 斯"], "[n ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ ame2]":…  ┆   ┆           ┆           ┆           ┆           │
│ 63004     ┆ 哈帕斯    ┆ Halphas  ┆ {"[name]" ┆ … ┆ ["[all]"] ┆           ┆ 宠物      ┆ 高级      │
│           ┆           ┆          ┆ : ["哈帕  ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ 斯"], "[n ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ ame2]":…  ┆   ┆           ┆           ┆           ┆           │
│ …         ┆ …         ┆ …        ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 2750000   ┆ 蓝喜鹊    ┆ bluebird ┆ {"[name]" ┆ … ┆ ["[all]"] ┆           ┆ 宠物      ┆ 神器      │
│           ┆           ┆          ┆ : ["蓝喜  ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ 鹊"], "[n ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ ame2]":…  ┆   ┆           ┆           ┆           ┆           │
│ 400990109 ┆ 迷你皇女  ┆          ┆ {"[name]" ┆ … ┆ ["[all]"] ┆           ┆ 宠物      ┆ 史诗      │
│           ┆ 艾丽婕    ┆          ┆ : ["迷你  ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ 皇女艾丽  ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ 婕"],     ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ "[expl…   ┆   ┆           ┆           ┆           ┆           │
│ 400990502 ┆ 迷你冲浪  ┆          ┆ {"[name]" ┆ … ┆ ["[all]"] ┆           ┆ 宠物      ┆ 史诗      │
│           ┆ 赛丽亚    ┆          ┆ : ["迷你  ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ 冲浪赛丽  ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ 亚"],     ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ "[expl…   ┆   ┆           ┆           ┆           ┆           │
│ 400990078 ┆ 灵动小龙  ┆          ┆ {"[name]" ┆ … ┆ ["[all]"] ┆           ┆ 宠物      ┆ 神器      │
│           ┆ 女        ┆          ┆ : ["灵动  ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ 小龙女"], ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ "[flavor… ┆   ┆           ┆           ┆           ┆           │
│ 400990077 ┆ 热辣小龙  ┆          ┆ {"[name]" ┆ … ┆ ["[all]"] ┆           ┆ 宠物      ┆ 神器      │
│           ┆ 女        ┆          ┆ : ["热辣  ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ 小龙女"], ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆          ┆ "[explai… ┆   ┆           ┆           ┆           ┆           │
└───────────┴───────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [12]:
df.filter((pl.col("equipment_type") == "[support]") & (pl.col("name") != ""))

shape: (967, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id        ┆ name      ┆ name2     ┆ json      ┆ … ┆ usable_jo ┆ armor_typ ┆ equipment ┆ rarity_d │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ b         ┆ e         ┆ _type_dis ┆ isplay   │
│ i64       ┆ str       ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ play      ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ list[str] ┆ str       ┆ ---       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ str       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 440000    ┆ 古老的丝  ┆ Old Silky ┆ {"[name]" ┆ … ┆ ["[all]"] ┆           ┆ 辅助装备  ┆ 普通     │
│           ┆ 绒臂章    ┆ Yarn      ┆ : ["古老  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Armband   ┆ 的丝绒臂  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 章"],     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name…   ┆   ┆           ┆           ┆           ┆          │
│ 440001    ┆ 丝绒臂章  ┆ Silky     ┆ {"[name]" ┆ … ┆ ["[all]"] ┆           ┆ 辅助装备  ┆ 高级     │
│           ┆           ┆ Yarn      ┆ : ["丝绒  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Armband   ┆ 臂章"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2]" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆          │
│ 440003    ┆ 虚祖王室  ┆ Sujue     ┆ {"[name]" ┆ … ┆ ["[all]"] ┆           ┆ 辅助装备  ┆ 神器     │
│           ┆ 臂章      ┆ Royal     ┆ : ["虚祖  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Family    ┆ 王室臂章" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Armband   ┆ ],        ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2…  ┆   ┆           ┆           ┆           ┆          │
│ 440004    ┆ 布万加的  ┆ Bwanga's  ┆ {"[name]" ┆ … ┆ ["[all]"] ┆           ┆ 辅助装备  ┆ 史诗     │
│           ┆ 族长臂章  ┆ Patriarch ┆ : ["布万  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Armband   ┆ 加的族长  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 臂章"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[nam…    ┆   ┆           ┆           ┆           ┆          │
│ 440016    ┆ 剑魂巴恩  ┆ Noble     ┆ {"[name]" ┆ … ┆ ["[swordm ┆           ┆ 辅助装备  ┆ 神器     │
│           ┆ 的手套    ┆ Glove of  ┆ : ["剑魂  ┆   ┆ an]"]     ┆           ┆           ┆          │
│           ┆           ┆ Bhan      ┆ 巴恩的手  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 套"],     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name…   ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 100341669 ┆ 时间旅行  ┆           ┆ {"[name]" ┆ … ┆ ["[all]"] ┆           ┆ 辅助装备  ┆ 史诗     │
│           ┆ 者的随身  ┆           ┆ : ["时间  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 怀表      ┆           ┆ 旅行者的  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 随身怀表" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ], "[b…   ┆   ┆           ┆           ┆           ┆          │
│ 300340000 ┆ MLA-600   ┆           ┆ {"[name]" ┆ … ┆ ["[all]"] ┆           ┆ 辅助装备  ┆ 神器     │
│           ┆ 机械臂章( ┆           ┆ :         ┆   ┆           ┆           ┆           ┆          │
│           ┆ 附加伤害) ┆           ┆ ["MLA-600 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 机械臂章( ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 附加伤害… ┆   ┆           ┆           ┆           ┆          │
│ 300340001 ┆ MLA-600   ┆           ┆ {"[name]" ┆ … ┆ ["[all]"] ┆           ┆ 辅助装备  ┆ 神器     │
│           ┆ 机械臂章( ┆           ┆ :         ┆   ┆           ┆           ┆           ┆          │
│           ┆ 冷却时间) ┆           ┆ ["MLA-600 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 机械臂章( ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 冷却时间… ┆   ┆           ┆           ┆           ┆          │
│ 300340002 ┆ MLA-600   ┆           ┆ {"[name]" ┆ … ┆ ["[all]"] ┆           ┆ 辅助装备  ┆ 神器     │
│           ┆ 机械臂章( ┆           ┆ :         ┆   ┆           ┆           ┆           ┆          │
│           ┆ 暴击伤害) ┆           ┆ ["MLA-600 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 机械臂章( ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 暴击伤害… ┆   ┆           ┆           ┆           ┆          │
│ 600340000 ┆ 觉醒勇士  ┆ awake     ┆ {"[name]" ┆ … ┆ ["[all]"] ┆           ┆ 辅助装备  ┆ 稀有     │
│           ┆ 的辅助装  ┆ support   ┆ : ["觉醒  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 备        ┆           ┆ 勇士的辅  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 助装备"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[na…     ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [13]:
df.filter((pl.col("equipment_type") == "[weapon]") & (pl.col("name") != ""))

shape: (7_915, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id        ┆ name      ┆ name2     ┆ json      ┆ … ┆ usable_jo ┆ armor_typ ┆ equipment ┆ rarity_d │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ b         ┆ e         ┆ _type_dis ┆ isplay   │
│ i64       ┆ str       ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ play      ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ list[str] ┆ str       ┆ ---       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ str       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 29000     ┆ 普通手套  ┆ Default   ┆ {"[name]" ┆ … ┆ ["[fighte ┆           ┆ 武器      ┆ 普通     │
│           ┆           ┆ Gloves    ┆ : ["普通  ┆   ┆ r]", "[at ┆           ┆           ┆          │
│           ┆           ┆           ┆ 手套"],   ┆   ┆ fighter]" ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2]" ┆   ┆ ]         ┆           ┆           ┆          │
│           ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆          │
│ 29016     ┆ (旧) 破旧 ┆ Outdated  ┆ {"[name]" ┆ … ┆ ["[fighte ┆           ┆ 武器      ┆ 普通     │
│           ┆ 的蚕丝手  ┆ Hora      ┆ : ["(旧)  ┆   ┆ r]", "[at ┆           ┆           ┆          │
│           ┆ 套        ┆           ┆ 破旧的蚕  ┆   ┆ fighter]" ┆           ┆           ┆          │
│           ┆           ┆           ┆ 丝手套"], ┆   ┆ ]         ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[…       ┆   ┆           ┆           ┆           ┆          │
│ 29017     ┆ (旧)      ┆ Hora      ┆ {"[name]" ┆ … ┆ ["[fighte ┆           ┆ 武器      ┆ 高级     │
│           ┆ 蚕丝手套  ┆           ┆ : ["(旧)  ┆   ┆ r]", "[at ┆           ┆           ┆          │
│           ┆           ┆           ┆ 蚕丝手套" ┆   ┆ fighter]" ┆           ┆           ┆          │
│           ┆           ┆           ┆ ], "[nam… ┆   ┆ ]         ┆           ┆           ┆          │
│ 29018     ┆ (旧) 十夫 ┆ Knuckle   ┆ {"[name]" ┆ … ┆ ["[fighte ┆           ┆ 武器      ┆ 稀有     │
│           ┆ 长的手套  ┆ of Chief  ┆ : ["(旧)  ┆   ┆ r]", "[at ┆           ┆           ┆          │
│           ┆           ┆ Sign      ┆ 十夫长的  ┆   ┆ fighter]" ┆           ┆           ┆          │
│           ┆           ┆           ┆ 手套"],   ┆   ┆ ]         ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[n…      ┆   ┆           ┆           ┆           ┆          │
│ 29019     ┆ (旧) 坚固 ┆ Strong    ┆ {"[name]" ┆ … ┆ ["[fighte ┆           ┆ 武器      ┆ 高级     │
│           ┆ 的蚕丝手  ┆ Hora      ┆ : ["(旧)  ┆   ┆ r]", "[at ┆           ┆           ┆          │
│           ┆ 套        ┆           ┆ 坚固的蚕  ┆   ┆ fighter]" ┆           ┆           ┆          │
│           ┆           ┆           ┆ 丝手套"], ┆   ┆ ]         ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[…       ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 609020004 ┆ 传承 :    ┆ Legacy :  ┆ {"[name]" ┆ … ┆ ["[thief] ┆           ┆ 武器      ┆ 传承     │
│           ┆ 复魂天使  ┆ Mummy     ┆ : ["传承  ┆   ┆ "]        ┆           ┆           ┆          │
│           ┆ 的木乃伊  ┆ Wand of   ┆ : 复魂天  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 手杖      ┆ Lauvi     ┆ 使的木乃  ┆   ┆           ┆           ┆           ┆          │
│           ┆ [活动]    ┆           ┆ 伊手杖 [… ┆   ┆           ┆           ┆           ┆          │
│ 609020005 ┆ 传承 :    ┆ Legacy :  ┆ {"[name]" ┆ … ┆ ["[thief] ┆           ┆ 武器      ┆ 传承     │
│           ┆ 暗影精灵  ┆ Logna     ┆ : ["传承  ┆   ┆ "]        ┆           ┆           ┆          │
│           ┆ 的罗格纳  ┆ Demos of  ┆ : 暗影精  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 手杖      ┆ Reiden    ┆ 灵的罗格  ┆   ┆           ┆           ┆           ┆          │
│           ┆ [活动]    ┆           ┆ 纳手杖 [… ┆   ┆           ┆           ┆           ┆          │
│ 609020006 ┆ 传承 :    ┆ Legacy :  ┆ {"[name]" ┆ … ┆ ["[thief] ┆           ┆ 武器      ┆ 传承     │
│           ┆ 毒狱天使  ┆ Airamos   ┆ : ["传承  ┆   ┆ "]        ┆           ┆           ┆          │
│           ┆ 的阿摩司  ┆ of Oreas  ┆ : 毒狱天  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 手杖      ┆           ┆ 使的阿摩  ┆   ┆           ┆           ┆           ┆          │
│           ┆ [活动]    ┆           ┆ 司手杖 [… ┆   ┆           ┆           ┆           ┆          │
│ 609020007 ┆ 传承 :    ┆ Legacy :  ┆ {"[name]" ┆ … ┆ ["[thief] ┆           ┆ 武器      ┆ 传承     │
│           ┆ 炎魔精灵  ┆ Gud Rota  ┆ : ["传承  ┆   ┆ "]        ┆           ┆           ┆          │
│           ┆ 的祭祀手  ┆ of Salim  ┆ : 炎魔精  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 杖 [活动] ┆           ┆ 灵的祭祀  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 手杖 [活… ┆   ┆           ┆           ┆           ┆          │
│ 609020008 ┆ 茁壮冒险  ┆ taiwan    ┆ {"[name]" ┆ … ┆ ["[thief] ┆           ┆ 武器      ┆ 稀有     │
│           ┆ 家的成长  ┆ newbie    ┆ : ["茁壮  ┆   ┆ "]        ┆           ┆           ┆          │
│           ┆ 权杖      ┆ support   ┆ 冒险家的  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 2nd       ┆ 成长权杖" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ], "[n…   ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [14]:
df.filter(pl.col("id") == 11338)

shape: (1, 12)
┌───────┬────────────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ id    ┆ name       ┆ name2      ┆ json       ┆ … ┆ usable_jo ┆ armor_typ ┆ equipment ┆ rarity_di │
│ ---   ┆ ---        ┆ ---        ┆ ---        ┆   ┆ b         ┆ e         ┆ _type_dis ┆ splay     │
│ i64   ┆ str        ┆ str        ┆ str        ┆   ┆ ---       ┆ ---       ┆ play      ┆ ---       │
│       ┆            ┆            ┆            ┆   ┆ list[str] ┆ str       ┆ ---       ┆ str       │
│       ┆            ┆            ┆            ┆   ┆           ┆           ┆ str       ┆           │
╞═══════╪════════════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 11338 ┆ 古老的鳞岩 ┆ Low-Cost   ┆ {"[name]": ┆ … ┆ ["[all]"] ┆ ha        ┆ 上衣      ┆ 稀有      │
│       ┆ 胸甲       ┆ Carbollite ┆ ["古老的鳞 ┆   ┆           ┆           ┆           ┆           │
│       ┆            ┆ Breastplat ┆ 岩胸甲"],  ┆   ┆           ┆           ┆           ┆           │
│       ┆            ┆ …          ┆ "[name…    ┆   ┆           ┆           ┆           ┆           │
└───────┴────────────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [15]:
df.select(pl.col("item_group_name")).unique()

shape: (59, 1)
┌─────────────────┐
│ item_group_name │
│ ---             │
│ str             │
╞═════════════════╡
│ la shoulder     │
│ staff           │
│ rod             │
│ cl pants        │
│ tonfa           │
│ …               │
│ ha shoes        │
│ axe             │
│ magic stone     │
│ rosary          │
│ mt pants        │
└─────────────────┘

In [16]:
df.select(pl.col("equipment_type")).unique()

shape: (27, 1)
┌─────────────────┐
│ equipment_type  │
│ ---             │
│ str             │
╞═════════════════╡
│                 │
│ [magic stone]   │
│ [title name]    │
│ [face avatar]   │
│ [pants]         │
│ …               │
│ [artifact blue] │
│ [shoes]         │
│ [support]       │
│ [artifact red]  │
│ [pants avatar]  │
└─────────────────┘

In [17]:
df.filter((pl.col("equipment_type") == "[title name]") & (pl.col("name") != ""))

shape: (762, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id        ┆ name      ┆ name2     ┆ json      ┆ … ┆ usable_jo ┆ armor_typ ┆ equipment ┆ rarity_d │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ b         ┆ e         ┆ _type_dis ┆ isplay   │
│ i64       ┆ str       ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ play      ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ list[str] ┆ str       ┆ ---       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ str       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 26001     ┆ (旧) 卡妮 ┆ Kanna's   ┆ {"[name]" ┆ … ┆ ["[all]"] ┆           ┆ 称号      ┆ 稀有     │
│           ┆ 娜的希望☆ ┆ slave     ┆ : ["(旧)  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 卡妮娜的  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 希望☆"],  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[…       ┆   ┆           ┆           ┆           ┆          │
│ 26002     ┆ 温暖的心  ┆ Warmmind  ┆ {"[name]" ┆ … ┆ ["[all]"] ┆           ┆ 称号      ┆ 稀有     │
│           ┆           ┆           ┆ : ["温暖  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 的心"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2]" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆          │
│ 26003     ┆ 皇女的护  ┆ Skadyguar ┆ {"[name]" ┆ … ┆ ["[all]"] ┆           ┆ 称号      ┆ 稀有     │
│           ┆ 卫        ┆ d         ┆ : ["皇女  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 的护卫"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2]… ┆   ┆           ┆           ┆           ┆          │
│ 26004     ┆ 帝国见习  ┆ Empireapp ┆ {"[name]" ┆ … ┆ ["[all]"] ┆           ┆ 称号      ┆ 稀有     │
│           ┆ 骑士      ┆ rentice   ┆ : ["帝国  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 见习骑士" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ],        ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2…  ┆   ┆           ┆           ┆           ┆          │
│ 26005     ┆ 罗马宽剑  ┆ Gladios   ┆ {"[name]" ┆ … ┆ ["[all]"] ┆           ┆ 称号      ┆ 稀有     │
│           ┆           ┆           ┆ : ["罗马  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 宽剑"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2]" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 100331258 ┆ 蓝色海浪  ┆           ┆ {"[name]" ┆ … ┆ ["[all]"] ┆           ┆ 称号      ┆ 稀有     │
│           ┆           ┆           ┆ : ["蓝色  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 海浪"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[explain ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆          │
│ 100331259 ┆ 红色夕阳- ┆           ┆ {"[name]" ┆ … ┆ ["[all]"] ┆           ┆ 称号      ┆ 稀有     │
│           ┆ 白金      ┆           ┆ : ["红色  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 夕阳-白金 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "],       ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[grad…   ┆   ┆           ┆           ┆           ┆          │
│ 100331260 ┆ 型男辣妹- ┆           ┆ {"[name]" ┆ … ┆ ["[all]"] ┆           ┆ 称号      ┆ 稀有     │
│           ┆ 白金      ┆           ┆ : ["型男  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 辣妹-白金 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "],       ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[grad…   ┆   ┆           ┆           ┆           ┆          │
│ 100331261 ┆ 蓝色海浪- ┆           ┆ {"[name]" ┆ … ┆ ["[all]"] ┆           ┆ 称号      ┆ 稀有     │
│           ┆ 白金      ┆           ┆ : ["蓝色  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 海浪-白金 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "],       ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[expl…   ┆   ┆           ┆           ┆           ┆          │
│ 20251005  ┆ 赛丽亚的  ┆ [Seria]   ┆ {"[name]" ┆ … ┆ ["[all]"] ┆           ┆ 称号      ┆ 史诗     │
│           ┆ 祝福      ┆           ┆ : ["赛丽  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 亚的祝福" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ],        ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2…  ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [18]:
df.filter(pl.col("name") == "守护腰带")

shape: (1, 12)
┌───────┬──────────┬────────────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ id    ┆ name     ┆ name2      ┆ json       ┆ … ┆ usable_job ┆ armor_type ┆ equipment ┆ rarity_di │
│ ---   ┆ ---      ┆ ---        ┆ ---        ┆   ┆ ---        ┆ ---        ┆ _type_dis ┆ splay     │
│ i64   ┆ str      ┆ str        ┆ str        ┆   ┆ list[str]  ┆ str        ┆ play      ┆ ---       │
│       ┆          ┆            ┆            ┆   ┆            ┆            ┆ ---       ┆ str       │
│       ┆          ┆            ┆            ┆   ┆            ┆            ┆ str       ┆           │
╞═══════╪══════════╪════════════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 17242 ┆ 守护腰带 ┆ Protection ┆ {"[name]": ┆ … ┆ ["[all]"]  ┆ ha         ┆ 腰带      ┆ 稀有      │
│       ┆          ┆ Belt       ┆ ["守护腰带 ┆   ┆            ┆            ┆           ┆           │
│       ┆          ┆            ┆ "],        ┆   ┆            ┆            ┆           ┆           │
│       ┆          ┆            ┆ "[name2]"… ┆   ┆            ┆            ┆           ┆           │
└───────┴──────────┴────────────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

In [19]:
df.select(pl.col("item_category")).unique()

ColumnNotFoundError: unable to find column "item_category"; valid columns: ["id", "name", "name2", "json", "level", "equipment_type", "sub_equipment_type", "item_group_name", "usable_job", "armor_type", "equipment_type_display", "rarity_display"]

In [100]:
df.filter(pl.col("item_category") == "clear avatar")

shape: (27, 13)
┌───────────┬────────────┬───────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ id        ┆ name       ┆ name2 ┆ json       ┆ … ┆ item_categ ┆ usable_jo ┆ armor_typ ┆ equipment │
│ ---       ┆ ---        ┆ ---   ┆ ---        ┆   ┆ ory        ┆ b         ┆ e         ┆ _type_dis │
│ i64       ┆ str        ┆ str   ┆ str        ┆   ┆ ---        ┆ ---       ┆ ---       ┆ play      │
│           ┆            ┆       ┆            ┆   ┆ str        ┆ list[str] ┆ str       ┆ ---       │
│           ┆            ┆       ┆            ┆   ┆            ┆           ┆           ┆ str       │
╞═══════════╪════════════╪═══════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 601560133 ┆ 梦幻克隆装 ┆       ┆ {"[name]": ┆ … ┆ clear      ┆ ["[swordm ┆           ┆ 头部装扮  │
│           ┆ 扮头部     ┆       ┆ ["梦幻克隆 ┆   ┆ avatar     ┆ an]",     ┆           ┆           │
│           ┆            ┆       ┆ 装扮头部"] ┆   ┆            ┆ "[demonic ┆           ┆           │
│           ┆            ┆       ┆ , "[fla…   ┆   ┆            ┆ sword…    ┆           ┆           │
│ 601570104 ┆ 梦幻克隆装 ┆       ┆ {"[name]": ┆ … ┆ clear      ┆ ["[swordm ┆           ┆ 脸部装扮  │
│           ┆ 扮脸部     ┆       ┆ ["梦幻克隆 ┆   ┆ avatar     ┆ an]",     ┆           ┆           │
│           ┆            ┆       ┆ 装扮脸部"] ┆   ┆            ┆ "[demonic ┆           ┆           │
│           ┆            ┆       ┆ , "[fla…   ┆   ┆            ┆ sword…    ┆           ┆           │
│ 601530111 ┆ 梦幻克隆装 ┆       ┆ {"[name]": ┆ … ┆ clear      ┆ ["[swordm ┆           ┆ 腰部装扮  │
│           ┆ 扮腰部     ┆       ┆ ["梦幻克隆 ┆   ┆ avatar     ┆ an]",     ┆           ┆           │
│           ┆            ┆       ┆ 装扮腰部"] ┆   ┆            ┆ "[demonic ┆           ┆           │
│           ┆            ┆       ┆ , "[fla…   ┆   ┆            ┆ sword…    ┆           ┆           │
│ 603560110 ┆ 梦幻克隆装 ┆       ┆ {"[name]": ┆ … ┆ clear      ┆ ["[at fig ┆           ┆ 头部装扮  │
│           ┆ 扮头部     ┆       ┆ ["梦幻克隆 ┆   ┆ avatar     ┆ hter]"]   ┆           ┆           │
│           ┆            ┆       ┆ 装扮头部"] ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ , "[fla…   ┆   ┆            ┆           ┆           ┆           │
│ 603570086 ┆ 梦幻克隆装 ┆       ┆ {"[name]": ┆ … ┆ clear      ┆ ["[at fig ┆           ┆ 脸部装扮  │
│           ┆ 扮脸部     ┆       ┆ ["梦幻克隆 ┆   ┆ avatar     ┆ hter]"]   ┆           ┆           │
│           ┆            ┆       ┆ 装扮脸部"] ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ , "[fla…   ┆   ┆            ┆           ┆           ┆           │
│ …         ┆ …          ┆ …     ┆ …          ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 108570084 ┆ 梦幻克隆装 ┆       ┆ {"[name]": ┆ … ┆ clear      ┆ ["[priest ┆           ┆ 脸部装扮  │
│           ┆ 扮脸部     ┆       ┆ ["梦幻克隆 ┆   ┆ avatar     ┆ ]"]       ┆           ┆           │
│           ┆            ┆       ┆ 装扮脸部"] ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ , "[fla…   ┆   ┆            ┆           ┆           ┆           │
│ 608530086 ┆ 梦幻克隆装 ┆       ┆ {"[name]": ┆ … ┆ clear      ┆ ["[priest ┆           ┆ 腰部装扮  │
│           ┆ 扮腰部     ┆       ┆ ["梦幻克隆 ┆   ┆ avatar     ┆ ]"]       ┆           ┆           │
│           ┆            ┆       ┆ 装扮腰部"] ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ , "[fla…   ┆   ┆            ┆           ┆           ┆           │
│ 609560112 ┆ 梦幻克隆装 ┆       ┆ {"[name]": ┆ … ┆ clear      ┆ ["[thief] ┆           ┆ 头部装扮  │
│           ┆ 扮头部     ┆       ┆ ["梦幻克隆 ┆   ┆ avatar     ┆ "]        ┆           ┆           │
│           ┆            ┆       ┆ 装扮头部"] ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ , "[fla…   ┆   ┆            ┆           ┆           ┆           │
│ 109570078 ┆ 梦幻克隆装 ┆       ┆ {"[name]": ┆ … ┆ clear      ┆ ["[thief] ┆           ┆ 脸部装扮  │
│           ┆ 扮脸部     ┆       ┆ ["梦幻克隆 ┆   ┆ avatar     ┆ "]        ┆           ┆           │
│           ┆            ┆       ┆ 装扮脸部"] ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ , "[fla…   ┆   ┆            ┆           ┆           ┆           │
│ 609530092 ┆ 梦幻克隆装 ┆       ┆ {"[name]": ┆ … ┆ clear      ┆ ["[thief] ┆           ┆ 腰部装扮  │
│           ┆ 扮腰部     ┆       ┆ ["梦幻克隆 ┆   ┆ avatar     ┆ "]        ┆           ┆           │
│           ┆            ┆       ┆ 装扮腰部"] ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ , "[fla…   ┆   ┆            ┆           ┆           ┆           │
└───────────┴────────────┴───────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [20]:
df.filter(pl.col("rarity_display") == "史诗")

shape: (1_338, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id        ┆ name      ┆ name2     ┆ json      ┆ … ┆ usable_jo ┆ armor_typ ┆ equipment ┆ rarity_d │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ b         ┆ e         ┆ _type_dis ┆ isplay   │
│ i64       ┆ str       ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ play      ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ list[str] ┆ str       ┆ ---       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ str       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 10114     ┆ (旧) 银月 ┆ Spangle   ┆ {"[name]" ┆ … ┆ ["[all]"] ┆ cl        ┆ 上衣      ┆ 史诗     │
│           ┆ 少女T恤衫 ┆ Girl      ┆ : ["(旧)  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ T-Shirts  ┆ 银月少女T ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 恤衫"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[…       ┆   ┆           ┆           ┆           ┆          │
│ 10115     ┆ (旧) 天翎 ┆ Araclotho ┆ {"[name]" ┆ … ┆ ["[all]"] ┆ cl        ┆ 上衣      ┆ 史诗     │
│           ┆ 逐月长袍  ┆ 's Silk   ┆ : ["(旧)  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ shirts    ┆ 天翎逐月  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 长袍"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[n…      ┆   ┆           ┆           ┆           ┆          │
│ 10116     ┆ (旧) 希曼 ┆ Himan     ┆ {"[name]" ┆ … ┆ ["[all]"] ┆ cl        ┆ 上衣      ┆ 史诗     │
│           ┆ 的影舞衬  ┆ Stella's  ┆ : ["(旧)  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 衫        ┆ Rangerie  ┆ 希曼的影  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Top       ┆ 舞衬衫"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[…       ┆   ┆           ┆           ┆           ┆          │
│ 10117     ┆ (旧) 幽灵 ┆ Floating  ┆ {"[name]" ┆ … ┆ ["[all]"] ┆ cl        ┆ 上衣      ┆ 史诗     │
│           ┆ 穿云长袍  ┆ Ghosts    ┆ : ["(旧)  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 幽灵穿云  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 长袍"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[n…      ┆   ┆           ┆           ┆           ┆          │
│ 10493     ┆ (旧) 青龙 ┆ DragonHid ┆ {"[name]" ┆ … ┆ ["[all]"] ┆ lt        ┆ 上衣      ┆ 史诗     │
│           ┆ 啸月胸甲  ┆ e Coat    ┆ : ["(旧)  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 青龙啸月  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 胸甲"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[n…      ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 400350048 ┆ 暗黑克雷  ┆           ┆ {"[name]" ┆ … ┆ ["[all]"] ┆           ┆ 魔法石    ┆ 史诗     │
│           ┆ 泽的龟甲  ┆           ┆ : ["暗黑  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 克雷泽的  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 龟甲"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[bas…    ┆   ┆           ┆           ┆           ┆          │
│ 400350049 ┆ 彩虹克雷  ┆           ┆ {"[name]" ┆ … ┆ ["[all]"] ┆           ┆ 魔法石    ┆ 史诗     │
│           ┆ 泽的龟甲  ┆           ┆ : ["彩虹  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 克雷泽的  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 龟甲"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[bas…    ┆   ┆           ┆           ┆           ┆          │
│ 20251005  ┆ 赛丽亚的  ┆ [Seria]   ┆ {"[name]" ┆ … ┆ ["[all]"] ┆           ┆ 称号      ┆ 史诗     │
│           ┆ 祝福      ┆           ┆ : ["赛丽  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 亚的祝福" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ],        ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2…  ┆   ┆           ┆           ┆           ┆          │
│ 400990109 ┆ 迷你皇女  ┆           ┆ {"[name]" ┆ … ┆ ["[all]"] ┆           ┆ 宠物      ┆ 史诗     │
│           ┆ 艾丽婕    ┆           ┆ : ["迷你  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 皇女艾丽  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 婕"],     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[expl…   ┆   ┆           ┆           ┆           ┆          │
│ 400990502 ┆ 迷你冲浪  ┆           ┆ {"[name]" ┆ … ┆ ["[all]"] ┆           ┆ 宠物      ┆ 史诗     │
│           ┆ 赛丽亚    ┆           ┆ : ["迷你  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 冲浪赛丽  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 亚"],     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[expl…   ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘