In [2]:
import polars as pl

In [3]:
df = pl.read_parquet(
    '/Users/evrins/workspace/python/DNF_pvf_python/dnfpkgtool/repo/data/items.parquet'
)
df

shape: (14_493, 11)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ id       ┆ name      ┆ name2     ┆ json      ┆ … ┆ sub_stack ┆ item_grou ┆ item_cate ┆ stackable │
│ ---      ┆ ---       ┆ ---       ┆ ---       ┆   ┆ able_type ┆ p_name    ┆ gory      ┆ _type_dis │
│ i64      ┆ str       ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ play      │
│          ┆           ┆           ┆           ┆   ┆ i64       ┆ str       ┆ str       ┆ ---       │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ str       │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0        ┆ 金币      ┆ Gold      ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 消耗品    │
│          ┆           ┆           ┆ :         ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ ["金币"], ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ "[name2]" ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ : …       ┆   ┆           ┆           ┆           ┆           │
│ 1        ┆ 复活币    ┆ Coin      ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 其他      │
│          ┆           ┆           ┆ : ["复活  ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ 币"], "[n ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ ame2]":…  ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 决斗胜点  ┆ PvP       ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 其他      │
│          ┆           ┆ Victory   ┆ : ["决斗  ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆ Point     ┆ 胜点"],   ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ "[name2]" ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆           │
│ 3        ┆ 遗忘河之  ┆ The River ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 其他      │
│          ┆ 水        ┆ of Lethe  ┆ : ["遗忘  ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ 河之水"], ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ "[name2]… ┆   ┆           ┆           ┆           ┆           │
│ 4        ┆ 普通金库  ┆ Basic     ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 其他      │
│          ┆           ┆ Store     ┆ : ["普通  ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ 金库"],   ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ "[name2]" ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆           │
│ …        ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 20250927 ┆ 祖传武器  ┆           ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 礼包      │
│          ┆ 宝箱      ┆           ┆ : ["祖传  ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ 武器宝箱" ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ ],        ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ "[name2…  ┆   ┆           ┆           ┆           ┆           │
│ 83868    ┆ 有期限的  ┆           ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 礼包      │
│          ┆ 稀有克隆  ┆           ┆ : ["有期  ┆   ┆           ┆           ┆           ┆           │
│          ┆ 装扮套装  ┆           ┆ 限的稀有  ┆   ┆           ┆           ┆           ┆           │
│          ┆ 礼盒      ┆           ┆ 克隆装扮  ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ 套装礼盒" ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ ],…       ┆   ┆           ┆           ┆           ┆           │
│ 2683028  ┆ Fate/Zero ┆           ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 礼包      │
│          ┆ 诸王的命  ┆           ┆ : ["Fate/ ┆   ┆           ┆           ┆           ┆           │
│          ┆ 运装扮    ┆           ┆ Zero诸王  ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ 的命运装  ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ 扮"…      ┆   ┆           ┆           ┆           ┆           │
│ 8888     ┆ 命运的抉  ┆           ┆ {"[name]" ┆ … ┆ 1         ┆           ┆           ┆ 其他      │
│          ┆ 择+15装备 ┆           ┆ : ["命运  ┆   ┆           ┆           ┆           ┆           │
│          ┆ 强化券    ┆           ┆ 的抉择+15 ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ 装备强化  ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ 券"], …   ┆   ┆           ┆           ┆           ┆           │
│ 2668888  ┆ 赛丽亚的  ┆ Shining   ┆ {"[name]" ┆ … ┆ 0         ┆ potion    ┆           ┆ 消耗品    │
│          ┆ 援助      ┆ Hands of  ┆ : ["赛丽  ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆ Seria     ┆ 亚的援助" ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ ],        ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ "[name2…  ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [4]:
df.filter(pl.col('stackable_type') == '[etc]').sort(pl.col('sub_stackable_type'))

shape: (343, 11)
┌───────┬────────────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ id    ┆ name       ┆ name2      ┆ json       ┆ … ┆ sub_stack ┆ item_grou ┆ item_cate ┆ stackable │
│ ---   ┆ ---        ┆ ---        ┆ ---        ┆   ┆ able_type ┆ p_name    ┆ gory      ┆ _type_dis │
│ i64   ┆ str        ┆ str        ┆ str        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ play      │
│       ┆            ┆            ┆            ┆   ┆ i64       ┆ str       ┆ str       ┆ ---       │
│       ┆            ┆            ┆            ┆   ┆           ┆           ┆           ┆ str       │
╞═══════╪════════════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1     ┆ 复活币     ┆ Coin       ┆ {"[name]": ┆ … ┆ 0         ┆           ┆           ┆ 其他      │
│       ┆            ┆            ┆ ["复活币"] ┆   ┆           ┆           ┆           ┆           │
│       ┆            ┆            ┆ , "[name2] ┆   ┆           ┆           ┆           ┆           │
│       ┆            ┆            ┆ ":…        ┆   ┆           ┆           ┆           ┆           │
│ 2     ┆ 决斗胜点   ┆ PvP        ┆ {"[name]": ┆ … ┆ 0         ┆           ┆           ┆ 其他      │
│       ┆            ┆ Victory    ┆ ["决斗胜点 ┆   ┆           ┆           ┆           ┆           │
│       ┆            ┆ Point      ┆ "],        ┆   ┆           ┆           ┆           ┆           │
│       ┆            ┆            ┆ "[name2]"… ┆   ┆           ┆           ┆           ┆           │
│ 3     ┆ 遗忘河之水 ┆ The River  ┆ {"[name]": ┆ … ┆ 0         ┆           ┆           ┆ 其他      │
│       ┆            ┆ of Lethe   ┆ ["遗忘河之 ┆   ┆           ┆           ┆           ┆           │
│       ┆            ┆            ┆ 水"],      ┆   ┆           ┆           ┆           ┆           │
│       ┆            ┆            ┆ "[name2]…  ┆   ┆           ┆           ┆           ┆           │
│ 4     ┆ 普通金库   ┆ Basic      ┆ {"[name]": ┆ … ┆ 0         ┆           ┆           ┆ 其他      │
│       ┆            ┆ Store      ┆ ["普通金库 ┆   ┆           ┆           ┆           ┆           │
│       ┆            ┆            ┆ "],        ┆   ┆           ┆           ┆           ┆           │
│       ┆            ┆            ┆ "[name2]"… ┆   ┆           ┆           ┆           ┆           │
│ 5     ┆ 铜质金库升 ┆ Upgrade    ┆ {"[name]": ┆ … ┆ 0         ┆           ┆           ┆ 其他      │
│       ┆ 级工具     ┆ Kit For    ┆ ["铜质金库 ┆   ┆           ┆           ┆           ┆           │
│       ┆            ┆ Copper     ┆ 升级工具"] ┆   ┆           ┆           ┆           ┆           │
│       ┆            ┆ Store      ┆ , "[nam…   ┆   ┆           ┆           ┆           ┆           │
│ …     ┆ …          ┆ …          ┆ …          ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 1204  ┆ TP+1技能书 ┆ TP Book    ┆ {"[name]": ┆ … ┆ 8         ┆           ┆           ┆ 其他      │
│       ┆            ┆            ┆ ["TP+1技能 ┆   ┆           ┆           ┆           ┆           │
│       ┆            ┆            ┆ 书"],      ┆   ┆           ┆           ┆           ┆           │
│       ┆            ┆            ┆ "[name…    ┆   ┆           ┆           ┆           ┆           │
│ 1205  ┆ TP+5技能书 ┆ TP技能书   ┆ {"[name]": ┆ … ┆ 8         ┆           ┆           ┆ 其他      │
│       ┆            ┆            ┆ ["TP+5技能 ┆   ┆           ┆           ┆           ┆           │
│       ┆            ┆            ┆ 书"],      ┆   ┆           ┆           ┆           ┆           │
│       ┆            ┆            ┆ "[name…    ┆   ┆           ┆           ┆           ┆           │
│ 1206  ┆ TP初始化书 ┆ TP Reset   ┆ {"[name]": ┆ … ┆ 8         ┆           ┆           ┆ 其他      │
│       ┆            ┆ Book       ┆ ["TP初始化 ┆   ┆           ┆           ┆           ┆           │
│       ┆            ┆            ┆ 书"],      ┆   ┆           ┆           ┆           ┆           │
│       ┆            ┆            ┆ "[name2…   ┆   ┆           ┆           ┆           ┆           │
│ 1253  ┆ TP初始化书 ┆ TP Reset   ┆ {"[name]": ┆ … ┆ 8         ┆           ┆           ┆ 其他      │
│       ┆            ┆ Book       ┆ ["TP初始化 ┆   ┆           ┆           ┆           ┆           │
│       ┆            ┆            ┆ 书"],      ┆   ┆           ┆           ┆           ┆           │
│       ┆            ┆            ┆ "[name2…   ┆   ┆           ┆           ┆           ┆           │
│ 80003 ┆ SP+5技能书 ┆ Book of    ┆ {"[name]": ┆ … ┆ 8         ┆           ┆           ┆ 其他      │
│       ┆            ┆ Skill      ┆ ["SP+5技能 ┆   ┆           ┆           ┆           ┆           │
│       ┆            ┆            ┆ 书"],      ┆   ┆           ┆           ┆           ┆           │
│       ┆            ┆            ┆ "[name…    ┆   ┆           ┆           ┆           ┆           │
└───────┴────────────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [5]:
df.select(pl.col('stackable_type')).unique().sort(by=pl.col('stackable_type'))

shape: (38, 1)
┌───────────────────────┐
│ stackable_type        │
│ ---                   │
│ str                   │
╞═══════════════════════╡
│ [avatar emblem]       │
│ [booster random]      │
│ [booster selection]   │
│ [booster]             │
│ [cera booster]        │
│ …                     │
│ [unlimited waste]     │
│ [upgradable legacy]   │
│ [upgrade limit cube]  │
│ [usable cera package] │
│ [waste]               │
└───────────────────────┘

In [6]:
for it in df.select(pl.col('stackable_type')).to_series().unique().sort():
    print(f'df.filter(pl.col("stackable_type") == "{it}")')

df.filter(pl.col("stackable_type") == "[avatar emblem]")
df.filter(pl.col("stackable_type") == "[booster random]")
df.filter(pl.col("stackable_type") == "[booster selection]")
df.filter(pl.col("stackable_type") == "[booster]")
df.filter(pl.col("stackable_type") == "[cera booster]")
df.filter(pl.col("stackable_type") == "[cera package]")
df.filter(pl.col("stackable_type") == "[contract]")
df.filter(pl.col("stackable_type") == "[creature expitem]")
df.filter(pl.col("stackable_type") == "[creature]")
df.filter(pl.col("stackable_type") == "[disguise random]")
df.filter(pl.col("stackable_type") == "[disguise]")
df.filter(pl.col("stackable_type") == "[dye]")
df.filter(pl.col("stackable_type") == "[enchant waste]")
df.filter(pl.col("stackable_type") == "[etc]")
df.filter(pl.col("stackable_type") == "[expert town potion]")
df.filter(pl.col("stackable_type") == "[feed]")
df.filter(pl.col("stackable_type") == "[global effect]")
df.filter(pl.col("stackable_type") == "[legacy]")
df.filter(pl.col("stackable_type") == "[material expert job]")
df.filter(pl.col("stackable_type") == "[material]")
df.filter(pl.col("stackable_type") == "[multi upgradable legacy bonus cera]")
df.filter(pl.col("stackable_type") == "[multi upgradable legacy]")
df.filter(pl.col("stackable_type") == "[only effect]")
df.filter(pl.col("stackable_type") == "[quest receive]")
df.filter(pl.col("stackable_type") == "[quest]")
df.filter(pl.col("stackable_type") == "[recipe]")
df.filter(pl.col("stackable_type") == "[set]")
df.filter(pl.col("stackable_type") == "[stackable legacy]")
df.filter(pl.col("stackable_type") == "[teleport potion]")
df.filter(pl.col("stackable_type") == "[throw]")
df.filter(pl.col("stackable_type") == "[town and dungeon]")
df.filter(pl.col("stackable_type") == "[unlimited etc]")
df.filter(pl.col("stackable_type") == "[unlimited town and dungeon]")
df.filter(pl.col("stackable_type") == "[unlimited waste]")
df.filter(pl.col("stackable_type") == "[upgradable legacy]")
df.filter(pl.col("stackable_type") == "[upgrade limit cube]")
df.filter(pl.col("stackable_type") == "[usable cera package]")
df.filter(pl.col("stackable_type") == "[waste]")

In [7]:
df.filter(pl.col('stackable_type') == '[avatar emblem]')

shape: (595, 11)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ id      ┆ name       ┆ name2     ┆ json      ┆ … ┆ sub_stack ┆ item_grou ┆ item_cate ┆ stackable │
│ ---     ┆ ---        ┆ ---       ┆ ---       ┆   ┆ able_type ┆ p_name    ┆ gory      ┆ _type_dis │
│ i64     ┆ str        ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ play      │
│         ┆            ┆           ┆           ┆   ┆ i64       ┆ str       ┆ str       ┆ ---       │
│         ┆            ┆           ┆           ┆   ┆           ┆           ┆           ┆ str       │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2050    ┆ 红色徽章   ┆ Red       ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 时装徽章  │
│         ┆            ┆ Emblem    ┆ : ["红色  ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆ 徽章"],   ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆ "[name2]" ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆ …         ┆   ┆           ┆           ┆           ┆           │
│ 2051    ┆ 黄色徽章   ┆ Yellow    ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 时装徽章  │
│         ┆            ┆ Emblem    ┆ : ["黄色  ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆ 徽章"],   ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆ "[name2]" ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆ …         ┆   ┆           ┆           ┆           ┆           │
│ 2052    ┆ 绿色徽章   ┆ Green     ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 时装徽章  │
│         ┆            ┆ Emblem    ┆ : ["绿色  ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆ 徽章"],   ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆ "[name2]" ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆ …         ┆   ┆           ┆           ┆           ┆           │
│ 2053    ┆ 蓝色徽章   ┆ Blue      ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 时装徽章  │
│         ┆            ┆ Emblem    ┆ : ["蓝色  ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆ 徽章"],   ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆ "[name2]" ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆ …         ┆   ┆           ┆           ┆           ┆           │
│ 2054    ┆ 白金徽章   ┆ Platinum  ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 时装徽章  │
│         ┆            ┆ Emblem    ┆ : ["白金  ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆ 徽章"],   ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆ "[name2]" ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆ …         ┆   ┆           ┆           ┆           ┆           │
│ …       ┆ …          ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 2675882 ┆ 解放的决斗 ┆ Overclock ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 时装徽章  │
│         ┆ 徽章[攻速  ┆ Dual Embl ┆ : ["解放  ┆   ┆           ┆           ┆           ┆           │
│         ┆ + 命中率]  ┆ em“Attack ┆ 的决斗徽  ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆ S…        ┆ 章[攻速 + ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆ 命中率]…  ┆   ┆           ┆           ┆           ┆           │
│ 2675883 ┆ 解放的决斗 ┆ Overclock ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 时装徽章  │
│         ┆ 徽章[施放  ┆ Dual Embl ┆ : ["解放  ┆   ┆           ┆           ┆           ┆           │
│         ┆ 速度 +     ┆ em“Cast   ┆ 的决斗徽  ┆   ┆           ┆           ┆           ┆           │
│         ┆ 移动速度]  ┆ Spe…      ┆ 章[施放速 ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆ 度 +      ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆ 移动…     ┆   ┆           ┆           ┆           ┆           │
│ 2675884 ┆ 解放的决斗 ┆ Overclock ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 时装徽章  │
│         ┆ 徽章[施放  ┆ Dual Embl ┆ : ["解放  ┆   ┆           ┆           ┆           ┆           │
│         ┆ 速度 +     ┆ em“Cast   ┆ 的决斗徽  ┆   ┆           ┆           ┆           ┆           │
│         ┆ 命中率]    ┆ Spe…      ┆ 章[施放速 ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆ 度 +      ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆ 命中…     ┆   ┆           ┆           ┆           ┆           │
│ 2675885 ┆ 解放的决斗 ┆ Overclock ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 时装徽章  │
│         ┆ 徽章[硬直  ┆ Dual Embl ┆ : ["解放  ┆   ┆           ┆           ┆           ┆           │
│         ┆ +          ┆ em“Hit    ┆ 的决斗徽  ┆   ┆           ┆           ┆           ┆           │
│         ┆ 移动速度]  ┆ Reco…     ┆ 章[硬直 + ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆ 移动速度… ┆   ┆           ┆           ┆           ┆           │
│ 2675886 ┆ 解放的决斗 ┆ Overclock ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 时装徽章  │
│         ┆ 徽章[硬直  ┆ Dual Embl ┆ : ["解放  ┆   ┆           ┆           ┆           ┆           │
│         ┆ + 命中率]  ┆ em“Hit    ┆ 的决斗徽  ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆ Reco…     ┆ 章[硬直 + ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆ 命中率]…  ┆   ┆           ┆           ┆           ┆           │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [8]:
df.filter(pl.col('stackable_type') == '[booster random]')

shape: (5, 11)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ id      ┆ name       ┆ name2     ┆ json      ┆ … ┆ sub_stack ┆ item_grou ┆ item_cate ┆ stackable │
│ ---     ┆ ---        ┆ ---       ┆ ---       ┆   ┆ able_type ┆ p_name    ┆ gory      ┆ _type_dis │
│ i64     ┆ str        ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ play      │
│         ┆            ┆           ┆           ┆   ┆ i64       ┆ str       ┆ str       ┆ ---       │
│         ┆            ┆           ┆           ┆   ┆           ┆           ┆           ┆ str       │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 719     ┆ 09年DNF福  ┆ 09 DnF    ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 礼包      │
│         ┆ 袋         ┆ Lucky Bag ┆ : ["09年D ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆ NF福袋"], ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆ "[nam…    ┆   ┆           ┆           ┆           ┆           │
│ 957     ┆ 10年DNF福  ┆ 10DNFLuck ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 礼包      │
│         ┆ 袋         ┆ yBag      ┆ : ["10年D ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆ NF福袋"], ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆ "[nam…    ┆   ┆           ┆           ┆           ┆           │
│ 2660120 ┆ 11年DNF福  ┆           ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 礼包      │
│         ┆ 袋         ┆           ┆ : ["11年D ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆ NF福袋"], ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆ "[nam…    ┆   ┆           ┆           ┆           ┆           │
│ 2660538 ┆ 12年DNF福  ┆           ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 礼包      │
│         ┆ 袋         ┆           ┆ : ["12年D ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆ NF福袋"], ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆ "[nam…    ┆   ┆           ┆           ┆           ┆           │
│ 7528    ┆ TCG随机魔  ┆ Random    ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 礼包      │
│         ┆ 盒         ┆ Box of    ┆ : ["TCG随 ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆ TCG       ┆ 机魔盒"], ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆ "[name…   ┆   ┆           ┆           ┆           ┆           │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [9]:
df.filter(pl.col('stackable_type') == '[booster selection]')

shape: (114, 11)
┌──────────┬────────────┬───────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ id       ┆ name       ┆ name2 ┆ json       ┆ … ┆ sub_stacka ┆ item_group ┆ item_cate ┆ stackable │
│ ---      ┆ ---        ┆ ---   ┆ ---        ┆   ┆ ble_type   ┆ _name      ┆ gory      ┆ _type_dis │
│ i64      ┆ str        ┆ str   ┆ str        ┆   ┆ ---        ┆ ---        ┆ ---       ┆ play      │
│          ┆            ┆       ┆            ┆   ┆ i64        ┆ str        ┆ str       ┆ ---       │
│          ┆            ┆       ┆            ┆   ┆            ┆            ┆           ┆ str       │
╞══════════╪════════════╪═══════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 2660500  ┆ 狂想曲光环 ┆       ┆ {"[name]": ┆ … ┆ 0          ┆            ┆           ┆ 礼包      │
│          ┆ 装扮礼盒   ┆       ┆ ["狂想曲光 ┆   ┆            ┆            ┆           ┆           │
│          ┆            ┆       ┆ 环装扮礼盒 ┆   ┆            ┆            ┆           ┆           │
│          ┆            ┆       ┆ "], "[na…  ┆   ┆            ┆            ┆           ┆           │
│ 2660761  ┆ 阴森气息的 ┆       ┆ {"[name]": ┆ … ┆ 0          ┆            ┆           ┆ 礼包      │
│          ┆ 箱子       ┆       ┆ ["阴森气息 ┆   ┆            ┆            ┆           ┆           │
│          ┆            ┆       ┆ 的箱子"],  ┆   ┆            ┆            ┆           ┆           │
│          ┆            ┆       ┆ "[name…    ┆   ┆            ┆            ┆           ┆           │
│ 8382     ┆ 赛丽亚的2  ┆       ┆ {"[name]": ┆ … ┆ 0          ┆            ┆           ┆ 礼包      │
│          ┆ 期勇者套装 ┆       ┆ ["赛丽亚的 ┆   ┆            ┆            ┆           ┆           │
│          ┆ 礼盒       ┆       ┆ 2期勇者套  ┆   ┆            ┆            ┆           ┆           │
│          ┆ (防具)     ┆       ┆ 装礼盒     ┆   ┆            ┆            ┆           ┆           │
│          ┆            ┆       ┆ (防具)…    ┆   ┆            ┆            ┆           ┆           │
│ 8383     ┆ 赛丽亚的3  ┆       ┆ {"[name]": ┆ … ┆ 0          ┆            ┆           ┆ 礼包      │
│          ┆ 期勇者套装 ┆       ┆ ["赛丽亚的 ┆   ┆            ┆            ┆           ┆           │
│          ┆ 礼盒       ┆       ┆ 3期勇者套  ┆   ┆            ┆            ┆           ┆           │
│          ┆ (防具)     ┆       ┆ 装礼盒     ┆   ┆            ┆            ┆           ┆           │
│          ┆            ┆       ┆ (防具)…    ┆   ┆            ┆            ┆           ┆           │
│ 8384     ┆ 赛丽亚的65 ┆       ┆ {"[name]": ┆ … ┆ 0          ┆            ┆           ┆ 礼包      │
│          ┆ 级神器武器 ┆       ┆ ["赛丽亚的 ┆   ┆            ┆            ┆           ┆           │
│          ┆ 箱         ┆       ┆ 65级神器武 ┆   ┆            ┆            ┆           ┆           │
│          ┆            ┆       ┆ 器箱"], "… ┆   ┆            ┆            ┆           ┆           │
│ …        ┆ …          ┆ …     ┆ …          ┆ … ┆ …          ┆ …          ┆ …         ┆ …         │
│ 20250909 ┆ 光环装扮礼 ┆       ┆ {"[name]": ┆ … ┆ 0          ┆            ┆           ┆ 礼包      │
│          ┆ 盒         ┆       ┆ ["光环装扮 ┆   ┆            ┆            ┆           ┆           │
│          ┆            ┆       ┆ 礼盒"],    ┆   ┆            ┆            ┆           ┆           │
│          ┆            ┆       ┆ "[name2…   ┆   ┆            ┆            ┆           ┆           │
│ 21073002 ┆ 全职业自制 ┆       ┆ {"[name]": ┆ … ┆ 0          ┆            ┆           ┆ 礼包      │
│          ┆ 皮肤自选礼 ┆       ┆ ["全职业自 ┆   ┆            ┆            ┆           ┆           │
│          ┆ 盒         ┆       ┆ 制皮肤自选 ┆   ┆            ┆            ┆           ┆           │
│          ┆            ┆       ┆ 礼盒"],    ┆   ┆            ┆            ┆           ┆           │
│          ┆            ┆       ┆ "[…        ┆   ┆            ┆            ┆           ┆           │
│ 20250927 ┆ 祖传武器宝 ┆       ┆ {"[name]": ┆ … ┆ 0          ┆            ┆           ┆ 礼包      │
│          ┆ 箱         ┆       ┆ ["祖传武器 ┆   ┆            ┆            ┆           ┆           │
│          ┆            ┆       ┆ 宝箱"],    ┆   ┆            ┆            ┆           ┆           │
│          ┆            ┆       ┆ "[name2…   ┆   ┆            ┆            ┆           ┆           │
│ 83868    ┆ 有期限的稀 ┆       ┆ {"[name]": ┆ … ┆ 0          ┆            ┆           ┆ 礼包      │
│          ┆ 有克隆装扮 ┆       ┆ ["有期限的 ┆   ┆            ┆            ┆           ┆           │
│          ┆ 套装礼盒   ┆       ┆ 稀有克隆装 ┆   ┆            ┆            ┆           ┆           │
│          ┆            ┆       ┆ 扮套装礼盒 ┆   ┆            ┆            ┆           ┆           │
│          ┆            ┆       ┆ "],…       ┆   ┆            ┆            ┆           ┆           │
│ 2683028  ┆ Fate/Zero  ┆       ┆ {"[name]": ┆ … ┆ 0          ┆            ┆           ┆ 礼包      │
│          ┆ 诸王的命运 ┆       ┆ ["Fate/Zer ┆   ┆            ┆            ┆           ┆           │
│          ┆ 装扮       ┆       ┆ o诸王的命  ┆   ┆            ┆            ┆           ┆           │
│          ┆            ┆       ┆ 运装扮"…   ┆   ┆            ┆            ┆           ┆           │
└──────────┴────────────┴───────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

In [10]:
df.filter(pl.col('stackable_type') == '[booster]')

shape: (858, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id        ┆ name      ┆ name2     ┆ json      ┆ … ┆ sub_stack ┆ item_grou ┆ item_cate ┆ stackabl │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ able_type ┆ p_name    ┆ gory      ┆ e_type_d │
│ i64       ┆ str       ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ isplay   │
│           ┆           ┆           ┆           ┆   ┆ i64       ┆ str       ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 160       ┆ 冰霜幽暗  ┆ Random    ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 礼包     │
│           ┆ 密林      ┆ Creature  ┆ : ["冰霜  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Egg       ┆ 幽暗密林" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ],        ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2…  ┆   ┆           ┆           ┆           ┆          │
│ 189       ┆ 逐梦勇士  ┆ Dream     ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 礼包     │
│           ┆ 徽章礼盒  ┆ Fighter   ┆ : ["逐梦  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Emblem    ┆ 勇士徽章  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Box       ┆ 礼盒"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[nam…    ┆   ┆           ┆           ┆           ┆          │
│ 718       ┆ 新年祝福  ┆ Blessed   ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 礼包     │
│           ┆ 的箱子    ┆ Box of    ┆ : ["新年  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ New Year  ┆ 祝福的箱  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 子"],     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name…   ┆   ┆           ┆           ┆           ┆          │
│ 758       ┆ 五月的婚  ┆ Best Man[ ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 礼包     │
│           ┆ 礼称号包  ┆ Bridesmai ┆ : ["五月  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ d] Box of ┆ 的婚礼称  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Ma…       ┆ 号包"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[nam…    ┆   ┆           ┆           ┆           ┆          │
│ 759       ┆ 土罐充满  ┆ Danjin's  ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 礼包     │
│           ┆ 诚意的礼  ┆ Thoughtfu ┆ : ["土罐  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 物        ┆ l Gift    ┆ 充满诚意  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 的礼物"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[na…     ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 690017000 ┆ 黑钻贵族  ┆ Black     ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 礼包     │
│           ┆ (1天)     ┆ drill ari ┆ : ["黑钻  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ stocrat   ┆ 贵族      ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ (1天)"],  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[na…     ┆   ┆           ┆           ┆           ┆          │
│ 690017001 ┆ 黑钻贵族  ┆ Black     ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 礼包     │
│           ┆ (3天)     ┆ drill ari ┆ : ["黑钻  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ stocrat   ┆ 贵族      ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ (3天)"],  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[na…     ┆   ┆           ┆           ┆           ┆          │
│ 690017002 ┆ 黑钻贵族  ┆ Black     ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 礼包     │
│           ┆ (7天)     ┆ drill ari ┆ : ["黑钻  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ stocrat   ┆ 贵族      ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ (7天)"],  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[na…     ┆   ┆           ┆           ┆           ┆          │
│ 690017003 ┆ 黑钻贵族  ┆ Black     ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 礼包     │
│           ┆ (15天)    ┆ drill ari ┆ : ["黑钻  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ stocrat   ┆ 贵族      ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ (15天)"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[n…      ┆   ┆           ┆           ┆           ┆          │
│ 690017004 ┆ 黑钻贵族  ┆ Black     ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 礼包     │
│           ┆ (30天)    ┆ drill ari ┆ : ["黑钻  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ stocrat   ┆ 贵族      ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ (30天)"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[n…      ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [11]:
df.filter(pl.col('stackable_type') == '[cera booster]')

shape: (155, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id        ┆ name      ┆ name2     ┆ json      ┆ … ┆ sub_stack ┆ item_grou ┆ item_cate ┆ stackabl │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ able_type ┆ p_name    ┆ gory      ┆ e_type_d │
│ i64       ┆ str       ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ isplay   │
│           ┆           ┆           ┆           ┆   ┆ i64       ┆ str       ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 38        ┆ 鬼剑士福  ┆ Lucky Bag ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 礼包     │
│           ┆ 包        ┆ of        ┆ : ["鬼剑  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Swordman  ┆ 士福包"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2]… ┆   ┆           ┆           ┆           ┆          │
│ 39        ┆ 格斗家福  ┆ Lucky Bag ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 礼包     │
│           ┆ 包        ┆ of        ┆ : ["格斗  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Fighter   ┆ 家福包"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2]… ┆   ┆           ┆           ┆           ┆          │
│ 40        ┆ 神枪手福  ┆ Lucky Bag ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 礼包     │
│           ┆ 包        ┆ of Gunner ┆ : ["神枪  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 手福包"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2]… ┆   ┆           ┆           ┆           ┆          │
│ 41        ┆ 魔法师福  ┆ Lucky Bag ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 礼包     │
│           ┆ 包        ┆ of Mage   ┆ : ["魔法  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 师福包"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2]… ┆   ┆           ┆           ┆           ┆          │
│ 52        ┆ 野生力量  ┆ Wild      ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 礼包     │
│           ┆ 套装 (熊) ┆ Avatar    ┆ : ["野生  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Set       ┆ 力量套装  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ (Bear)    ┆ (熊)"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[n…      ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 10000052  ┆ 协作支援  ┆           ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 礼包     │
│           ┆ 礼包3     ┆           ┆ : ["协作  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 支援礼包3 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "],       ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name…   ┆   ┆           ┆           ┆           ┆          │
│ 10000116  ┆ 缔造者装  ┆           ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 礼包     │
│           ┆ 扮礼包4   ┆           ┆ : ["缔造  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 者装扮礼  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 包4"],    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[nam…    ┆   ┆           ┆           ┆           ┆          │
│ 10000191  ┆ 神秘的宠  ┆           ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 礼包     │
│           ┆ 物饲料口  ┆           ┆ : ["神秘  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 袋        ┆           ┆ 的宠物饲  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 料口袋"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[na…     ┆   ┆           ┆           ┆           ┆          │
│ 10000537  ┆ 7期稀有装 ┆           ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 礼包     │
│           ┆ 扮套装礼  ┆           ┆ : ["7期稀 ┆   ┆           ┆           ┆           ┆          │
│           ┆ 盒 (不可  ┆           ┆ 有装扮套  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 交易)     ┆           ┆ 装礼盒    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ (不可交易 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ )…        ┆   ┆           ┆           ┆           ┆          │
│ 690000120 ┆ 成长之契  ┆           ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 礼包     │
│           ┆ 约产包(15 ┆           ┆ : ["成长  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 日)       ┆           ┆ 之契约产  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 包(15日)" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ], "…     ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [12]:
df.filter(pl.col('stackable_type') == '[cera package]')

shape: (495, 11)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ id       ┆ name      ┆ name2     ┆ json      ┆ … ┆ sub_stack ┆ item_grou ┆ item_cate ┆ stackable │
│ ---      ┆ ---       ┆ ---       ┆ ---       ┆   ┆ able_type ┆ p_name    ┆ gory      ┆ _type_dis │
│ i64      ┆ str       ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ play      │
│          ┆           ┆           ┆           ┆   ┆ i64       ┆ str       ┆ str       ┆ ---       │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ str       │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 27       ┆ 挑战者包  ┆ Challenge ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 礼包      │
│          ┆ 裹        ┆ r Package ┆ : ["挑战  ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ 者包裹"], ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ "[name2]… ┆   ┆           ┆           ┆           ┆           │
│ 49       ┆ 达人之契  ┆ Contract  ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 礼包      │
│          ┆ 约        ┆ of Expert ┆ : ["达人  ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ 之契约"], ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ "[name2]… ┆   ┆           ┆           ┆           ┆           │
│ 84       ┆ 怪物套礼  ┆ Monster   ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 礼包      │
│          ┆ 包[鬼剑士 ┆ Package   ┆ : ["怪物  ┆   ┆           ┆           ┆           ┆           │
│          ┆ ]         ┆           ┆ 套礼包[鬼 ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ 剑士]"],  ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ "[n…      ┆   ┆           ┆           ┆           ┆           │
│ 87       ┆ 怪物套礼  ┆ Monster   ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 礼包      │
│          ┆ 包[格斗家 ┆ Package   ┆ : ["怪物  ┆   ┆           ┆           ┆           ┆           │
│          ┆ (女)]     ┆           ┆ 套礼包[格 ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ 斗家(女)] ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ "], …     ┆   ┆           ┆           ┆           ┆           │
│ 90       ┆ 怪物套礼  ┆ Monster   ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 礼包      │
│          ┆ 包[神枪手 ┆ Package   ┆ : ["怪物  ┆   ┆           ┆           ┆           ┆           │
│          ┆ (男)]     ┆           ┆ 套礼包[神 ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ 枪手(男)] ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ "], …     ┆   ┆           ┆           ┆           ┆           │
│ …        ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 10007883 ┆ 萌萌动物  ┆           ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 礼包      │
│          ┆ 园礼包2   ┆           ┆ : ["萌萌  ┆   ┆           ┆           ┆           ┆           │
│          ┆ (黑暗武士 ┆           ┆ 动物园礼  ┆   ┆           ┆           ┆           ┆           │
│          ┆ )         ┆           ┆ 包2 (黑暗 ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ 武士)"]…  ┆   ┆           ┆           ┆           ┆           │
│ 10007884 ┆ 萌萌动物  ┆           ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 礼包      │
│          ┆ 园礼包3   ┆           ┆ : ["萌萌  ┆   ┆           ┆           ┆           ┆           │
│          ┆ (黑暗武士 ┆           ┆ 动物园礼  ┆   ┆           ┆           ┆           ┆           │
│          ┆ )         ┆           ┆ 包3 (黑暗 ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ 武士)"]…  ┆   ┆           ┆           ┆           ┆           │
│ 10007885 ┆ 萌萌动物  ┆           ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 礼包      │
│          ┆ 园礼包1   ┆           ┆ : ["萌萌  ┆   ┆           ┆           ┆           ┆           │
│          ┆ (缔造者)  ┆           ┆ 动物园礼  ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ 包1 (缔造 ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ 者)"],…   ┆   ┆           ┆           ┆           ┆           │
│ 10007886 ┆ 萌萌动物  ┆           ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 礼包      │
│          ┆ 园礼包2   ┆           ┆ : ["萌萌  ┆   ┆           ┆           ┆           ┆           │
│          ┆ (缔造者)  ┆           ┆ 动物园礼  ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ 包2 (缔造 ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ 者)"],…   ┆   ┆           ┆           ┆           ┆           │
│ 10007887 ┆ 萌萌动物  ┆           ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 礼包      │
│          ┆ 园礼包3   ┆           ┆ : ["萌萌  ┆   ┆           ┆           ┆           ┆           │
│          ┆ (缔造者)  ┆           ┆ 动物园礼  ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ 包3 (缔造 ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ 者)"],…   ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [13]:
df.filter(pl.col('stackable_type') == '[contract]')

shape: (26, 11)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ id      ┆ name       ┆ name2     ┆ json      ┆ … ┆ sub_stack ┆ item_grou ┆ item_cate ┆ stackable │
│ ---     ┆ ---        ┆ ---       ┆ ---       ┆   ┆ able_type ┆ p_name    ┆ gory      ┆ _type_dis │
│ i64     ┆ str        ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ play      │
│         ┆            ┆           ┆           ┆   ┆ i64       ┆ str       ┆ str       ┆ ---       │
│         ┆            ┆           ┆           ┆   ┆           ┆           ┆           ┆ str       │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 820     ┆ 遗忘之契约 ┆ 5 Days    ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 契约      │
│         ┆ (5天)      ┆ Contract  ┆ : ["遗忘  ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆ of Lethe  ┆ 之契约    ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆ (5天)"],  ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆ "[n…      ┆   ┆           ┆           ┆           ┆           │
│ 901     ┆ 拍卖场优待 ┆           ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 契约      │
│         ┆ 券         ┆           ┆ : ["拍卖  ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆ 场优待券" ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆ ],        ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆ "[name2…  ┆   ┆           ┆           ┆           ┆           │
│ 917     ┆ 遗忘之契约 ┆ 7 Days    ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 契约      │
│         ┆ (7天)      ┆ Contract  ┆ : ["遗忘  ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆ of Lethe  ┆ 之契约    ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆ (7天)"],  ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆ "[n…      ┆   ┆           ┆           ┆           ┆           │
│ 920     ┆ 遗忘之契约 ┆ 7 Days    ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 契约      │
│         ┆ (7天)      ┆ Contract  ┆ : ["遗忘  ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆ of Lethe  ┆ 之契约    ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆ (7天)"],  ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆ "[n…      ┆   ┆           ┆           ┆           ┆           │
│ 2660401 ┆ 遗忘河契约 ┆           ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 契约      │
│         ┆ 3天        ┆           ┆ : ["遗忘  ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆ 河契约    ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆ 3天"],    ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆ "[nam…    ┆   ┆           ┆           ┆           ┆           │
│ …       ┆ …          ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 3017951 ┆ 黑钻贵族   ┆ Black     ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 契约      │
│         ┆ (1天)      ┆ drill ari ┆ : ["黑钻  ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆ stocrat   ┆ 贵族      ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆ (1天)"],  ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆ "[na…     ┆   ┆           ┆           ┆           ┆           │
│ 3017952 ┆ 黑钻贵族   ┆ Black     ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 契约      │
│         ┆ (3天)      ┆ drill ari ┆ : ["黑钻  ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆ stocrat   ┆ 贵族      ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆ (3天)"],  ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆ "[na…     ┆   ┆           ┆           ┆           ┆           │
│ 3017953 ┆ 黑钻贵族   ┆ Black     ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 契约      │
│         ┆ (7天)      ┆ drill ari ┆ : ["黑钻  ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆ stocrat   ┆ 贵族      ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆ (7天)"],  ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆ "[na…     ┆   ┆           ┆           ┆           ┆           │
│ 3017954 ┆ 黑钻贵族   ┆ Black     ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 契约      │
│         ┆ (15天)     ┆ drill ari ┆ : ["黑钻  ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆ stocrat   ┆ 贵族      ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆ (15天)"], ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆ "[n…      ┆   ┆           ┆           ┆           ┆           │
│ 3017955 ┆ 黑钻贵族   ┆ Black     ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 契约      │
│         ┆ (30天)     ┆ drill ari ┆ : ["黑钻  ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆ stocrat   ┆ 贵族      ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆ (30天)"], ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆ "[n…      ┆   ┆           ┆           ┆           ┆           │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [14]:
df.filter(pl.col('stackable_type') == '[creature expitem]')

shape: (4, 11)
┌──────────┬────────────┬───────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ id       ┆ name       ┆ name2 ┆ json       ┆ … ┆ sub_stacka ┆ item_group ┆ item_cate ┆ stackable │
│ ---      ┆ ---        ┆ ---   ┆ ---        ┆   ┆ ble_type   ┆ _name      ┆ gory      ┆ _type_dis │
│ i64      ┆ str        ┆ str   ┆ str        ┆   ┆ ---        ┆ ---        ┆ ---       ┆ play      │
│          ┆            ┆       ┆            ┆   ┆ i64        ┆ str        ┆ str       ┆ ---       │
│          ┆            ┆       ┆            ┆   ┆            ┆            ┆           ┆ str       │
╞══════════╪════════════╪═══════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 8472     ┆            ┆       ┆ {"[name]": ┆ … ┆ 0          ┆            ┆           ┆ 宠物道具  │
│          ┆            ┆       ┆ [""],      ┆   ┆            ┆            ┆           ┆           │
│          ┆            ┆       ┆ "[name2]": ┆   ┆            ┆            ┆           ┆           │
│          ┆            ┆       ┆ ["…        ┆   ┆            ┆            ┆           ┆           │
│ 8473     ┆            ┆       ┆ {"[name]": ┆ … ┆ 0          ┆            ┆           ┆ 宠物道具  │
│          ┆            ┆       ┆ [""],      ┆   ┆            ┆            ┆           ┆           │
│          ┆            ┆       ┆ "[name2]": ┆   ┆            ┆            ┆           ┆           │
│          ┆            ┆       ┆ ["…        ┆   ┆            ┆            ┆           ┆           │
│ 10000002 ┆ 菠菜味饼干 ┆       ┆ {"[name]": ┆ … ┆ 0          ┆            ┆           ┆ 宠物道具  │
│          ┆            ┆       ┆ ["菠菜味饼 ┆   ┆            ┆            ┆           ┆           │
│          ┆            ┆       ┆ 干"],      ┆   ┆            ┆            ┆           ┆           │
│          ┆            ┆       ┆ "[name2]…  ┆   ┆            ┆            ┆           ┆           │
│ 10000003 ┆ 贝贝食物   ┆       ┆ {"[name]": ┆ … ┆ 0          ┆            ┆           ┆ 宠物道具  │
│          ┆            ┆       ┆ ["贝贝食物 ┆   ┆            ┆            ┆           ┆           │
│          ┆            ┆       ┆ "],        ┆   ┆            ┆            ┆           ┆           │
│          ┆            ┆       ┆ "[name2]"… ┆   ┆            ┆            ┆           ┆           │
└──────────┴────────────┴───────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

In [15]:
df.filter(pl.col('stackable_type') == '[creature]')

shape: (2, 11)
┌─────┬────────────┬────────────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ id  ┆ name       ┆ name2      ┆ json       ┆ … ┆ sub_stacka ┆ item_group ┆ item_cate ┆ stackable │
│ --- ┆ ---        ┆ ---        ┆ ---        ┆   ┆ ble_type   ┆ _name      ┆ gory      ┆ _type_dis │
│ i64 ┆ str        ┆ str        ┆ str        ┆   ┆ ---        ┆ ---        ┆ ---       ┆ play      │
│     ┆            ┆            ┆            ┆   ┆ i64        ┆ str        ┆ str       ┆ ---       │
│     ┆            ┆            ┆            ┆   ┆            ┆            ┆           ┆ str       │
╞═════╪════════════╪════════════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 25  ┆ 宠物换名卡 ┆ Rename     ┆ {"[name]": ┆ … ┆ 1          ┆            ┆           ┆ 宠物道具  │
│     ┆            ┆ Card       ┆ ["宠物换名 ┆   ┆            ┆            ┆           ┆           │
│     ┆            ┆            ┆ 卡"],      ┆   ┆            ┆            ┆           ┆           │
│     ┆            ┆            ┆ "[name2]…  ┆   ┆            ┆            ┆           ┆           │
│ 26  ┆ 宠物权限书 ┆ Creature   ┆ {"[name]": ┆ … ┆ 1          ┆            ┆           ┆ 宠物道具  │
│     ┆            ┆ Maintenanc ┆ ["宠物权限 ┆   ┆            ┆            ┆           ┆           │
│     ┆            ┆ e          ┆ 书"],      ┆   ┆            ┆            ┆           ┆           │
│     ┆            ┆ Authoriza… ┆ "[name2]…  ┆   ┆            ┆            ┆           ┆           │
└─────┴────────────┴────────────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

In [16]:
df.filter(pl.col('stackable_type') == '[disguise random]')

shape: (1, 11)
┌───────────┬────────────┬───────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ id        ┆ name       ┆ name2 ┆ json       ┆ … ┆ sub_stacka ┆ item_grou ┆ item_cate ┆ stackable │
│ ---       ┆ ---        ┆ ---   ┆ ---        ┆   ┆ ble_type   ┆ p_name    ┆ gory      ┆ _type_dis │
│ i64       ┆ str        ┆ str   ┆ str        ┆   ┆ ---        ┆ ---       ┆ ---       ┆ play      │
│           ┆            ┆       ┆            ┆   ┆ i64        ┆ str       ┆ str       ┆ ---       │
│           ┆            ┆       ┆            ┆   ┆            ┆           ┆           ┆ str       │
╞═══════════╪════════════╪═══════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 690000779 ┆ 万圣节服装 ┆       ┆ {"[name]": ┆ … ┆ 0          ┆           ┆           ┆ 变身道具  │
│           ┆ 药水       ┆       ┆ ["万圣节服 ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ 装药水"],  ┆   ┆            ┆           ┆           ┆           │
│           ┆            ┆       ┆ "[expl…    ┆   ┆            ┆           ┆           ┆           │
└───────────┴────────────┴───────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [17]:
df.filter(pl.col('stackable_type') == '[disguise]')

shape: (37, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id        ┆ name      ┆ name2     ┆ json      ┆ … ┆ sub_stack ┆ item_grou ┆ item_cate ┆ stackabl │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ able_type ┆ p_name    ┆ gory      ┆ e_type_d │
│ i64       ┆ str       ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ isplay   │
│           ┆           ┆           ┆           ┆   ┆ i64       ┆ str       ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 7432      ┆ COS变装玩 ┆ Costume   ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 变身道具 │
│           ┆ 具 (凯丽) ┆ Toy(Kiri) ┆ : ["COS变 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 装玩具    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ (凯丽)"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "…        ┆   ┆           ┆           ┆           ┆          │
│ 7433      ┆ COS变装玩 ┆ Costume   ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 变身道具 │
│           ┆ 具 (莎兰) ┆ Toy(Shara ┆ : ["COS变 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ n)        ┆ 装玩具    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ (莎兰)"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "…        ┆   ┆           ┆           ┆           ┆          │
│ 7434      ┆ COS变装玩 ┆ Costume   ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 变身道具 │
│           ┆ 具 (风振) ┆ Toy(Poong ┆ : ["COS变 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ jin)      ┆ 装玩具    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ (风振)"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "…        ┆   ┆           ┆           ┆           ┆          │
│ 7435      ┆ COS变装玩 ┆ Costume   ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 变身道具 │
│           ┆ 具        ┆ Toy(GSD)  ┆ : ["COS变 ┆   ┆           ┆           ┆           ┆          │
│           ┆ (G.S.D)   ┆           ┆ 装玩具    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ (G.S.D)"] ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆          │
│ 7436      ┆ COS变装玩 ┆ Costume   ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 变身道具 │
│           ┆ 具 (歌兰  ┆ Toy(Grand ┆ : ["COS变 ┆   ┆           ┆           ┆           ┆          │
│           ┆ 蒂斯)     ┆ is)       ┆ 装玩具    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ (歌兰蒂斯 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ )"],…     ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 690000452 ┆ 黄金鹅的  ┆ feather   ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 变身道具 │
│           ┆ 羽毛      ┆           ┆ : ["黄金  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 鹅的羽毛" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ],        ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2…  ┆   ┆           ┆           ┆           ┆          │
│ 690000693 ┆ 烤肉服[培 ┆ grill     ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 变身道具 │
│           ┆ 根卷]     ┆           ┆ : ["烤肉  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 服[培根卷 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ]"],      ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[nam…    ┆   ┆           ┆           ┆           ┆          │
│ 690000694 ┆ 烤肉服[烤 ┆ grill     ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 变身道具 │
│           ┆ 明虾]     ┆           ┆ : ["烤肉  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 服[烤明虾 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ]"],      ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[nam…    ┆   ┆           ┆           ┆           ┆          │
│ 690000695 ┆ 烤肉服[羊 ┆ grill     ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 变身道具 │
│           ┆ 肉串]     ┆           ┆ : ["烤肉  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 服[羊肉串 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ]"],      ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[nam…    ┆   ┆           ┆           ┆           ┆          │
│ 690000696 ┆ 烤肉服[烤 ┆ grill     ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 变身道具 │
│           ┆ 玉米]     ┆           ┆ : ["烤肉  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 服[烤玉米 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ]"],      ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[nam…    ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [18]:
df.filter(pl.col('stackable_type') == '[dye]')

shape: (36, 11)
┌──────────┬────────────┬───────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ id       ┆ name       ┆ name2 ┆ json       ┆ … ┆ sub_stacka ┆ item_group ┆ item_cate ┆ stackable │
│ ---      ┆ ---        ┆ ---   ┆ ---        ┆   ┆ ble_type   ┆ _name      ┆ gory      ┆ _type_dis │
│ i64      ┆ str        ┆ str   ┆ str        ┆   ┆ ---        ┆ ---        ┆ ---       ┆ play      │
│          ┆            ┆       ┆            ┆   ┆ i64        ┆ str        ┆ str       ┆ ---       │
│          ┆            ┆       ┆            ┆   ┆            ┆            ┆           ┆ str       │
╞══════════╪════════════╪═══════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 2660674  ┆ 洗色剂     ┆       ┆ {"[name]": ┆ … ┆ 0          ┆            ┆           ┆ 染色剂    │
│          ┆            ┆       ┆ ["洗色剂"] ┆   ┆            ┆            ┆           ┆           │
│          ┆            ┆       ┆ , "[name2] ┆   ┆            ┆            ┆           ┆           │
│          ┆            ┆       ┆ ":…        ┆   ┆            ┆            ┆           ┆           │
│ 2660675  ┆ 珊瑚色染色 ┆       ┆ {"[name]": ┆ … ┆ 0          ┆            ┆           ┆ 染色剂    │
│          ┆ 剂         ┆       ┆ ["珊瑚色染 ┆   ┆            ┆            ┆           ┆           │
│          ┆            ┆       ┆ 色剂"],    ┆   ┆            ┆            ┆           ┆           │
│          ┆            ┆       ┆ "[name2…   ┆   ┆            ┆            ┆           ┆           │
│ 2660676  ┆ 杏黄色染色 ┆       ┆ {"[name]": ┆ … ┆ 0          ┆            ┆           ┆ 染色剂    │
│          ┆ 剂         ┆       ┆ ["杏黄色染 ┆   ┆            ┆            ┆           ┆           │
│          ┆            ┆       ┆ 色剂"],    ┆   ┆            ┆            ┆           ┆           │
│          ┆            ┆       ┆ "[name2…   ┆   ┆            ┆            ┆           ┆           │
│ 2660677  ┆ 土黄色染色 ┆       ┆ {"[name]": ┆ … ┆ 0          ┆            ┆           ┆ 染色剂    │
│          ┆ 剂         ┆       ┆ ["土黄色染 ┆   ┆            ┆            ┆           ┆           │
│          ┆            ┆       ┆ 色剂"],    ┆   ┆            ┆            ┆           ┆           │
│          ┆            ┆       ┆ "[name2…   ┆   ┆            ┆            ┆           ┆           │
│ 2660678  ┆ 绿色染色剂 ┆       ┆ {"[name]": ┆ … ┆ 0          ┆            ┆           ┆ 染色剂    │
│          ┆            ┆       ┆ ["绿色染色 ┆   ┆            ┆            ┆           ┆           │
│          ┆            ┆       ┆ 剂"],      ┆   ┆            ┆            ┆           ┆           │
│          ┆            ┆       ┆ "[name2]…  ┆   ┆            ┆            ┆           ┆           │
│ …        ┆ …          ┆ …     ┆ …          ┆ … ┆ …          ┆ …          ┆ …         ┆ …         │
│ 10000199 ┆ 军绿色染色 ┆       ┆ {"[name]": ┆ … ┆ 0          ┆            ┆           ┆ 染色剂    │
│          ┆ 剂         ┆       ┆ ["军绿色染 ┆   ┆            ┆            ┆           ┆           │
│          ┆            ┆       ┆ 色剂"],    ┆   ┆            ┆            ┆           ┆           │
│          ┆            ┆       ┆ "[name2…   ┆   ┆            ┆            ┆           ┆           │
│ 10000200 ┆ 浅绿色染色 ┆       ┆ {"[name]": ┆ … ┆ 0          ┆            ┆           ┆ 染色剂    │
│          ┆ 剂         ┆       ┆ ["浅绿色染 ┆   ┆            ┆            ┆           ┆           │
│          ┆            ┆       ┆ 色剂"],    ┆   ┆            ┆            ┆           ┆           │
│          ┆            ┆       ┆ "[name2…   ┆   ┆            ┆            ┆           ┆           │
│ 10000201 ┆ 柠檬色染色 ┆       ┆ {"[name]": ┆ … ┆ 0          ┆            ┆           ┆ 染色剂    │
│          ┆ 剂         ┆       ┆ ["柠檬色染 ┆   ┆            ┆            ┆           ┆           │
│          ┆            ┆       ┆ 色剂"],    ┆   ┆            ┆            ┆           ┆           │
│          ┆            ┆       ┆ "[name2…   ┆   ┆            ┆            ┆           ┆           │
│ 10000202 ┆ 浅灰色染色 ┆       ┆ {"[name]": ┆ … ┆ 0          ┆            ┆           ┆ 染色剂    │
│          ┆ 剂         ┆       ┆ ["浅灰色染 ┆   ┆            ┆            ┆           ┆           │
│          ┆            ┆       ┆ 色剂"],    ┆   ┆            ┆            ┆           ┆           │
│          ┆            ┆       ┆ "[name2…   ┆   ┆            ┆            ┆           ┆           │
│ 10000203 ┆ 夜空色染色 ┆       ┆ {"[name]": ┆ … ┆ 0          ┆            ┆           ┆ 染色剂    │
│          ┆ 剂         ┆       ┆ ["夜空色染 ┆   ┆            ┆            ┆           ┆           │
│          ┆            ┆       ┆ 色剂"],    ┆   ┆            ┆            ┆           ┆           │
│          ┆            ┆       ┆ "[name2…   ┆   ┆            ┆            ┆           ┆           │
└──────────┴────────────┴───────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

In [19]:
df.filter(pl.col('stackable_type') == '[enchant waste]')

shape: (261, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id        ┆ name      ┆ name2     ┆ json      ┆ … ┆ sub_stack ┆ item_grou ┆ item_cate ┆ stackabl │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ able_type ┆ p_name    ┆ gory      ┆ e_type_d │
│ i64       ┆ str       ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ isplay   │
│           ┆           ┆           ┆           ┆   ┆ i64       ┆ str       ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2600294   ┆ 光之城主  ┆ Sieghart  ┆ {"[name]" ┆ … ┆ 0         ┆ potion    ┆           ┆ 附魔宝珠 │
│           ┆ 赛格哈特  ┆ : Lord of ┆ : ["光之  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 的宝珠    ┆ Light's   ┆ 城主赛格  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Cas…      ┆ 哈特的宝  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 珠"], "[… ┆   ┆           ┆           ┆           ┆          │
│ 2600295   ┆ 长脚罗特  ┆ Lotus of  ┆ {"[name]" ┆ … ┆ 0         ┆ potion    ┆           ┆ 附魔宝珠 │
│           ┆ 斯的宝珠  ┆ Long Foot ┆ : ["长脚  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Bead      ┆ 罗特斯的  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 宝珠"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[nam…    ┆   ┆           ┆           ┆           ┆          │
│ 2600296   ┆ 邪龙斯皮  ┆ Head of   ┆ {"[name]" ┆ … ┆ 0         ┆ potion    ┆           ┆ 附魔宝珠 │
│           ┆ 兹的宝珠  ┆ Spirrazzi ┆ : ["邪龙  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ : Dead    ┆ 斯皮兹的  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Drago…    ┆ 宝珠"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[nam…    ┆   ┆           ┆           ┆           ┆          │
│ 2600297   ┆ 魔笛使者  ┆ Peter The ┆ {"[name]" ┆ … ┆ 0         ┆ potion    ┆           ┆ 附魔宝珠 │
│           ┆ 皮特的宝  ┆ Piper     ┆ : ["魔笛  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 珠        ┆ Bead      ┆ 使者皮特  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 的宝珠"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[na…     ┆   ┆           ┆           ┆           ┆          │
│ 2600298   ┆ 烈焰彼诺  ┆ Vinoshu   ┆ {"[name]" ┆ … ┆ 0         ┆ potion    ┆           ┆ 附魔宝珠 │
│           ┆ 修的宝珠  ┆ of Flame  ┆ : ["烈焰  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Bead      ┆ 彼诺修的  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 宝珠"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[nam…    ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 690000298 ┆ 勇者的祝  ┆ summer    ┆ {"[name]" ┆ … ┆ 0         ┆ potion    ┆           ┆ 附魔宝珠 │
│           ┆ 福        ┆ bead      ┆ : ["勇者  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 的祝福"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2]… ┆   ┆           ┆           ┆           ┆          │
│ 10015655  ┆ 藏有女魔  ┆           ┆ {"[name]" ┆ … ┆ 0         ┆ potion    ┆           ┆ 附魔宝珠 │
│           ┆ 法师佣兵  ┆           ┆ : ["藏有  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 力量的宝  ┆           ┆ 女魔法师  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 珠        ┆           ┆ 佣兵力量  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 的宝珠"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆          │
│ 10015656  ┆ 藏有格斗  ┆           ┆ {"[name]" ┆ … ┆ 0         ┆ potion    ┆           ┆ 附魔宝珠 │
│           ┆ 家佣兵力  ┆           ┆ : ["藏有  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 量的宝珠  ┆           ┆ 格斗家佣  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 兵力量的  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 宝珠"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "…        ┆   ┆           ┆           ┆           ┆          │
│ 10015657  ┆ 藏有女枪  ┆           ┆ {"[name]" ┆ … ┆ 0         ┆ potion    ┆           ┆ 附魔宝珠 │
│           ┆ 手佣兵力  ┆           ┆ : ["藏有  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 量的宝珠  ┆           ┆ 女枪手佣  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 兵力量的  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 宝珠"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "…        ┆   ┆           ┆           ┆           ┆          │
│ 10015658  ┆ 藏有暗夜  ┆           ┆ {"[name]" ┆ … ┆ 0         ┆ potion    ┆           ┆ 附魔宝珠 │
│           ┆ 使者佣兵  ┆           ┆ : ["藏有  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 力量的宝  ┆           ┆ 暗夜使者  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 珠        ┆           ┆ 佣兵力量  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 的宝珠"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [20]:
df.filter(pl.col('stackable_type') == '[etc]')

shape: (343, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id        ┆ name      ┆ name2     ┆ json      ┆ … ┆ sub_stack ┆ item_grou ┆ item_cate ┆ stackabl │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ able_type ┆ p_name    ┆ gory      ┆ e_type_d │
│ i64       ┆ str       ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ isplay   │
│           ┆           ┆           ┆           ┆   ┆ i64       ┆ str       ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1         ┆ 复活币    ┆ Coin      ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 其他     │
│           ┆           ┆           ┆ : ["复活  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 币"], "[n ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ame2]":…  ┆   ┆           ┆           ┆           ┆          │
│ 2         ┆ 决斗胜点  ┆ PvP       ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 其他     │
│           ┆           ┆ Victory   ┆ : ["决斗  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Point     ┆ 胜点"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2]" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆          │
│ 3         ┆ 遗忘河之  ┆ The River ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 其他     │
│           ┆ 水        ┆ of Lethe  ┆ : ["遗忘  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 河之水"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2]… ┆   ┆           ┆           ┆           ┆          │
│ 4         ┆ 普通金库  ┆ Basic     ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 其他     │
│           ┆           ┆ Store     ┆ : ["普通  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 金库"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2]" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆          │
│ 5         ┆ 铜质金库  ┆ Upgrade   ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 其他     │
│           ┆ 升级工具  ┆ Kit For   ┆ : ["铜质  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Copper    ┆ 金库升级  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Store     ┆ 工具"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[nam…    ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 10014782  ┆ 邂逅缘分  ┆           ┆ {"[name]" ┆ … ┆ 1         ┆           ┆           ┆ 其他     │
│           ┆           ┆           ┆ : ["邂逅  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 缘分"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[explain ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆          │
│ 10014783  ┆ 成为阿拉  ┆           ┆ {"[name]" ┆ … ┆ 1         ┆           ┆           ┆ 其他     │
│           ┆ 德的勇士  ┆           ┆ : ["成为  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 阿拉德的  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 勇士"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[exp…    ┆   ┆           ┆           ┆           ┆          │
│ 690000790 ┆ +7 装备强 ┆           ┆ {"[name]" ┆ … ┆ 1         ┆           ┆           ┆ 其他     │
│           ┆ 化券      ┆           ┆ : ["+7    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 装备强化  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 券"],     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[exp…    ┆   ┆           ┆           ┆           ┆          │
│ 897       ┆ 掉色的黄  ┆ Gold      ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 其他     │
│           ┆ 金装备品  ┆ Kaleido   ┆ : ["掉色  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 级调整箱  ┆ Box       ┆ 的黄金装  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 备品级调  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 整箱"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "…        ┆   ┆           ┆           ┆           ┆          │
│ 8888      ┆ 命运的抉  ┆           ┆ {"[name]" ┆ … ┆ 1         ┆           ┆           ┆ 其他     │
│           ┆ 择+15装备 ┆           ┆ : ["命运  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 强化券    ┆           ┆ 的抉择+15 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 装备强化  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 券"], …   ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [21]:
df.filter(pl.col('stackable_type') == '[expert town potion]')

shape: (26, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id        ┆ name      ┆ name2     ┆ json      ┆ … ┆ sub_stack ┆ item_grou ┆ item_cate ┆ stackabl │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ able_type ┆ p_name    ┆ gory      ┆ e_type_d │
│ i64       ┆ str       ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ isplay   │
│           ┆           ┆           ┆           ┆   ┆ i64       ┆ str       ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 7456      ┆ 魔界抗疲  ┆ Nostrum   ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 秘药     │
│           ┆ 劳秘药    ┆ of        ┆ : ["魔界  ┆   ┆           ┆           ┆           ┆          │
│           ┆ (40点)    ┆ Recovery  ┆ 抗疲劳秘  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 药        ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ (40点)"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆          │
│ 7518      ┆ 魔界抗疲  ┆ Nostrum   ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 秘药     │
│           ┆ 劳秘药    ┆ of        ┆ : ["魔界  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Recovery  ┆ 抗疲劳秘  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 药"],     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name…   ┆   ┆           ┆           ┆           ┆          │
│ 7644      ┆ 魔界抗疲  ┆ Nostrum   ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 秘药     │
│           ┆ 劳秘药    ┆ of        ┆ : ["魔界  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Recovery  ┆ 抗疲劳秘  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 药"],     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name…   ┆   ┆           ┆           ┆           ┆          │
│ 7645      ┆ 魔界抗疲  ┆ Nostrum   ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 秘药     │
│           ┆ 劳秘药    ┆ of        ┆ : ["魔界  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Recovery  ┆ 抗疲劳秘  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 药"],     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name…   ┆   ┆           ┆           ┆           ┆          │
│ 8079      ┆           ┆           ┆ {"[name]" ┆ … ┆ 0         ┆ potion    ┆           ┆ 秘药     │
│           ┆           ┆           ┆ : [""],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2]" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ : ["…     ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 10000526  ┆ 中秋限定· ┆           ┆ {"[name]" ┆ … ┆ 0         ┆ potion    ┆           ┆ 秘药     │
│           ┆ 缓解疲劳  ┆           ┆ : ["中秋  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 之灵药    ┆           ┆ 限定·缓解 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 疲劳之灵  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 药"], "…  ┆   ┆           ┆           ┆           ┆          │
│ 2683400   ┆ 魔界抗疲  ┆           ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 秘药     │
│           ┆ 劳秘药    ┆           ┆ : ["魔界  ┆   ┆           ┆           ┆           ┆          │
│           ┆ (50点)    ┆           ┆ 抗疲劳秘  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 药        ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ (50点)"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆          │
│ 690000016 ┆ 恢复的秘  ┆ CCB       ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 秘药     │
│           ┆ 药        ┆ Recovery  ┆ : ["恢复  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Fatigue   ┆ 的秘药"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Potion    ┆ "[name2]… ┆   ┆           ┆           ┆           ┆          │
│ 690000094 ┆ CB纪念恢  ┆ recovery  ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 秘药     │
│           ┆ 复的秘药  ┆ fatigue   ┆ : ["CB纪  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 念恢复的  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 秘药"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[na…     ┆   ┆           ┆           ┆           ┆          │
│ 690000115 ┆ 魔界抗疲  ┆ Nostrum   ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 秘药     │
│           ┆ 劳秘药    ┆ of        ┆ : ["魔界  ┆   ┆           ┆           ┆           ┆          │
│           ┆ (30点)    ┆ Recovery  ┆ 抗疲劳秘  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 药        ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ (30点)"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [22]:
df.filter(pl.col('stackable_type') == '[feed]')

shape: (1, 11)
┌─────┬──────────┬────────────┬────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ id  ┆ name     ┆ name2      ┆ json       ┆ … ┆ sub_stacka ┆ item_group ┆ item_categ ┆ stackable_ │
│ --- ┆ ---      ┆ ---        ┆ ---        ┆   ┆ ble_type   ┆ _name      ┆ ory        ┆ type_displ │
│ i64 ┆ str      ┆ str        ┆ str        ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ay         │
│     ┆          ┆            ┆            ┆   ┆ i64        ┆ str        ┆ str        ┆ ---        │
│     ┆          ┆            ┆            ┆   ┆            ┆            ┆            ┆ str        │
╞═════╪══════════╪════════════╪════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 24  ┆ 宠物饲料 ┆ Creature   ┆ {"[name]": ┆ … ┆ 1          ┆            ┆            ┆ 宠物道具   │
│     ┆          ┆ Food       ┆ ["宠物饲料 ┆   ┆            ┆            ┆            ┆            │
│     ┆          ┆            ┆ "],        ┆   ┆            ┆            ┆            ┆            │
│     ┆          ┆            ┆ "[name2]"… ┆   ┆            ┆            ┆            ┆            │
└─────┴──────────┴────────────┴────────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [23]:
df.filter(pl.col('stackable_type') == '[global effect]')

shape: (4, 11)
┌──────┬────────────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ id   ┆ name       ┆ name2      ┆ json       ┆ … ┆ sub_stacka ┆ item_grou ┆ item_cate ┆ stackable │
│ ---  ┆ ---        ┆ ---        ┆ ---        ┆   ┆ ble_type   ┆ p_name    ┆ gory      ┆ _type_dis │
│ i64  ┆ str        ┆ str        ┆ str        ┆   ┆ ---        ┆ ---       ┆ ---       ┆ play      │
│      ┆            ┆            ┆            ┆   ┆ i64        ┆ str       ┆ str       ┆ ---       │
│      ┆            ┆            ┆            ┆   ┆            ┆           ┆           ┆ str       │
╞══════╪════════════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 7451 ┆ 成长之幸运 ┆ Fortune    ┆ {"[name]": ┆ … ┆ 0          ┆           ┆           ┆ 频道道具  │
│      ┆ 光环       ┆ Aura of    ┆ ["成长之幸 ┆   ┆            ┆           ┆           ┆           │
│      ┆            ┆ Growth     ┆ 运光环"],  ┆   ┆            ┆           ┆           ┆           │
│      ┆            ┆            ┆ "[name…    ┆   ┆            ┆           ┆           ┆           │
│ 7452 ┆ 财富之幸运 ┆ Fortune    ┆ {"[name]": ┆ … ┆ 0          ┆           ┆           ┆ 频道道具  │
│      ┆ 光环       ┆ Aura of    ┆ ["财富之幸 ┆   ┆            ┆           ┆           ┆           │
│      ┆            ┆ Wealth     ┆ 运光环"],  ┆   ┆            ┆           ┆           ┆           │
│      ┆            ┆            ┆ "[name…    ┆   ┆            ┆           ┆           ┆           │
│ 7453 ┆ 成功之幸运 ┆ Fortune    ┆ {"[name]": ┆ … ┆ 0          ┆           ┆           ┆ 频道道具  │
│      ┆ 光环       ┆ Aura of    ┆ ["成功之幸 ┆   ┆            ┆           ┆           ┆           │
│      ┆            ┆ Success    ┆ 运光环"],  ┆   ┆            ┆           ┆           ┆           │
│      ┆            ┆            ┆ "[name…    ┆   ┆            ┆           ┆           ┆           │
│ 7907 ┆ 5周年庆祝  ┆ Celebratio ┆ {"[name]": ┆ … ┆ 0          ┆           ┆           ┆ 频道道具  │
│      ┆ 绳索       ┆ n Aura of  ┆ ["5周年庆  ┆   ┆            ┆           ┆           ┆           │
│      ┆            ┆ Fifth      ┆ 祝绳索"],  ┆   ┆            ┆           ┆           ┆           │
│      ┆            ┆ Anni…      ┆ "[name…    ┆   ┆            ┆           ┆           ┆           │
└──────┴────────────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [24]:
df.filter(pl.col('stackable_type') == '[legacy]')

shape: (4, 11)
┌──────┬────────────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ id   ┆ name       ┆ name2      ┆ json       ┆ … ┆ sub_stacka ┆ item_grou ┆ item_cate ┆ stackable │
│ ---  ┆ ---        ┆ ---        ┆ ---        ┆   ┆ ble_type   ┆ p_name    ┆ gory      ┆ _type_dis │
│ i64  ┆ str        ┆ str        ┆ str        ┆   ┆ ---        ┆ ---       ┆ ---       ┆ play      │
│      ┆            ┆            ┆            ┆   ┆ i64        ┆ str       ┆ str       ┆ ---       │
│      ┆            ┆            ┆            ┆   ┆            ┆           ┆           ┆ str       │
╞══════╪════════════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 1086 ┆ 潘多拉魔盒 ┆            ┆ {"[name]": ┆ … ┆ 1          ┆           ┆           ┆ 其他      │
│      ┆            ┆            ┆ ["潘多拉魔 ┆   ┆            ┆           ┆           ┆           │
│      ┆            ┆            ┆ 盒"],      ┆   ┆            ┆           ┆           ┆           │
│      ┆            ┆            ┆ "[name2]…  ┆   ┆            ┆           ┆           ┆           │
│ 7036 ┆ 压缩胶囊   ┆            ┆ {"[name]": ┆ … ┆ 5          ┆           ┆           ┆ 其他      │
│      ┆            ┆            ┆ ["压缩胶囊 ┆   ┆            ┆           ┆           ┆           │
│      ┆            ┆            ┆ "],        ┆   ┆            ┆           ┆           ┆           │
│      ┆            ┆            ┆ "[name2]"… ┆   ┆            ┆           ┆           ┆           │
│ 7040 ┆ 运气试炼   ┆ Test of    ┆ {"[name]": ┆ … ┆ 1          ┆           ┆           ┆ 其他      │
│      ┆            ┆ Fortune    ┆ ["运气试炼 ┆   ┆            ┆           ┆           ┆           │
│      ┆            ┆            ┆ "],        ┆   ┆            ┆           ┆           ┆           │
│      ┆            ┆            ┆ "[name2]"… ┆   ┆            ┆           ┆           ┆           │
│ 7188 ┆ 赛丽亚特制 ┆ Seria's    ┆ {"[name]": ┆ … ┆ 1          ┆           ┆           ┆ 其他      │
│      ┆ 的袖珍罐   ┆ Special    ┆ ["赛丽亚特 ┆   ┆            ┆           ┆           ┆           │
│      ┆            ┆ Jar        ┆ 制的袖珍罐 ┆   ┆            ┆           ┆           ┆           │
│      ┆            ┆            ┆ "], "[na…  ┆   ┆            ┆           ┆           ┆           │
└──────┴────────────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [25]:
df.filter(pl.col('stackable_type') == '[material expert job]')

shape: (306, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id        ┆ name      ┆ name2     ┆ json      ┆ … ┆ sub_stack ┆ item_grou ┆ item_cate ┆ stackabl │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ able_type ┆ p_name    ┆ gory      ┆ e_type_d │
│ i64       ┆ str       ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ isplay   │
│           ┆           ┆           ┆           ┆   ┆ i64       ┆ str       ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 3227      ┆ 魔力溶解  ┆ Magical   ┆ {"[name]" ┆ … ┆ 1         ┆ stuff etc ┆           ┆ 副职业   │
│           ┆ 剂        ┆ Powers    ┆ : ["魔力  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Solvent   ┆ 溶解剂"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2]… ┆   ┆           ┆           ┆           ┆          │
│ 3600      ┆ 光之城主  ┆ Sieghart  ┆ {"[name]" ┆ … ┆ 1         ┆           ┆ monster   ┆ 卡片     │
│           ┆ 赛格哈特  ┆ : Lord of ┆ : ["光之  ┆   ┆           ┆           ┆ card      ┆          │
│           ┆ 卡片      ┆ Light's   ┆ 城主赛格  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Cas…      ┆ 哈特      ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 卡片"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "…        ┆   ┆           ┆           ┆           ┆          │
│ 3601      ┆ 长脚罗特  ┆ Lotus of  ┆ {"[name]" ┆ … ┆ 1         ┆           ┆ monster   ┆ 卡片     │
│           ┆ 斯  卡片  ┆ Long Foot ┆ : ["长脚  ┆   ┆           ┆           ┆ card      ┆          │
│           ┆           ┆ Card      ┆ 罗特斯    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 卡片"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[na…     ┆   ┆           ┆           ┆           ┆          │
│ 3602      ┆ 邪龙斯皮  ┆ Head of   ┆ {"[name]" ┆ … ┆ 1         ┆           ┆ monster   ┆ 卡片     │
│           ┆ 兹头部    ┆ Spirrazzi ┆ : ["邪龙  ┆   ┆           ┆           ┆ card      ┆          │
│           ┆ 卡片      ┆ : Dead    ┆ 斯皮兹头  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Drago…    ┆ 部        ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 卡片"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[…       ┆   ┆           ┆           ┆           ┆          │
│ 3603      ┆ 魔笛使者  ┆ Peter The ┆ {"[name]" ┆ … ┆ 1         ┆           ┆ monster   ┆ 卡片     │
│           ┆ 皮特      ┆ Piper     ┆ : ["魔笛  ┆   ┆           ┆           ┆ card      ┆          │
│           ┆ 卡片      ┆ Card      ┆ 使者皮特  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 卡片"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[n…      ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 690000299 ┆ 勇者的祝  ┆ summer    ┆ {"[name]" ┆ … ┆ 1         ┆           ┆ monster   ┆ 卡片     │
│           ┆ 福        ┆ bead      ┆ : ["勇者  ┆   ┆           ┆           ┆ card      ┆          │
│           ┆           ┆           ┆ 的祝福"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2]… ┆   ┆           ┆           ┆           ┆          │
│ 10015651  ┆ 藏有女魔  ┆           ┆ {"[name]" ┆ … ┆ 1         ┆           ┆           ┆ 副职业   │
│           ┆ 法师佣兵  ┆           ┆ : ["藏有  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 力量的卡  ┆           ┆ 女魔法师  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 片        ┆           ┆ 佣兵力量  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 的卡片"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆          │
│ 10015652  ┆ 藏有格斗  ┆           ┆ {"[name]" ┆ … ┆ 1         ┆           ┆           ┆ 副职业   │
│           ┆ 家佣兵力  ┆           ┆ : ["藏有  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 量的卡片  ┆           ┆ 格斗家佣  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 兵力量的  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 卡片"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "…        ┆   ┆           ┆           ┆           ┆          │
│ 10015653  ┆ 藏有女枪  ┆           ┆ {"[name]" ┆ … ┆ 1         ┆           ┆           ┆ 副职业   │
│           ┆ 手佣兵力  ┆           ┆ : ["藏有  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 量的卡片  ┆           ┆ 女枪手佣  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 兵力量的  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 卡片"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "…        ┆   ┆           ┆           ┆           ┆          │
│ 10015654  ┆ 藏有暗夜  ┆           ┆ {"[name]" ┆ … ┆ 1         ┆           ┆           ┆ 副职业   │
│           ┆ 使者佣兵  ┆           ┆ : ["藏有  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 力量的卡  ┆           ┆ 暗夜使者  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 片        ┆           ┆ 佣兵力量  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 的卡片"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [26]:
df.filter(pl.col('stackable_type') == '[material]')

shape: (570, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id        ┆ name      ┆ name2     ┆ json      ┆ … ┆ sub_stack ┆ item_grou ┆ item_cate ┆ stackabl │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ able_type ┆ p_name    ┆ gory      ┆ e_type_d │
│ i64       ┆ str       ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ isplay   │
│           ┆           ┆           ┆           ┆   ┆ i64       ┆ str       ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 900       ┆ 解放之钥  ┆ Key of    ┆ {"[name]" ┆ … ┆ 1         ┆           ┆           ┆ 材料     │
│           ┆           ┆ Release   ┆ : ["解放  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 之钥"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2]" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆          │
│ 2660547   ┆ 智能娃娃  ┆ Label of  ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 材料     │
│           ┆ 机硬币    ┆ crane     ┆ : ["智能  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ game      ┆ 娃娃机硬  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 币"],     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name…   ┆   ┆           ┆           ┆           ┆          │
│ 3012      ┆ 猫妖脚爪  ┆ Lugaru    ┆ {"[name]" ┆ … ┆ 3         ┆ animal    ┆           ┆ 材料     │
│           ┆           ┆ Claw      ┆ : ["猫妖  ┆   ┆           ┆ stuff     ┆           ┆          │
│           ┆           ┆           ┆ 脚爪"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2]" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆          │
│ 3015      ┆ 哥布林手  ┆ Goblin    ┆ {"[name]" ┆ … ┆ 4         ┆ animal    ┆           ┆ 材料     │
│           ┆ 骨        ┆ Handbone  ┆ : ["哥布  ┆   ┆           ┆ stuff     ┆           ┆          │
│           ┆           ┆           ┆ 林手骨"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2]… ┆   ┆           ┆           ┆           ┆          │
│ 3016      ┆ 魔法师的  ┆           ┆ {"[name]" ┆ … ┆ 10        ┆ animal    ┆           ┆ 材料     │
│           ┆ 血液      ┆           ┆ : ["魔法  ┆   ┆           ┆ stuff     ┆           ┆          │
│           ┆           ┆           ┆ 师的血液" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ],        ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[expla…  ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 10092630  ┆ 能量残骸  ┆           ┆ {"[name]" ┆ … ┆ 2         ┆           ┆           ┆ 材料     │
│           ┆           ┆           ┆ : ["能量  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 残骸"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[explain ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆          │
│ 690000778 ┆ 万圣节南  ┆           ┆ {"[name]" ┆ … ┆ 1         ┆           ┆           ┆ 材料     │
│           ┆ 瓜        ┆           ┆ : ["万圣  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 节南瓜"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[flavor… ┆   ┆           ┆           ┆           ┆          │
│ 690000780 ┆ 万圣节纪  ┆           ┆ {"[name]" ┆ … ┆ 1         ┆           ┆           ┆ 材料     │
│           ┆ 念货币    ┆           ┆ : ["万圣  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 节纪念货  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 币"],     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[expl…   ┆   ┆           ┆           ┆           ┆          │
│ 690000794 ┆ 深渊派对  ┆           ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 材料     │
│           ┆ 免费招待  ┆           ┆ : ["深渊  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 券[万圣节 ┆           ┆ 派对免费  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 活动]     ┆           ┆ 招待券[万 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 圣节活动] ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "…        ┆   ┆           ┆           ┆           ┆          │
│ 2670203   ┆ 高级炉岩  ┆ Senior    ┆ {"[name]" ┆ … ┆ 1         ┆ mineral   ┆           ┆ 材料     │
│           ┆ 炭        ┆ Ryan      ┆ : ["高级  ┆   ┆           ┆ stuff     ┆           ┆          │
│           ┆           ┆ Cokes     ┆ 炉岩炭"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2]… ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [27]:
df.filter(pl.col('stackable_type') == '[multi upgradable legacy bonus cera]')

shape: (1, 11)
┌─────────┬────────────┬───────┬────────────┬───┬────────────┬────────────┬────────────┬───────────┐
│ id      ┆ name       ┆ name2 ┆ json       ┆ … ┆ sub_stacka ┆ item_group ┆ item_categ ┆ stackable │
│ ---     ┆ ---        ┆ ---   ┆ ---        ┆   ┆ ble_type   ┆ _name      ┆ ory        ┆ _type_dis │
│ i64     ┆ str        ┆ str   ┆ str        ┆   ┆ ---        ┆ ---        ┆ ---        ┆ play      │
│         ┆            ┆       ┆            ┆   ┆ i64        ┆ str        ┆ str        ┆ ---       │
│         ┆            ┆       ┆            ┆   ┆            ┆            ┆            ┆ str       │
╞═════════╪════════════╪═══════╪════════════╪═══╪════════════╪════════════╪════════════╪═══════════╡
│ 2660419 ┆ 盛装的箱子 ┆       ┆ {"[name]": ┆ … ┆ 0          ┆            ┆            ┆ 其他      │
│         ┆            ┆       ┆ ["盛装的箱 ┆   ┆            ┆            ┆            ┆           │
│         ┆            ┆       ┆ 子"],      ┆   ┆            ┆            ┆            ┆           │
│         ┆            ┆       ┆ "[name2]…  ┆   ┆            ┆            ┆            ┆           │
└─────────┴────────────┴───────┴────────────┴───┴────────────┴────────────┴────────────┴───────────┘

In [28]:
df.filter(pl.col('stackable_type') == '[multi upgradable legacy]')

shape: (6, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id        ┆ name      ┆ name2     ┆ json      ┆ … ┆ sub_stack ┆ item_grou ┆ item_cate ┆ stackabl │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ able_type ┆ p_name    ┆ gory      ┆ e_type_d │
│ i64       ┆ str       ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ isplay   │
│           ┆           ┆           ┆           ┆   ┆ i64       ┆ str       ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 896       ┆ 封印之锁  ┆ Sealed    ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 其他     │
│           ┆           ┆ Lock      ┆ : ["封印  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 之锁"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2]" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆          │
│ 992       ┆ 奇异国度  ┆ Sealed    ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 其他     │
│           ┆ 封印之锁  ┆ Lock of   ┆ : ["奇异  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Wonder    ┆ 国度封印  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Land      ┆ 之锁"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[nam…    ┆   ┆           ┆           ┆           ┆          │
│ 2660169   ┆ 封印的祖  ┆           ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 其他     │
│           ┆ 母绿锁    ┆           ┆ : ["封印  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 的祖母绿  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 锁"],     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name…   ┆   ┆           ┆           ┆           ┆          │
│ 2660397   ┆ 七彩封印  ┆           ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 其他     │
│           ┆ 之锁      ┆           ┆ : ["七彩  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 封印之锁" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ],        ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2…  ┆   ┆           ┆           ┆           ┆          │
│ 8289      ┆ 活动礼盒  ┆           ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 其他     │
│           ┆           ┆           ┆ : ["活动  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 礼盒"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[explain ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆          │
│ 690000280 ┆ 封印之锁  ┆           ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 其他     │
│           ┆           ┆           ┆ : ["封印  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 之锁"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2]" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [29]:
df.filter(pl.col('stackable_type') == '[only effect]')

shape: (20, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id        ┆ name      ┆ name2     ┆ json      ┆ … ┆ sub_stack ┆ item_grou ┆ item_cate ┆ stackabl │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ able_type ┆ p_name    ┆ gory      ┆ e_type_d │
│ i64       ┆ str       ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ isplay   │
│           ┆           ┆           ┆           ┆   ┆ i64       ┆ str       ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 7576      ┆ 五彩烟火  ┆ Five-Colo ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 其他     │
│           ┆           ┆ red Firec ┆ : ["五彩  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ racker    ┆ 烟火"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2]" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆          │
│ 7577      ┆ 粉色花瓣  ┆ Pink      ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 其他     │
│           ┆           ┆ Petal     ┆ : ["粉色  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 花瓣"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2]" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆          │
│ 10000113  ┆ 红色闪电  ┆           ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 其他     │
│           ┆ 爆竹      ┆           ┆ : ["红色  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 闪电爆竹" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ],        ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2…  ┆   ┆           ┆           ┆           ┆          │
│ 10000114  ┆ 蓝色闪电  ┆           ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 其他     │
│           ┆ 爆竹      ┆           ┆ : ["蓝色  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 闪电爆竹" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ],        ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2…  ┆   ┆           ┆           ┆           ┆          │
│ 690000031 ┆ 五彩烟火  ┆ Firework  ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 其他     │
│           ┆           ┆           ┆ : ["五彩  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 烟火"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2]" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 202388980 ┆ 副本难度  ┆ Dungeon   ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 其他     │
│ 8         ┆ 解锁券    ┆ difficult ┆ : ["副本  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ y unlock  ┆ 难度解锁  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ tick…     ┆ 券"],     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name…   ┆   ┆           ┆           ┆           ┆          │
│ 202211050 ┆ 一键分解  ┆ One-click ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 其他     │
│ 4         ┆ 券        ┆ breakdown ┆ : ["一键  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ of        ┆ 分解券"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ coupons   ┆ "[name2]… ┆   ┆           ┆           ┆           ┆          │
│ 202145880 ┆ 万能跨界  ┆           ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 其他     │
│ 1         ┆ 石        ┆           ┆ : ["万能  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 跨界石"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[explai… ┆   ┆           ┆           ┆           ┆          │
│ 20250928  ┆ 一键出售  ┆           ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 其他     │
│           ┆ 白装券    ┆           ┆ : ["一键  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 出售白装  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 券"],     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name…   ┆   ┆           ┆           ┆           ┆          │
│ 202509281 ┆ 一键出售  ┆           ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 其他     │
│           ┆ 白蓝装券  ┆           ┆ : ["一键  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 出售白蓝  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 装券"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[nam…    ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [30]:
df.filter(pl.col('stackable_type') == '[quest]')

shape: (803, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id        ┆ name      ┆ name2     ┆ json      ┆ … ┆ sub_stack ┆ item_grou ┆ item_cate ┆ stackabl │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ able_type ┆ p_name    ┆ gory      ┆ e_type_d │
│ i64       ┆ str       ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ isplay   │
│           ┆           ┆           ┆           ┆   ┆ i64       ┆ str       ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 3072      ┆ 寒气结晶  ┆ Crystalli ┆ {"[name]" ┆ … ┆ 3         ┆ mineral   ┆           ┆ 任务道具 │
│           ┆           ┆ zation of ┆ : ["寒气  ┆   ┆           ┆ stuff     ┆           ┆          │
│           ┆           ┆ Chill     ┆ 结晶"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2]" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆          │
│ 3073      ┆ 火焰结晶  ┆ Crystalli ┆ {"[name]" ┆ … ┆ 3         ┆ mineral   ┆           ┆ 任务道具 │
│           ┆           ┆ zation of ┆ : ["火焰  ┆   ┆           ┆ stuff     ┆           ┆          │
│           ┆           ┆ Flame     ┆ 结晶"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2]" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆          │
│ 3077      ┆ 灰色结晶  ┆ Crystal   ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 任务道具 │
│           ┆           ┆ of Gray   ┆ : ["灰色  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 结晶"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2]" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆          │
│ 3078      ┆ 灰色结晶  ┆ Small     ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 任务道具 │
│           ┆ 碎片      ┆ Crysta of ┆ : ["灰色  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Gray      ┆ 结晶碎片" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ],        ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2…  ┆   ┆           ┆           ┆           ┆          │
│ 3079      ┆ 魔法结晶  ┆ Crystal   ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 任务道具 │
│           ┆           ┆ of Magic  ┆ : ["魔法  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 结晶"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2]" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 690000698 ┆ 恐龙的巨  ┆ big egg   ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 任务道具 │
│           ┆ 蛋        ┆           ┆ : ["恐龙  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 的巨蛋"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2]… ┆   ┆           ┆           ┆           ┆          │
│ 690000699 ┆ 石巨人的  ┆ skin      ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 任务道具 │
│           ┆ 坚硬外壳  ┆           ┆ : ["石巨  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 人的坚硬  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 外壳"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[nam…    ┆   ┆           ┆           ┆           ┆          │
│ 690000700 ┆ 火焰精灵  ┆ fire ora  ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 任务道具 │
│           ┆ 的火舌    ┆           ┆ : ["火焰  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 精灵的火  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 舌"],     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name…   ┆   ┆           ┆           ┆           ┆          │
│ 10092628  ┆ 机械碎片  ┆           ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 任务道具 │
│           ┆           ┆           ┆ : ["机械  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 碎片"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[explain ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆          │
│ 10093393  ┆ 赫拉斯研  ┆           ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 任务道具 │
│           ┆ 究所的钥  ┆           ┆ : ["赫拉  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 匙        ┆           ┆ 斯研究所  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 的钥匙"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[ex…     ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [31]:
df.filter(pl.col('stackable_type') == '[recipe]')

shape: (6_860, 11)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ id       ┆ name      ┆ name2     ┆ json      ┆ … ┆ sub_stack ┆ item_grou ┆ item_cate ┆ stackable │
│ ---      ┆ ---       ┆ ---       ┆ ---       ┆   ┆ able_type ┆ p_name    ┆ gory      ┆ _type_dis │
│ i64      ┆ str       ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ play      │
│          ┆           ┆           ┆           ┆   ┆ i64       ┆ str       ┆ str       ┆ ---       │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ str       │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1195     ┆ 圣光之珠  ┆ Recipe of ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 设计图    │
│          ┆ 设计图    ┆ Holy      ┆ : ["圣光  ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆ precious  ┆ 之珠      ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆ stone     ┆ 设计图"], ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ "[na…     ┆   ┆           ┆           ┆           ┆           │
│ 1196     ┆ 先知者的  ┆ Recipe of ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 设计图    │
│          ┆ 铁拳      ┆ the fist  ┆ : ["先知  ┆   ┆           ┆           ┆           ┆           │
│          ┆ 设计图    ┆ of        ┆ 者的铁拳  ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆ prophets  ┆ 设计图"], ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ "[…       ┆   ┆           ┆           ┆           ┆           │
│ 1197     ┆ 信耶的附  ┆ Recipe of ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 设计图    │
│          ┆ 灵青龙碎  ┆ Sinya's   ┆ : ["信耶  ┆   ┆           ┆           ┆           ┆           │
│          ┆ 片        ┆ Spirit    ┆ 的附灵青  ┆   ┆           ┆           ┆           ┆           │
│          ┆ 设计图    ┆ Attat…    ┆ 龙碎片    ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ 设计图"], ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆           │
│ 1242     ┆ 赛丽亚的  ┆ Seria a   ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 设计图    │
│          ┆ 思念      ┆ Recipient ┆ : ["赛丽  ┆   ┆           ┆           ┆           ┆           │
│          ┆ 设计图    ┆ of the    ┆ 亚的思念  ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆ Love …    ┆ 设计图"], ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ "[…       ┆   ┆           ┆           ┆           ┆           │
│ 1243     ┆ G.S.D的朋 ┆ G.S.D a   ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 设计图    │
│          ┆ 友        ┆ Trusted   ┆ : ["G.S.D ┆   ┆           ┆           ┆           ┆           │
│          ┆ 设计图    ┆ Person    ┆ 的朋友    ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆ Recipe    ┆ 设计图"], ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆           │
│ …        ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 2649809  ┆ 真 · 绝地 ┆ Recipe of ┆ {"[name]" ┆ … ┆ 1         ┆           ┆           ┆ 设计图    │
│          ┆ 武士腰带  ┆ Shin :    ┆ : ["真 ·  ┆   ┆           ┆           ┆           ┆           │
│          ┆ 设计图    ┆ Garura    ┆ 绝地武士  ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆ Warrio…   ┆ 腰带      ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ 设计图"]… ┆   ┆           ┆           ┆           ┆           │
│ 2649811  ┆ 真 · 邪恶 ┆ Recipe of ┆ {"[name]" ┆ … ┆ 1         ┆           ┆           ┆ 设计图    │
│          ┆ 之击腰带  ┆ Shin :    ┆ : ["真 ·  ┆   ┆           ┆           ┆           ┆           │
│          ┆ 设计图    ┆ Evil      ┆ 邪恶之击  ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆ Repulser… ┆ 腰带      ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ 设计图"]… ┆   ┆           ┆           ┆           ┆           │
│ 10002594 ┆ 魔法巨龙  ┆           ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 设计图    │
│          ┆ 石像的卷  ┆           ┆ : ["魔法  ┆   ┆           ┆           ┆           ┆           │
│          ┆ 轴 : 独立 ┆           ┆ 巨龙石像  ┆   ┆           ┆           ┆           ┆           │
│          ┆ 攻击力    ┆           ┆ 的卷轴 :  ┆   ┆           ┆           ┆           ┆           │
│          ┆ +44       ┆           ┆ 独立攻击  ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ 力…       ┆   ┆           ┆           ┆           ┆           │
│ 10002595 ┆ 巨型烈焰  ┆           ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 设计图    │
│          ┆ 傀儡的卷  ┆           ┆ : ["巨型  ┆   ┆           ┆           ┆           ┆           │
│          ┆ 轴 : 魔法 ┆           ┆ 烈焰傀儡  ┆   ┆           ┆           ┆           ┆           │
│          ┆ 攻击力    ┆           ┆ 的卷轴 :  ┆   ┆           ┆           ┆           ┆           │
│          ┆ +23       ┆           ┆ 魔法攻击  ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ 力…       ┆   ┆           ┆           ┆           ┆           │
│ 10002596 ┆ 巨龙纳特  ┆           ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 设计图    │
│          ┆ 拉的卷轴  ┆           ┆ : ["巨龙  ┆   ┆           ┆           ┆           ┆           │
│          ┆ : 物理攻  ┆           ┆ 纳特拉的  ┆   ┆           ┆           ┆           ┆           │
│          ┆ 击力 +23  ┆           ┆ 卷轴 :    ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ 物理攻击  ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ 力 …      ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [32]:
df.filter(pl.col('stackable_type') == '[quest receive]')

shape: (7, 11)
┌──────┬────────────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ id   ┆ name       ┆ name2      ┆ json       ┆ … ┆ sub_stacka ┆ item_grou ┆ item_cate ┆ stackable │
│ ---  ┆ ---        ┆ ---        ┆ ---        ┆   ┆ ble_type   ┆ p_name    ┆ gory      ┆ _type_dis │
│ i64  ┆ str        ┆ str        ┆ str        ┆   ┆ ---        ┆ ---       ┆ ---       ┆ play      │
│      ┆            ┆            ┆            ┆   ┆ i64        ┆ str       ┆ str       ┆ ---       │
│      ┆            ┆            ┆            ┆   ┆            ┆           ┆           ┆ str       │
╞══════╪════════════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 1141 ┆ 古代书籍   ┆ Ancient    ┆ {"[name]": ┆ … ┆ 0          ┆           ┆           ┆ 悬赏令    │
│      ┆            ┆ Book       ┆ ["古代书籍 ┆   ┆            ┆           ┆           ┆           │
│      ┆            ┆            ┆ "],        ┆   ┆            ┆           ┆           ┆           │
│      ┆            ┆            ┆ "[name2]"… ┆   ┆            ┆           ┆           ┆           │
│ 1288 ┆ 悬赏令 -   ┆ Wanted -   ┆ {"[name]": ┆ … ┆ 0          ┆           ┆           ┆ 悬赏令    │
│      ┆ 锤王波罗丁 ┆ Hammerking ┆ ["悬赏令 - ┆   ┆            ┆           ┆           ┆           │
│      ┆            ┆ Borodin    ┆ 锤王波罗丁 ┆   ┆            ┆           ┆           ┆           │
│      ┆            ┆            ┆ "], "[…    ┆   ┆            ┆           ┆           ┆           │
│ 1289 ┆ 悬赏令 -   ┆ Wanted -   ┆ {"[name]": ┆ … ┆ 0          ┆           ┆           ┆ 悬赏令    │
│      ┆ 牛头械王   ┆ Hyper      ┆ ["悬赏令 - ┆   ┆            ┆           ┆           ┆           │
│      ┆            ┆ Mechatau   ┆ 牛头械王"] ┆   ┆            ┆           ┆           ┆           │
│      ┆            ┆            ┆ , "[n…     ┆   ┆            ┆           ┆           ┆           │
│ 1290 ┆ 悬赏令 -   ┆ Wanted -   ┆ {"[name]": ┆ … ┆ 0          ┆           ┆           ┆ 悬赏令    │
│      ┆ 虫王戮蛊   ┆ Huge Nugol ┆ ["悬赏令 - ┆   ┆            ┆           ┆           ┆           │
│      ┆            ┆            ┆ 虫王戮蛊"] ┆   ┆            ┆           ┆           ┆           │
│      ┆            ┆            ┆ , "[n…     ┆   ┆            ┆           ┆           ┆           │
│ 1291 ┆ 悬赏令 -   ┆ Wanted -   ┆ {"[name]": ┆ … ┆ 0          ┆           ┆           ┆ 悬赏令    │
│      ┆ 狄瑞吉的幻 ┆ Phantom of ┆ ["悬赏令 - ┆   ┆            ┆           ┆           ┆           │
│      ┆ 影         ┆ Direzie    ┆ 狄瑞吉的幻 ┆   ┆            ┆           ┆           ┆           │
│      ┆            ┆            ┆ 影"], "…   ┆   ┆            ┆           ┆           ┆           │
│ 1292 ┆ 悬赏令 -   ┆ Wanted -   ┆ {"[name]": ┆ … ┆ 0          ┆           ┆           ┆ 悬赏令    │
│      ┆ 巨灵布鲁   ┆ Big Ghost  ┆ ["悬赏令 - ┆   ┆            ┆           ┆           ┆           │
│      ┆            ┆ Flu        ┆ 巨灵布鲁"] ┆   ┆            ┆           ┆           ┆           │
│      ┆            ┆            ┆ , "[n…     ┆   ┆            ┆           ┆           ┆           │
│ 1293 ┆ 悬赏令 -   ┆ Wanted -   ┆ {"[name]": ┆ … ┆ 0          ┆           ┆           ┆ 悬赏令    │
│      ┆ 黑色瘟疫狄 ┆ The Wicked ┆ ["悬赏令 - ┆   ┆            ┆           ┆           ┆           │
│      ┆ 瑞吉       ┆ Disease    ┆ 黑色瘟疫狄 ┆   ┆            ┆           ┆           ┆           │
│      ┆            ┆ Di…        ┆ 瑞吉"], …  ┆   ┆            ┆           ┆           ┆           │
└──────┴────────────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [33]:
df.filter(pl.col('stackable_type') == '[set]')

shape: (7, 11)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ id       ┆ name      ┆ name2     ┆ json      ┆ … ┆ sub_stack ┆ item_grou ┆ item_cate ┆ stackable │
│ ---      ┆ ---       ┆ ---       ┆ ---       ┆   ┆ able_type ┆ p_name    ┆ gory      ┆ _type_dis │
│ i64      ┆ str       ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ play      │
│          ┆           ┆           ┆           ┆   ┆ i64       ┆ str       ┆ str       ┆ ---       │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ str       │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 6020     ┆ 哥布林地  ┆ Goblin    ┆ {"[name]" ┆ … ┆ 1         ┆           ┆           ┆ 地雷      │
│          ┆ 雷        ┆ Mine      ┆ : ["哥布  ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ 林地雷"], ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ "[name2]… ┆   ┆           ┆           ┆           ┆           │
│ 6044     ┆ 哥布林地  ┆ Goblin    ┆ {"[name]" ┆ … ┆ 3         ┆           ┆           ┆ 地雷      │
│          ┆ 雷 2      ┆ Mine2     ┆ : ["哥布  ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ 林地雷    ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ 2"],      ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ "[name…   ┆   ┆           ┆           ┆           ┆           │
│ 6045     ┆ 哥布林地  ┆ Goblin    ┆ {"[name]" ┆ … ┆ 3         ┆           ┆           ┆ 地雷      │
│          ┆ 雷 3      ┆ Mine3     ┆ : ["哥布  ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ 林地雷    ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ 3"],      ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ "[name…   ┆   ┆           ┆           ┆           ┆           │
│ 6046     ┆ 哥布林地  ┆ Goblin    ┆ {"[name]" ┆ … ┆ 3         ┆           ┆           ┆ 地雷      │
│          ┆ 雷 4      ┆ Mine4     ┆ : ["哥布  ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ 林地雷    ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ 4"],      ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ "[name…   ┆   ┆           ┆           ┆           ┆           │
│ 1073     ┆ 藤蔓种子  ┆ Tough     ┆ {"[name]" ┆ … ┆ 3         ┆           ┆           ┆ 地雷      │
│          ┆           ┆ Vine Seed ┆ : ["藤蔓  ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ 种子"],   ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ "[name2]" ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆           │
│ 10002833 ┆ 破甲地雷  ┆           ┆ {"[name]" ┆ … ┆ 3         ┆           ┆           ┆ 地雷      │
│          ┆ (物理)    ┆           ┆ : ["破甲  ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ 地雷      ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ (物理)"], ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ "[ex…     ┆   ┆           ┆           ┆           ┆           │
│ 10002834 ┆ 破甲地雷  ┆           ┆ {"[name]" ┆ … ┆ 3         ┆           ┆           ┆ 地雷      │
│          ┆ (魔法)    ┆           ┆ : ["破甲  ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ 地雷      ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ (魔法)"], ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ "[ex…     ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [34]:
df.filter(pl.col('stackable_type') == '[stackable legacy]')

shape: (2, 11)
┌──────┬────────────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ id   ┆ name       ┆ name2      ┆ json       ┆ … ┆ sub_stacka ┆ item_grou ┆ item_cate ┆ stackable │
│ ---  ┆ ---        ┆ ---        ┆ ---        ┆   ┆ ble_type   ┆ p_name    ┆ gory      ┆ _type_dis │
│ i64  ┆ str        ┆ str        ┆ str        ┆   ┆ ---        ┆ ---       ┆ ---       ┆ play      │
│      ┆            ┆            ┆            ┆   ┆ i64        ┆ str       ┆ str       ┆ ---       │
│      ┆            ┆            ┆            ┆   ┆            ┆           ┆           ┆ str       │
╞══════╪════════════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 7106 ┆ 可乐魔法币 ┆ Coke Magic ┆ {"[name]": ┆ … ┆ 1          ┆           ┆           ┆ 其他      │
│      ┆            ┆ Coin       ┆ ["可乐魔法 ┆   ┆            ┆           ┆           ┆           │
│      ┆            ┆            ┆ 币"],      ┆   ┆            ┆           ┆           ┆           │
│      ┆            ┆            ┆ "[name2]…  ┆   ┆            ┆           ┆           ┆           │
│ 7297 ┆ 面碗售货机 ┆ 面碗售货机 ┆ {"[name]": ┆ … ┆ 0          ┆           ┆           ┆ 其他      │
│      ┆ 使用券     ┆ 使用券     ┆ [""],      ┆   ┆            ┆           ┆           ┆           │
│      ┆            ┆            ┆ "[name2]": ┆   ┆            ┆           ┆           ┆           │
│      ┆            ┆            ┆ ["…        ┆   ┆            ┆           ┆           ┆           │
└──────┴────────────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [35]:
df.filter(pl.col('stackable_type') == '[teleport potion]')

shape: (2, 11)
┌─────────┬────────────┬───────┬────────────┬───┬────────────┬────────────┬────────────┬───────────┐
│ id      ┆ name       ┆ name2 ┆ json       ┆ … ┆ sub_stacka ┆ item_group ┆ item_categ ┆ stackable │
│ ---     ┆ ---        ┆ ---   ┆ ---        ┆   ┆ ble_type   ┆ _name      ┆ ory        ┆ _type_dis │
│ i64     ┆ str        ┆ str   ┆ str        ┆   ┆ ---        ┆ ---        ┆ ---        ┆ play      │
│         ┆            ┆       ┆            ┆   ┆ i64        ┆ str        ┆ str        ┆ ---       │
│         ┆            ┆       ┆            ┆   ┆            ┆            ┆            ┆ str       │
╞═════════╪════════════╪═══════╪════════════╪═══╪════════════╪════════════╪════════════╪═══════════╡
│ 2680784 ┆ 赛丽亚的瞬 ┆       ┆ {"[name]": ┆ … ┆ 0          ┆ potion     ┆            ┆ 瞬间移动  │
│         ┆ 间移动药剂 ┆       ┆ ["赛丽亚的 ┆   ┆            ┆            ┆            ┆ 药剂      │
│         ┆            ┆       ┆ 瞬间移动药 ┆   ┆            ┆            ┆            ┆           │
│         ┆            ┆       ┆ 剂"], "[e… ┆   ┆            ┆            ┆            ┆           │
│ 2749064 ┆ 赛丽亚的瞬 ┆       ┆ {"[name]": ┆ … ┆ 0          ┆ potion     ┆            ┆ 瞬间移动  │
│         ┆ 间移动药剂 ┆       ┆ ["赛丽亚的 ┆   ┆            ┆            ┆            ┆ 药剂      │
│         ┆            ┆       ┆ 瞬间移动药 ┆   ┆            ┆            ┆            ┆           │
│         ┆            ┆       ┆ 剂"], "[e… ┆   ┆            ┆            ┆            ┆           │
└─────────┴────────────┴───────┴────────────┴───┴────────────┴────────────┴────────────┴───────────┘

In [36]:
df.filter(pl.col('stackable_type') == '[throw]')

shape: (63, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id        ┆ name      ┆ name2     ┆ json      ┆ … ┆ sub_stack ┆ item_grou ┆ item_cate ┆ stackabl │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ able_type ┆ p_name    ┆ gory      ┆ e_type_d │
│ i64       ┆ str       ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ isplay   │
│           ┆           ┆           ┆           ┆   ┆ i64       ┆ str       ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 6001      ┆ 飞盘      ┆ Weahtersp ┆ {"[name]" ┆ … ┆ 3         ┆           ┆           ┆ 投掷物   │
│           ┆           ┆ oon Disk  ┆ :         ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ["飞盘"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2]" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ : …       ┆   ┆           ┆           ┆           ┆          │
│ 6002      ┆ 回旋镖    ┆ Boomerang ┆ {"[name]" ┆ … ┆ 2         ┆           ┆           ┆ 投掷物   │
│           ┆           ┆           ┆ : ["回旋  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 镖"], "[n ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ame2]":…  ┆   ┆           ┆           ┆           ┆          │
│ 6003      ┆ 石头      ┆ Stone     ┆ {"[name]" ┆ … ┆ 1         ┆           ┆           ┆ 投掷物   │
│           ┆           ┆           ┆ :         ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ["石头"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2]" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ : …       ┆   ┆           ┆           ┆           ┆          │
│ 6004      ┆ 天空树果  ┆ Fruit of  ┆ {"[name]" ┆ … ┆ 2         ┆           ┆           ┆ 投掷物   │
│           ┆ 实        ┆ Skytree   ┆ : ["天空  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 树果实"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2]… ┆   ┆           ┆           ┆           ┆          │
│ 6005      ┆ 燃烧瓶    ┆ Oil Flask ┆ {"[name]" ┆ … ┆ 2         ┆           ┆           ┆ 投掷物   │
│           ┆           ┆           ┆ : ["燃烧  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 瓶"], "[n ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ame2]":…  ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 80006     ┆ 石头      ┆ Stone     ┆ {"[name]" ┆ … ┆ 1         ┆           ┆           ┆ 投掷物   │
│           ┆           ┆           ┆ :         ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ["石头"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2]" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ : …       ┆   ┆           ┆           ┆           ┆          │
│ 10002832  ┆ 魔力分解  ┆           ┆ {"[name]" ┆ … ┆ 3         ┆           ┆           ┆ 投掷物   │
│           ┆ 炸弹      ┆           ┆ : ["魔力  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 分解炸弹" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ],        ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[expla…  ┆   ┆           ┆           ┆           ┆          │
│ 10002838  ┆ 虚祖皇家  ┆           ┆ {"[name]" ┆ … ┆ 3         ┆           ┆           ┆ 投掷物   │
│           ┆ 念气罩    ┆           ┆ : ["虚祖  ┆   ┆           ┆           ┆           ┆          │
│           ┆ (物理)    ┆           ┆ 皇家念气  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 罩        ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ (物理)"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "…        ┆   ┆           ┆           ┆           ┆          │
│ 10002902  ┆ 虚祖皇家  ┆           ┆ {"[name]" ┆ … ┆ 3         ┆           ┆           ┆ 投掷物   │
│           ┆ 念气罩    ┆           ┆ : ["虚祖  ┆   ┆           ┆           ┆           ┆          │
│           ┆ (魔法)    ┆           ┆ 皇家念气  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 罩        ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ (魔法)"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "…        ┆   ┆           ┆           ┆           ┆          │
│ 690000179 ┆ 尘埃与碎  ┆ Stone     ┆ {"[name]" ┆ … ┆ 1         ┆           ┆           ┆ 投掷物   │
│           ┆ 石        ┆           ┆ : ["尘埃  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 与碎石"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2]… ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [37]:
df.filter(pl.col('stackable_type') == '[town and dungeon]')

shape: (14, 11)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ id       ┆ name      ┆ name2     ┆ json      ┆ … ┆ sub_stack ┆ item_grou ┆ item_cate ┆ stackable │
│ ---      ┆ ---       ┆ ---       ┆ ---       ┆   ┆ able_type ┆ p_name    ┆ gory      ┆ _type_dis │
│ i64      ┆ str       ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ play      │
│          ┆           ┆           ┆           ┆   ┆ i64       ┆ str       ┆ str       ┆ ---       │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ str       │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2600460  ┆ 破旧的解  ┆ Poor      ┆ {"[name]" ┆ … ┆ 0         ┆ potion    ┆           ┆ 其他      │
│          ┆ 封卷轴    ┆ Unlock    ┆ : ["破旧  ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆ Scroll    ┆ 的解封卷  ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ 轴"],     ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ "[name…   ┆   ┆           ┆           ┆           ┆           │
│ 2600461  ┆ 古老的解  ┆ Easy      ┆ {"[name]" ┆ … ┆ 0         ┆ potion    ┆           ┆ 其他      │
│          ┆ 封卷轴    ┆ Unlock    ┆ : ["古老  ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆ Scroll    ┆ 的解封卷  ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ 轴"],     ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ "[name…   ┆   ┆           ┆           ┆           ┆           │
│ 2600462  ┆ 神奇的解  ┆ Strong    ┆ {"[name]" ┆ … ┆ 0         ┆ potion    ┆           ┆ 其他      │
│          ┆ 封卷轴    ┆ Unlock    ┆ : ["神奇  ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆ Scroll    ┆ 的解封卷  ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ 轴"],     ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ "[name…   ┆   ┆           ┆           ┆           ┆           │
│ 2600468  ┆ 破旧的便  ┆ Uneasy    ┆ {"[name]" ┆ … ┆ 0         ┆ potion    ┆           ┆ 其他      │
│          ┆ 携式分解  ┆ Portable  ┆ : ["破旧  ┆   ┆           ┆           ┆           ┆           │
│          ┆ 机        ┆ Disjointo ┆ 的便携式  ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆ r         ┆ 分解机"], ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ "[na…     ┆   ┆           ┆           ┆           ┆           │
│ 2600469  ┆ 普通的便  ┆ Good      ┆ {"[name]" ┆ … ┆ 0         ┆ potion    ┆           ┆ 其他      │
│          ┆ 携式分解  ┆ Portable  ┆ : ["普通  ┆   ┆           ┆           ┆           ┆           │
│          ┆ 机        ┆ Disjointo ┆ 的便携式  ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆ r         ┆ 分解机"], ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ "[na…     ┆   ┆           ┆           ┆           ┆           │
│ …        ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 10000322 ┆ 单次用强  ┆           ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 其他      │
│          ┆ 化机(1~40 ┆           ┆ : ["单次  ┆   ┆           ┆           ┆           ┆           │
│          ┆ 级装备/+1 ┆           ┆ 用强化机( ┆   ┆           ┆           ┆           ┆           │
│          ┆ 1以上)    ┆           ┆ 1~40级装  ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ 备/+1…    ┆   ┆           ┆           ┆           ┆           │
│ 10000323 ┆ 单次用强  ┆           ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 其他      │
│          ┆ 化机(1~69 ┆           ┆ : ["单次  ┆   ┆           ┆           ┆           ┆           │
│          ┆ 级装备/+1 ┆           ┆ 用强化机( ┆   ┆           ┆           ┆           ┆           │
│          ┆ 0以下)    ┆           ┆ 1~69级装  ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ 备/+1…    ┆   ┆           ┆           ┆           ┆           │
│ 10000324 ┆ 单次用强  ┆           ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 其他      │
│          ┆ 化机(1~85 ┆           ┆ : ["单次  ┆   ┆           ┆           ┆           ┆           │
│          ┆ 级装备/+1 ┆           ┆ 用强化机( ┆   ┆           ┆           ┆           ┆           │
│          ┆ 0以下)    ┆           ┆ 1~85级装  ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ 备/+1…    ┆   ┆           ┆           ┆           ┆           │
│ 10000325 ┆ 单次用强  ┆           ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 其他      │
│          ┆ 化机(1~85 ┆           ┆ : ["单次  ┆   ┆           ┆           ┆           ┆           │
│          ┆ 级装备/+1 ┆           ┆ 用强化机( ┆   ┆           ┆           ┆           ┆           │
│          ┆ 1以上)    ┆           ┆ 1~85级装  ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ 备/+1…    ┆   ┆           ┆           ┆           ┆           │
│ 10000326 ┆ 单次用强  ┆           ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 其他      │
│          ┆ 化机(1~69 ┆           ┆ : ["单次  ┆   ┆           ┆           ┆           ┆           │
│          ┆ 级装备/+1 ┆           ┆ 用强化机( ┆   ┆           ┆           ┆           ┆           │
│          ┆ 1以上)    ┆           ┆ 1~69级装  ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ 备/+1…    ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [38]:
df.filter(pl.col('stackable_type') == '[unlimited etc]')

shape: (2, 11)
┌─────┬────────────┬────────────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ id  ┆ name       ┆ name2      ┆ json       ┆ … ┆ sub_stacka ┆ item_group ┆ item_cate ┆ stackable │
│ --- ┆ ---        ┆ ---        ┆ ---        ┆   ┆ ble_type   ┆ _name      ┆ gory      ┆ _type_dis │
│ i64 ┆ str        ┆ str        ┆ str        ┆   ┆ ---        ┆ ---        ┆ ---       ┆ play      │
│     ┆            ┆            ┆            ┆   ┆ i64        ┆ str        ┆ str       ┆ ---       │
│     ┆            ┆            ┆            ┆   ┆            ┆            ┆           ┆ str       │
╞═════╪════════════╪════════════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 161 ┆ 无限遗忘之 ┆ Unlimited  ┆ {"[name]": ┆ … ┆ 0          ┆            ┆           ┆ 其他      │
│     ┆ 铃铛       ┆ Bell of    ┆ ["无限遗忘 ┆   ┆            ┆            ┆           ┆           │
│     ┆            ┆ Lethe      ┆ 之铃铛"],  ┆   ┆            ┆            ┆           ┆           │
│     ┆            ┆            ┆ "[name…    ┆   ┆            ┆            ┆           ┆           │
│ 162 ┆ 无限遗忘之 ┆ Unlimited  ┆ {"[name]": ┆ … ┆ 0          ┆            ┆           ┆ 其他      │
│     ┆ 铃铛       ┆ Bell of    ┆ ["无限遗忘 ┆   ┆            ┆            ┆           ┆           │
│     ┆            ┆ Lethe      ┆ 之铃铛"],  ┆   ┆            ┆            ┆           ┆           │
│     ┆            ┆            ┆ "[name…    ┆   ┆            ┆            ┆           ┆           │
└─────┴────────────┴────────────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

In [39]:
df.filter(pl.col('stackable_type') == '[unlimited town and dungeon]')

shape: (18, 11)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ id      ┆ name       ┆ name2     ┆ json      ┆ … ┆ sub_stack ┆ item_grou ┆ item_cate ┆ stackable │
│ ---     ┆ ---        ┆ ---       ┆ ---       ┆   ┆ able_type ┆ p_name    ┆ gory      ┆ _type_dis │
│ i64     ┆ str        ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ play      │
│         ┆            ┆           ┆           ┆   ┆ i64       ┆ str       ┆ str       ┆ ---       │
│         ┆            ┆           ┆           ┆   ┆           ┆           ┆           ┆ str       │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2600463 ┆ 最下级炼金 ┆ Lowest    ┆ {"[name]" ┆ … ┆ 0         ┆ potion    ┆           ┆ 其他      │
│         ┆ 提取器     ┆ grade     ┆ : ["最下  ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆ Alchemy   ┆ 级炼金提  ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆ Extractor ┆ 取器"],   ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆ "[nam…    ┆   ┆           ┆           ┆           ┆           │
│ 2600464 ┆ 下级炼金提 ┆ Low grade ┆ {"[name]" ┆ … ┆ 0         ┆ potion    ┆           ┆ 其他      │
│         ┆ 取器       ┆ Alchemy   ┆ : ["下级  ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆ Extractor ┆ 炼金提取  ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆ 器"],     ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆ "[name…   ┆   ┆           ┆           ┆           ┆           │
│ 2600465 ┆ 中级炼金提 ┆ Intermedi ┆ {"[name]" ┆ … ┆ 0         ┆ potion    ┆           ┆ 其他      │
│         ┆ 取器       ┆ ate grade ┆ : ["中级  ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆ Alchemy   ┆ 炼金提取  ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆ Ext…      ┆ 器"],     ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆ "[name…   ┆   ┆           ┆           ┆           ┆           │
│ 2600466 ┆ 上级炼金提 ┆ Upper     ┆ {"[name]" ┆ … ┆ 0         ┆ potion    ┆           ┆ 其他      │
│         ┆ 取器       ┆ Grade     ┆ : ["上级  ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆ Alchemy   ┆ 炼金提取  ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆ Extractor ┆ 器"],     ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆ "[name…   ┆   ┆           ┆           ┆           ┆           │
│ 2600467 ┆ 最上级炼金 ┆ Highest   ┆ {"[name]" ┆ … ┆ 0         ┆ potion    ┆           ┆ 其他      │
│         ┆ 提取器     ┆ Grade     ┆ : ["最上  ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆ Alchemy   ┆ 级炼金提  ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆ Extracto… ┆ 取器"],   ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆ "[nam…    ┆   ┆           ┆           ┆           ┆           │
│ …       ┆ …          ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 2600485 ┆ 上级魔力提 ┆ Upper     ┆ {"[name]" ┆ … ┆ 0         ┆ potion    ┆           ┆ 其他      │
│         ┆ 取器       ┆ Grade     ┆ : ["上级  ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆ Magical   ┆ 魔力提取  ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆ Powers    ┆ 器"],     ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆ Ext…      ┆ "[name…   ┆   ┆           ┆           ┆           ┆           │
│ 2600486 ┆ 最上级魔力 ┆ Highest   ┆ {"[name]" ┆ … ┆ 0         ┆ potion    ┆           ┆ 其他      │
│         ┆ 提取器     ┆ Grade     ┆ : ["最上  ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆ Magical   ┆ 级魔力提  ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆ Powers E… ┆ 取器"],   ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆ "[nam…    ┆   ┆           ┆           ┆           ┆           │
│ 2600547 ┆ 至尊炼金提 ┆           ┆ {"[name]" ┆ … ┆ 0         ┆ potion    ┆           ┆ 其他      │
│         ┆ 取器       ┆           ┆ : ["至尊  ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆ 炼金提取  ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆ 器"],     ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆ "[expl…   ┆   ┆           ┆           ┆           ┆           │
│ 2600549 ┆ 至尊灵魂提 ┆           ┆ {"[name]" ┆ … ┆ 0         ┆ potion    ┆           ┆ 其他      │
│         ┆ 取器       ┆           ┆ : ["至尊  ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆ 灵魂提取  ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆ 器"],     ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆ "[expl…   ┆   ┆           ┆           ┆           ┆           │
│ 2600550 ┆ 至尊魔力提 ┆           ┆ {"[name]" ┆ … ┆ 0         ┆ potion    ┆           ┆ 其他      │
│         ┆ 取器       ┆           ┆ : ["至尊  ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆ 魔力提取  ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆ 器"],     ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆           ┆ "[expl…   ┆   ┆           ┆           ┆           ┆           │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [40]:
df.filter(pl.col('stackable_type') == '[unlimited waste]')

shape: (60, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id        ┆ name      ┆ name2     ┆ json      ┆ … ┆ sub_stack ┆ item_grou ┆ item_cate ┆ stackabl │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ able_type ┆ p_name    ┆ gory      ┆ e_type_d │
│ i64       ┆ str       ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ isplay   │
│           ┆           ┆           ┆           ┆   ┆ i64       ┆ str       ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 51        ┆ 无限猫头  ┆ Unlimited ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 消耗品   │
│           ┆ 鹰        ┆ Owl       ┆ : ["无限  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 猫头鹰"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2]… ┆   ┆           ┆           ┆           ┆          │
│ 2660234   ┆ 无限猫头  ┆           ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 消耗品   │
│           ┆ 鹰        ┆           ┆ : ["无限  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 猫头鹰"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2]… ┆   ┆           ┆           ┆           ┆          │
│ 1120      ┆ 服务器喇  ┆ Heartbeat ┆ {"[name]" ┆ … ┆ 1         ┆           ┆           ┆ 消耗品   │
│           ┆ 叭 (GM)   ┆ Mega      ┆ : ["服务  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Phone     ┆ 器喇叭    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ (GM)      ┆ (GM)"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[n…      ┆   ┆           ┆           ┆           ┆          │
│ 1125      ┆ 戮蛊的蛹  ┆ Nugol's   ┆ {"[name]" ┆ … ┆ 1         ┆           ┆           ┆ 消耗品   │
│           ┆           ┆ Spinning  ┆ : ["戮蛊  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Projectio ┆ 的蛹"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ n         ┆ "[name2]" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆          │
│ 1126      ┆ 大地之神  ┆ Fury of   ┆ {"[name]" ┆ … ┆ 1         ┆           ┆           ┆ 消耗品   │
│           ┆ 的愤怒    ┆ Ground    ┆ : ["大地  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ God       ┆ 之神的愤  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 怒"],     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name…   ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 2749209   ┆ 巨齿鳄 (  ┆           ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 消耗品   │
│           ┆ Lv4 )     ┆           ┆ :         ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ["巨齿鳄  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ( Lv4     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ )"], "[…  ┆   ┆           ┆           ┆           ┆          │
│ 1298      ┆ 超速胶囊  ┆           ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 消耗品   │
│           ┆           ┆           ┆ : ["超速  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 胶囊"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2]" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆          │
│ 2660838   ┆ 立顿无限  ┆           ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 消耗品   │
│           ┆ 猫头鹰    ┆           ┆ : ["立顿  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 无限猫头  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 鹰"],     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name…   ┆   ┆           ┆           ┆           ┆          │
│ 490700049 ┆ 鲜脆胡萝  ┆           ┆ {"[name]" ┆ … ┆ 1         ┆ potion    ┆           ┆ 消耗品   │
│           ┆ 卜        ┆           ┆ : ["鲜脆  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 胡萝卜"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[explai… ┆   ┆           ┆           ┆           ┆          │
│ 490700050 ┆ 冰爽胡萝  ┆           ┆ {"[name]" ┆ … ┆ 1         ┆ potion    ┆           ┆ 消耗品   │
│           ┆ 卜汁      ┆           ┆ : ["冰爽  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 胡萝卜汁" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ],        ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[expla…  ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [41]:
df.filter(pl.col('stackable_type') == '[upgradable legacy]')

shape: (327, 11)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ id       ┆ name      ┆ name2     ┆ json      ┆ … ┆ sub_stack ┆ item_grou ┆ item_cate ┆ stackable │
│ ---      ┆ ---       ┆ ---       ┆ ---       ┆   ┆ able_type ┆ p_name    ┆ gory      ┆ _type_dis │
│ i64      ┆ str       ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ play      │
│          ┆           ┆           ┆           ┆   ┆ i64       ┆ str       ┆ str       ┆ ---       │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ str       │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 7110     ┆ 土罐的袖  ┆ Ancient   ┆ {"[name]" ┆ … ┆ 1         ┆           ┆           ┆ 袖珍罐    │
│          ┆ 珍罐      ┆ Jar of    ┆ : ["土罐  ┆   ┆           ┆           ┆           ┆           │
│          ┆ (首饰)    ┆ Accessari ┆ 的袖珍罐  ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆ es        ┆ (首饰)"], ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ "[…       ┆   ┆           ┆           ┆           ┆           │
│ 7111     ┆ 火罐的袖  ┆ Ancient   ┆ {"[name]" ┆ … ┆ 1         ┆           ┆           ┆ 袖珍罐    │
│          ┆ 珍罐      ┆ Jar of    ┆ : ["火罐  ┆   ┆           ┆           ┆           ┆           │
│          ┆ (首饰)    ┆ Accessari ┆ 的袖珍罐  ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆ es        ┆ (首饰)"], ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ "[…       ┆   ┆           ┆           ┆           ┆           │
│ 7112     ┆ 木罐的袖  ┆ Ancient   ┆ {"[name]" ┆ … ┆ 1         ┆           ┆           ┆ 袖珍罐    │
│          ┆ 珍罐      ┆ Jar of    ┆ : ["木罐  ┆   ┆           ┆           ┆           ┆           │
│          ┆ (首饰)    ┆ Accessari ┆ 的袖珍罐  ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆ es        ┆ (首饰)"], ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ "[…       ┆   ┆           ┆           ┆           ┆           │
│ 7113     ┆ 水罐的袖  ┆ Ancient   ┆ {"[name]" ┆ … ┆ 1         ┆           ┆           ┆ 袖珍罐    │
│          ┆ 珍罐      ┆ Jar of    ┆ : ["水罐  ┆   ┆           ┆           ┆           ┆           │
│          ┆ (首饰)    ┆ Accessari ┆ 的袖珍罐  ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆ es        ┆ (首饰)"], ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ "[…       ┆   ┆           ┆           ┆           ┆           │
│ 7114     ┆ 金罐的袖  ┆ Ancient   ┆ {"[name]" ┆ … ┆ 1         ┆           ┆           ┆ 袖珍罐    │
│          ┆ 珍罐      ┆ Jar of    ┆ : ["金罐  ┆   ┆           ┆           ┆           ┆           │
│          ┆ (首饰)    ┆ Accessari ┆ 的袖珍罐  ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆ es        ┆ (首饰)"], ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ "[…       ┆   ┆           ┆           ┆           ┆           │
│ …        ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 2749106  ┆ 灵魂袖珍  ┆           ┆ {"[name]" ┆ … ┆ 1         ┆           ┆           ┆ 袖珍罐    │
│          ┆ 罐 (神枪  ┆           ┆ : ["灵魂  ┆   ┆           ┆           ┆           ┆           │
│          ┆ 手武器)   ┆           ┆ 袖珍罐    ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ (神枪手武 ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ 器)"], …  ┆   ┆           ┆           ┆           ┆           │
│ 2749107  ┆ 灵魂袖珍  ┆           ┆ {"[name]" ┆ … ┆ 1         ┆           ┆           ┆ 袖珍罐    │
│          ┆ 罐 (魔法  ┆           ┆ : ["灵魂  ┆   ┆           ┆           ┆           ┆           │
│          ┆ 师武器)   ┆           ┆ 袖珍罐    ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ (魔法师武 ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ 器)"], …  ┆   ┆           ┆           ┆           ┆           │
│ 2749108  ┆ 灵魂袖珍  ┆           ┆ {"[name]" ┆ … ┆ 1         ┆           ┆           ┆ 袖珍罐    │
│          ┆ 罐 (圣职  ┆           ┆ : ["灵魂  ┆   ┆           ┆           ┆           ┆           │
│          ┆ 者武器)   ┆           ┆ 袖珍罐    ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ (圣职者武 ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ 器)"], …  ┆   ┆           ┆           ┆           ┆           │
│ 2749109  ┆ 灵魂袖珍  ┆           ┆ {"[name]" ┆ … ┆ 1         ┆           ┆           ┆ 袖珍罐    │
│          ┆ 罐 (暗夜  ┆           ┆ : ["灵魂  ┆   ┆           ┆           ┆           ┆           │
│          ┆ 使者武器) ┆           ┆ 袖珍罐    ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ (暗夜使者 ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ 武器)"],… ┆   ┆           ┆           ┆           ┆           │
│ 10093401 ┆ 秘密机械  ┆           ┆ {"[name]" ┆ … ┆ 1         ┆           ┆           ┆ 袖珍罐    │
│          ┆ 保险柜    ┆           ┆ : ["秘密  ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ 机械保险  ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ 柜"],     ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ "[expl…   ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [42]:
df.filter(pl.col('stackable_type') == '[upgrade limit cube]')

shape: (3, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id        ┆ name      ┆ name2     ┆ json      ┆ … ┆ sub_stack ┆ item_grou ┆ item_cate ┆ stackabl │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ able_type ┆ p_name    ┆ gory      ┆ e_type_d │
│ i64       ┆ str       ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ isplay   │
│           ┆           ┆           ┆           ┆   ┆ i64       ┆ str       ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 7942      ┆ 限定的大  ┆ Limited   ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 礼包     │
│           ┆ 晶体 (红  ┆ Cube      ┆ : ["限定  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 色气息)   ┆           ┆ 的大晶体  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ (红色气息 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ )"], …    ┆   ┆           ┆           ┆           ┆          │
│ 7953      ┆ 限定的大  ┆ Limited   ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 礼包     │
│           ┆ 晶体 (蓝  ┆ Cube      ┆ : ["限定  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 色气息)   ┆           ┆ 的大晶体  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ (蓝色气息 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ )"], …    ┆   ┆           ┆           ┆           ┆          │
│ 690000274 ┆ 封印的大  ┆ mage      ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 礼包     │
│           ┆ 魔法师武  ┆ unique    ┆ : ["封印  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 器宝箱    ┆ box 1     ┆ 的大魔法  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 师武器宝  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 箱"], "[… ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [43]:
df.filter(pl.col('stackable_type') == '[usable cera package]')

shape: (1_693, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id        ┆ name      ┆ name2     ┆ json      ┆ … ┆ sub_stack ┆ item_grou ┆ item_cate ┆ stackabl │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ able_type ┆ p_name    ┆ gory      ┆ e_type_d │
│ i64       ┆ str       ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ isplay   │
│           ┆           ┆           ┆           ┆   ┆ i64       ┆ str       ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 74        ┆ 月下之赐  ┆ Teaching  ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 礼包     │
│           ┆ 教1       ┆ Under     ┆ : ["月下  ┆   ┆           ┆           ┆           ┆          │
│           ┆ (鬼剑士)  ┆ Moonlight ┆ 之赐教1   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ (鬼剑士)" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ], "…     ┆   ┆           ┆           ┆           ┆          │
│ 75        ┆ 月下之赐  ┆ Teaching  ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 礼包     │
│           ┆ 教2       ┆ Under     ┆ : ["月下  ┆   ┆           ┆           ┆           ┆          │
│           ┆ (鬼剑士)  ┆ Moonlight ┆ 之赐教2   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ (鬼剑士)" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ], "…     ┆   ┆           ┆           ┆           ┆          │
│ 76        ┆ 月下之赐  ┆ Teaching  ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 礼包     │
│           ┆ 教1 (格斗 ┆ Under     ┆ : ["月下  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 家-女)    ┆ Moonlight ┆ 之赐教1   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ (格斗家-  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 女)"],…   ┆   ┆           ┆           ┆           ┆          │
│ 77        ┆ 月下之赐  ┆ Teaching  ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 礼包     │
│           ┆ 教2(格斗  ┆ Under     ┆ : ["月下  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 家-女)    ┆ Moonlight ┆ 之赐教2(  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 格斗家-女 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ )"], …    ┆   ┆           ┆           ┆           ┆          │
│ 78        ┆ 月下之赐  ┆ Teaching  ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 礼包     │
│           ┆ 教1 (神枪 ┆ Under     ┆ : ["月下  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 手-男)    ┆ Moonlight ┆ 之赐教1   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ (神枪手-  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 男)"],…   ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 690001669 ┆ 2014艳阳  ┆           ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 礼包     │
│           ┆ 夏日礼包- ┆           ┆ : ["2014  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 暗夜使者B ┆           ┆ 艳阳夏日  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 礼包-暗夜 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 使者B"…   ┆   ┆           ┆           ┆           ┆          │
│ 690001670 ┆ 2014艳阳  ┆           ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 礼包     │
│           ┆ 夏日礼包- ┆           ┆ : ["2014  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 魔法师(男 ┆           ┆ 艳阳夏日  ┆   ┆           ┆           ┆           ┆          │
│           ┆ )A        ┆           ┆ 礼包-魔法 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 师(男)…   ┆   ┆           ┆           ┆           ┆          │
│ 690001671 ┆ 2014艳阳  ┆           ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 礼包     │
│           ┆ 夏日礼包- ┆           ┆ : ["2014  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 魔法师(男 ┆           ┆ 艳阳夏日  ┆   ┆           ┆           ┆           ┆          │
│           ┆ )B        ┆           ┆ 礼包-魔法 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 师(男)…   ┆   ┆           ┆           ┆           ┆          │
│ 690001646 ┆ 2014艳阳  ┆           ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 礼包     │
│           ┆ 夏日礼包- ┆           ┆ : ["2014  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 缔造者A   ┆           ┆ 艳阳夏日  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 礼包-缔造 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 者A"]…    ┆   ┆           ┆           ┆           ┆          │
│ 690001647 ┆ 2014艳阳  ┆           ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 礼包     │
│           ┆ 夏日礼包- ┆           ┆ : ["2014  ┆   ┆           ┆           ┆           ┆          │
│           ┆ 缔造者B   ┆           ┆ 艳阳夏日  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 礼包-缔造 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 者B"]…    ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [44]:
df.filter(pl.col('stackable_type') == '[waste]')

shape: (762, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id        ┆ name      ┆ name2     ┆ json      ┆ … ┆ sub_stack ┆ item_grou ┆ item_cate ┆ stackabl │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ able_type ┆ p_name    ┆ gory      ┆ e_type_d │
│ i64       ┆ str       ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ isplay   │
│           ┆           ┆           ┆           ┆   ┆ i64       ┆ str       ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0         ┆ 金币      ┆ Gold      ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 消耗品   │
│           ┆           ┆           ┆ :         ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ["金币"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2]" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ : …       ┆   ┆           ┆           ┆           ┆          │
│ 8         ┆ 雷米的援  ┆ Hands of  ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 消耗品   │
│           ┆ 助        ┆ Remy      ┆ : ["雷米  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 的援助"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2]… ┆   ┆           ┆           ┆           ┆          │
│ 10        ┆ 猫头鹰    ┆ Owl       ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 消耗品   │
│           ┆           ┆           ┆ : ["猫头  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 鹰"], "[n ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ame2]":…  ┆   ┆           ┆           ┆           ┆          │
│ 36        ┆ 服务器喇  ┆ Heartbeat ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 消耗品   │
│           ┆ 叭        ┆ Mega      ┆ : ["服务  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Phone     ┆ 器喇叭"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2]… ┆   ┆           ┆           ┆           ┆          │
│ 37        ┆ 频道喇叭  ┆ Echo Mega ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 消耗品   │
│           ┆           ┆ Phone     ┆ : ["频道  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 喇叭"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2]" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ …         ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 690000703 ┆ 远古精灵  ┆ twdf good ┆ {"[name]" ┆ … ┆ 0         ┆           ┆           ┆ 消耗品   │
│           ┆ 的秘药    ┆ review    ┆ : ["远古  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ event     ┆ 精灵的秘  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ growth …  ┆ 药"],     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name…   ┆   ┆           ┆           ┆           ┆          │
│ 690000770 ┆ 后勤支援  ┆           ┆ {"[name]" ┆ … ┆ 0         ┆ potion    ┆           ┆ 消耗品   │
│           ┆ 抗魔药剂  ┆           ┆ : ["后勤  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 支援抗魔  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 药剂"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[nam…    ┆   ┆           ┆           ┆           ┆          │
│ 690000777 ┆ 后勤支援  ┆           ┆ {"[name]" ┆ … ┆ 0         ┆ potion    ┆           ┆ 消耗品   │
│           ┆ 药水      ┆           ┆ : ["后勤  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 支援药水" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ],        ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[expla…  ┆   ┆           ┆           ┆           ┆          │
│ 690000791 ┆ 万圣节南  ┆           ┆ {"[name]" ┆ … ┆ 0         ┆ potion    ┆           ┆ 消耗品   │
│           ┆ 瓜糖果    ┆           ┆ : ["万圣  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 节南瓜糖  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 果"],     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[expl…   ┆   ┆           ┆           ┆           ┆          │
│ 2668888   ┆ 赛丽亚的  ┆ Shining   ┆ {"[name]" ┆ … ┆ 0         ┆ potion    ┆           ┆ 消耗品   │
│           ┆ 援助      ┆ Hands of  ┆ : ["赛丽  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Seria     ┆ 亚的援助" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ],        ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2…  ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [45]:
df.select(pl.col('item_category')).unique()

shape: (2, 1)
┌───────────────┐
│ item_category │
│ ---           │
│ str           │
╞═══════════════╡
│ monster card  │
│               │
└───────────────┘

In [46]:
# query card
df.filter(pl.col('item_category') == 'monster card')

shape: (244, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id        ┆ name      ┆ name2     ┆ json      ┆ … ┆ sub_stack ┆ item_grou ┆ item_cate ┆ stackabl │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ able_type ┆ p_name    ┆ gory      ┆ e_type_d │
│ i64       ┆ str       ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ isplay   │
│           ┆           ┆           ┆           ┆   ┆ i64       ┆ str       ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 3600      ┆ 光之城主  ┆ Sieghart  ┆ {"[name]" ┆ … ┆ 1         ┆           ┆ monster   ┆ 卡片     │
│           ┆ 赛格哈特  ┆ : Lord of ┆ : ["光之  ┆   ┆           ┆           ┆ card      ┆          │
│           ┆ 卡片      ┆ Light's   ┆ 城主赛格  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Cas…      ┆ 哈特      ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 卡片"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "…        ┆   ┆           ┆           ┆           ┆          │
│ 3601      ┆ 长脚罗特  ┆ Lotus of  ┆ {"[name]" ┆ … ┆ 1         ┆           ┆ monster   ┆ 卡片     │
│           ┆ 斯  卡片  ┆ Long Foot ┆ : ["长脚  ┆   ┆           ┆           ┆ card      ┆          │
│           ┆           ┆ Card      ┆ 罗特斯    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 卡片"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[na…     ┆   ┆           ┆           ┆           ┆          │
│ 3602      ┆ 邪龙斯皮  ┆ Head of   ┆ {"[name]" ┆ … ┆ 1         ┆           ┆ monster   ┆ 卡片     │
│           ┆ 兹头部    ┆ Spirrazzi ┆ : ["邪龙  ┆   ┆           ┆           ┆ card      ┆          │
│           ┆ 卡片      ┆ : Dead    ┆ 斯皮兹头  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Drago…    ┆ 部        ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 卡片"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[…       ┆   ┆           ┆           ┆           ┆          │
│ 3603      ┆ 魔笛使者  ┆ Peter The ┆ {"[name]" ┆ … ┆ 1         ┆           ┆ monster   ┆ 卡片     │
│           ┆ 皮特      ┆ Piper     ┆ : ["魔笛  ┆   ┆           ┆           ┆ card      ┆          │
│           ┆ 卡片      ┆ Card      ┆ 使者皮特  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 卡片"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[n…      ┆   ┆           ┆           ┆           ┆          │
│ 3604      ┆ 烈焰彼诺  ┆ Vinoshu   ┆ {"[name]" ┆ … ┆ 1         ┆           ┆ monster   ┆ 卡片     │
│           ┆ 修  卡片  ┆ of Flame  ┆ : ["烈焰  ┆   ┆           ┆           ┆ card      ┆          │
│           ┆           ┆ Card      ┆ 彼诺修    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 卡片"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[na…     ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 10007738  ┆ 迷你狄瑞  ┆           ┆ {"[name]" ┆ … ┆ 1         ┆           ┆ monster   ┆ 卡片     │
│           ┆ 吉卡片    ┆           ┆ : ["迷你  ┆   ┆           ┆           ┆ card      ┆          │
│           ┆           ┆           ┆ 狄瑞吉卡  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 片"],     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[grad…   ┆   ┆           ┆           ┆           ┆          │
│ 10007737  ┆ 迷你狄瑞  ┆           ┆ {"[name]" ┆ … ┆ 1         ┆           ┆ monster   ┆ 卡片     │
│           ┆ 吉的幻影  ┆           ┆ : ["迷你  ┆   ┆           ┆           ┆ card      ┆          │
│           ┆ 卡片      ┆           ┆ 狄瑞吉的  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 幻影卡片" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ], "[g…   ┆   ┆           ┆           ┆           ┆          │
│ 10008651  ┆ 春联仙娥  ┆           ┆ {"[name]" ┆ … ┆ 1         ┆           ┆ monster   ┆ 卡片     │
│           ┆ 卡片 -    ┆           ┆ : ["春联  ┆   ┆           ┆           ┆ card      ┆          │
│           ┆ 雪莲      ┆           ┆ 仙娥卡片  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ - 雪莲"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[…       ┆   ┆           ┆           ┆           ┆          │
│ 10008650  ┆ 春联仙娥  ┆           ┆ {"[name]" ┆ … ┆ 1         ┆           ┆ monster   ┆ 卡片     │
│           ┆ 卡片 -    ┆           ┆ : ["春联  ┆   ┆           ┆           ┆ card      ┆          │
│           ┆ 尔怜      ┆           ┆ 仙娥卡片  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ - 尔怜"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[…       ┆   ┆           ┆           ┆           ┆          │
│ 690000299 ┆ 勇者的祝  ┆ summer    ┆ {"[name]" ┆ … ┆ 1         ┆           ┆ monster   ┆ 卡片     │
│           ┆ 福        ┆ bead      ┆ : ["勇者  ┆   ┆           ┆           ┆ card      ┆          │
│           ┆           ┆           ┆ 的祝福"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2]… ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [47]:
df.schema

Schema([('id', Int64),
        ('name', String),
        ('name2', String),
        ('json', String),
        ('level', Int64),
        ('rarity', Int64),
        ('stackable_type', String),
        ('sub_stackable_type', Int64),
        ('item_group_name', String),
        ('item_category', String),
        ('stackable_type_display', String)])

In [48]:
df.filter(pl.col('stackable_type_display') == '卡片')

shape: (244, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id        ┆ name      ┆ name2     ┆ json      ┆ … ┆ sub_stack ┆ item_grou ┆ item_cate ┆ stackabl │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ able_type ┆ p_name    ┆ gory      ┆ e_type_d │
│ i64       ┆ str       ┆ str       ┆ str       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ isplay   │
│           ┆           ┆           ┆           ┆   ┆ i64       ┆ str       ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 3600      ┆ 光之城主  ┆ Sieghart  ┆ {"[name]" ┆ … ┆ 1         ┆           ┆ monster   ┆ 卡片     │
│           ┆ 赛格哈特  ┆ : Lord of ┆ : ["光之  ┆   ┆           ┆           ┆ card      ┆          │
│           ┆ 卡片      ┆ Light's   ┆ 城主赛格  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Cas…      ┆ 哈特      ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 卡片"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "…        ┆   ┆           ┆           ┆           ┆          │
│ 3601      ┆ 长脚罗特  ┆ Lotus of  ┆ {"[name]" ┆ … ┆ 1         ┆           ┆ monster   ┆ 卡片     │
│           ┆ 斯  卡片  ┆ Long Foot ┆ : ["长脚  ┆   ┆           ┆           ┆ card      ┆          │
│           ┆           ┆ Card      ┆ 罗特斯    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 卡片"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[na…     ┆   ┆           ┆           ┆           ┆          │
│ 3602      ┆ 邪龙斯皮  ┆ Head of   ┆ {"[name]" ┆ … ┆ 1         ┆           ┆ monster   ┆ 卡片     │
│           ┆ 兹头部    ┆ Spirrazzi ┆ : ["邪龙  ┆   ┆           ┆           ┆ card      ┆          │
│           ┆ 卡片      ┆ : Dead    ┆ 斯皮兹头  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Drago…    ┆ 部        ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 卡片"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[…       ┆   ┆           ┆           ┆           ┆          │
│ 3603      ┆ 魔笛使者  ┆ Peter The ┆ {"[name]" ┆ … ┆ 1         ┆           ┆ monster   ┆ 卡片     │
│           ┆ 皮特      ┆ Piper     ┆ : ["魔笛  ┆   ┆           ┆           ┆ card      ┆          │
│           ┆ 卡片      ┆ Card      ┆ 使者皮特  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 卡片"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[n…      ┆   ┆           ┆           ┆           ┆          │
│ 3604      ┆ 烈焰彼诺  ┆ Vinoshu   ┆ {"[name]" ┆ … ┆ 1         ┆           ┆ monster   ┆ 卡片     │
│           ┆ 修  卡片  ┆ of Flame  ┆ : ["烈焰  ┆   ┆           ┆           ┆ card      ┆          │
│           ┆           ┆ Card      ┆ 彼诺修    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 卡片"],   ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[na…     ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 10007738  ┆ 迷你狄瑞  ┆           ┆ {"[name]" ┆ … ┆ 1         ┆           ┆ monster   ┆ 卡片     │
│           ┆ 吉卡片    ┆           ┆ : ["迷你  ┆   ┆           ┆           ┆ card      ┆          │
│           ┆           ┆           ┆ 狄瑞吉卡  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 片"],     ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[grad…   ┆   ┆           ┆           ┆           ┆          │
│ 10007737  ┆ 迷你狄瑞  ┆           ┆ {"[name]" ┆ … ┆ 1         ┆           ┆ monster   ┆ 卡片     │
│           ┆ 吉的幻影  ┆           ┆ : ["迷你  ┆   ┆           ┆           ┆ card      ┆          │
│           ┆ 卡片      ┆           ┆ 狄瑞吉的  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ 幻影卡片" ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ ], "[g…   ┆   ┆           ┆           ┆           ┆          │
│ 10008651  ┆ 春联仙娥  ┆           ┆ {"[name]" ┆ … ┆ 1         ┆           ┆ monster   ┆ 卡片     │
│           ┆ 卡片 -    ┆           ┆ : ["春联  ┆   ┆           ┆           ┆ card      ┆          │
│           ┆ 雪莲      ┆           ┆ 仙娥卡片  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ - 雪莲"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[…       ┆   ┆           ┆           ┆           ┆          │
│ 10008650  ┆ 春联仙娥  ┆           ┆ {"[name]" ┆ … ┆ 1         ┆           ┆ monster   ┆ 卡片     │
│           ┆ 卡片 -    ┆           ┆ : ["春联  ┆   ┆           ┆           ┆ card      ┆          │
│           ┆ 尔怜      ┆           ┆ 仙娥卡片  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ - 尔怜"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[…       ┆   ┆           ┆           ┆           ┆          │
│ 690000299 ┆ 勇者的祝  ┆ summer    ┆ {"[name]" ┆ … ┆ 1         ┆           ┆ monster   ┆ 卡片     │
│           ┆ 福        ┆ bead      ┆ : ["勇者  ┆   ┆           ┆           ┆ card      ┆          │
│           ┆           ┆           ┆ 的祝福"], ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ "[name2]… ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [49]:
df.select(pl.col('rarity')).unique()

shape: (6, 1)
┌────────┐
│ rarity │
│ ---    │
│ i64    │
╞════════╡
│ 3      │
│ 0      │
│ 1      │
│ 4      │
│ 2      │
│ 5      │
└────────┘